/*
 * GENERATED by tools/reference/trace_to_c.py. Do not edit by hand.
 * The record types of the conformance tables (conformance.h and
 * conformance_team_c.h) and of the comparators that read them.
 */
#ifndef DUOFORGE_TESTS_REFERENCE_CONFORMANCE_TYPES_H
#define DUOFORGE_TESTS_REFERENCE_CONFORMANCE_TYPES_H
#include <stdint.h>

/* species, gender, nature, Stat Points, ability + 1 (0 none), item + 1 (0 none), moves */
typedef struct df_conf_member {
    uint32_t species, gender, nature, sp[6], ability, item, move_count, moves[4];
} df_conf_member;
/* kind, move_slot, target, mega, reserve */
typedef struct df_conf_cmd {
    uint8_t kind, move_slot, target, mega, reserve;
} df_conf_cmd;
/* present, hp, pp, stages (biased by 6), stall counter present, fainted,
 * status (DFI_STATUS_*), its counter (sleep, freeze), confusion turns, the
 * locked move slot (0xFF none) and its target, Mega forme, the item still
 * held, and what the opponent has seen: seen, HP percent and colour flag
 * of the last public display (DUOFORGE_HP_FLAG_*) */
typedef struct df_conf_mon {
    uint32_t present, hp;
    uint8_t pp[4];
    uint8_t stages[7];
    uint8_t stall, fainted, status, status_counter, confusion, locked_slot, locked_target, mega;
    uint8_t held, seen, seen_percent, seen_flag;
    uint8_t vols; /* volatiles: 1 protect, 2 flashfire, 4 twoturnmove, 8 choicelock, 16 unburden, 32 helpinghand */
} df_conf_mon;
/* team step, side 0 / side 1 answered, tape slice, the turn, boundary and
 * result afterwards, the picks of a team step, slot commands, the occupants
 * of the positions afterwards (roster index, 0xFF empty), the positions
 * (side * 2 + slot) that received a Pokemon in the reference's order (0xFF
 * pads), weather, its turns, terrain, its turns, Trick Room turns, per
 * side Tailwind, Reflect and Light Screen turns, the moves the request
 * offers per slot (bit k move k, 0x10 Struggle, 0xFF none), the expected
 * members by roster index */
typedef struct df_conf_step {
    uint32_t team, answered0, answered1, tape_off, tape_len, turn, boundary, result;
    uint8_t picks[2][6];
    df_conf_cmd cmds[2][2];
    uint8_t occupants[2][2];
    uint8_t entries[4];
    uint8_t field[11];
    uint8_t enabled[2][2];
    df_conf_mon mons[2][6];
    uint32_t ev_off[2], ev_len[2]; /* each player's events of the step in conf_events */
} df_conf_step;
typedef struct df_conf_battle {
    const char *name;
    uint32_t member_count;
    const df_conf_member (*members)[6];
    const df_conf_step *steps;
    uint32_t step_count;
    uint32_t dropped;
} df_conf_battle;

#endif
