/*
 * GENERATED by tools/reference/trace_to_c.py from tests/reference/specs and
 * tests/reference/traces (pinned Showdown b2cb775b0616115b775534eaeff50300e1fc81fc).
 * Do not edit by hand. Draw drop rules: tools/reference/trace_to_c.py.
 */
#ifndef DUOFORGE_TESTS_REFERENCE_CONFORMANCE_H
#define DUOFORGE_TESTS_REFERENCE_CONFORMANCE_H
#include <stdint.h>

#include "rng/draw.h"

/* species, gender, nature, Stat Points, ability + 1 (0 none), item + 1 (0 none), moves */
typedef struct df_conf_member {
    uint32_t species, gender, nature, sp[6], ability, item, move_count, moves[4];
} df_conf_member;
/* kind, move_slot, target, mega, reserve */
typedef struct df_conf_cmd {
    uint8_t kind, move_slot, target, mega, reserve;
} df_conf_cmd;
/* present, hp, pp, stages (biased by 6), stall counter present, fainted */
typedef struct df_conf_mon {
    uint32_t present, hp;
    uint8_t pp[4];
    uint8_t stages[7];
    uint8_t stall, fainted;
} df_conf_mon;
/* team step, side 0 / side 1 answered, tape slice, the turn afterwards, the
 * picks of a team step, slot commands, the expected members by roster index */
typedef struct df_conf_step {
    uint32_t team, answered0, answered1, tape_off, tape_len, turn;
    uint8_t picks[2][6];
    df_conf_cmd cmds[2][2];
    df_conf_mon mons[2][6];
} df_conf_step;
typedef struct df_conf_battle {
    const char *name;
    uint32_t member_count;
    const df_conf_member (*members)[6];
    const df_conf_step *steps;
    uint32_t step_count;
    uint32_t dropped;
} df_conf_battle;

/* s2_ally_target: Single-target moves into the partner (allowed in doubles): Drill Run and Psychic at the ally, Dragon Pulse at an ally that protects itself. */
static const df_conf_member conf_s2_ally_target_members[2][6] = {
    {{9u, 2u, 0u, {32u, 32u, 0u, 0u, 1u, 1u}, 0u, 0u, 2u, {23u, 7u, 0u, 0u}}, {12u, 2u, 2u, {29u, 0u, 20u, 0u, 17u, 0u}, 0u, 0u, 2u, {27u, 7u, 0u, 0u}}, {3u, 2u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {11u, 2u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 2u, {24u, 7u, 0u, 0u}}},
    {{11u, 1u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 2u, {24u, 7u, 0u, 0u}}, {12u, 1u, 2u, {29u, 0u, 20u, 0u, 17u, 0u}, 0u, 0u, 2u, {27u, 7u, 0u, 0u}}, {3u, 1u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {9u, 1u, 0u, {32u, 32u, 0u, 0u, 1u, 1u}, 0u, 0u, 2u, {23u, 7u, 0u, 0u}}},
};
static const df_conf_step conf_s2_ally_target_steps[] = {
    {1u, 1u, 1u, 0u, 0u, 1u, {{0u, 1u, 2u, 3u, 0u, 0u}, {0u, 1u, 2u, 3u, 0u, 0u}}, {{{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}, {{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}}, {{{1u, 182u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 224u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 197u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 224u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 5 draws dropped */
    {0u, 1u, 1u, 0u, 7u, 2u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 1u, 0u, 0u}, {1u, 0u, 0u, 0u, 0u}}, {{1u, 0u, 3u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}}, {{{1u, 119u, {11u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 141u, {11u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 197u, {11u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 224u, {12u, 7u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 14 draws dropped */
    {0u, 1u, 1u, 7u, 12u, 3u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 1u, 255u, 0u, 0u}, {1u, 0u, 2u, 0u, 0u}}, {{1u, 0u, 0u, 0u, 0u}, {1u, 0u, 2u, 0u, 0u}}}, {{{1u, 119u, {11u, 7u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 141u, {10u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 132u, {10u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 224u, {11u, 7u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 14 draws dropped */
};
/* s2_protect_last: Protect by all four: the last to act has nobody acting after it and fails without a stall draw (queue.willAct); then repeated Protect with the stall counter and a move into Protect. */
static const df_conf_member conf_s2_protect_last_members[2][6] = {
    {{9u, 2u, 0u, {32u, 32u, 0u, 0u, 1u, 1u}, 0u, 0u, 2u, {7u, 23u, 0u, 0u}}, {4u, 2u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 2u, {7u, 13u, 0u, 0u}}, {3u, 2u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {11u, 2u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 2u, {7u, 24u, 0u, 0u}}},
    {{7u, 3u, 15u, {17u, 0u, 2u, 17u, 16u, 14u}, 0u, 0u, 2u, {7u, 18u, 0u, 0u}}, {11u, 1u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 2u, {7u, 24u, 0u, 0u}}, {3u, 1u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {4u, 1u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 2u, {7u, 13u, 0u, 0u}}},
};
static const df_conf_step conf_s2_protect_last_steps[] = {
    {1u, 1u, 1u, 19u, 0u, 1u, {{0u, 1u, 2u, 3u, 0u, 0u}, {0u, 1u, 2u, 3u, 0u, 0u}}, {{{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}, {{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}}, {{{1u, 182u, {8u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {8u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {8u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {8u, 16u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {8u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {8u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 1 draws dropped */
    {0u, 1u, 1u, 19u, 0u, 2u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {7u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {7u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {8u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {7u, 16u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 197u, {7u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {8u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 3 draws dropped */
    {0u, 1u, 1u, 19u, 3u, 3u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {6u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {6u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {8u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {6u, 16u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {6u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {8u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 1 draws dropped */
    {0u, 1u, 1u, 22u, 3u, 4u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 1u, 2u, 0u, 0u}, {1u, 1u, 2u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 1u, 1u, 0u, 0u}}}, {{{1u, 182u, {6u, 11u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 123u, {6u, 19u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {8u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {5u, 16u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 197u, {6u, 11u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {8u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 1 draws dropped */
    {0u, 1u, 1u, 25u, 1u, 5u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {5u, 11u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 123u, {5u, 19u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {8u, 12u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {4u, 16u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {5u, 11u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {8u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 2 draws dropped */
};
/* s2_stages: Stat stages inside damage and accuracy: Snarl lowers the special attackers every turn and a critical hit of a lowered attacker ignores the drop; Coil raises Milotic's accuracy, and Muddy Water lowers the accuracy of whoever it hits. */
static const df_conf_member conf_s2_stages_members[2][6] = {
    {{11u, 1u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 2u, {26u, 7u, 0u, 0u}}, {3u, 2u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 2u, {8u, 9u, 0u, 0u}}, {4u, 2u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 1u, {14u, 0u, 0u, 0u}}, {0u, 1u, 0u, {18u, 32u, 2u, 0u, 6u, 8u}, 0u, 0u, 1u, {3u, 0u, 0u, 0u}}},
    {{8u, 1u, 15u, {32u, 0u, 0u, 30u, 0u, 4u}, 0u, 0u, 1u, {8u, 0u, 0u, 0u}}, {12u, 2u, 2u, {29u, 0u, 20u, 0u, 17u, 0u}, 0u, 0u, 2u, {27u, 7u, 0u, 0u}}, {4u, 1u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 1u, {14u, 0u, 0u, 0u}}, {0u, 2u, 0u, {18u, 32u, 2u, 0u, 6u, 8u}, 0u, 0u, 1u, {3u, 0u, 0u, 0u}}},
};
static const df_conf_step conf_s2_stages_steps[] = {
    {1u, 1u, 1u, 26u, 0u, 1u, {{0u, 1u, 2u, 3u, 0u, 0u}, {0u, 1u, 2u, 3u, 0u, 0u}}, {{{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}, {{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}}, {{{1u, 197u, {16u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {12u, 20u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 197u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 224u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 2 draws dropped */
    {0u, 1u, 1u, 26u, 20u, 2u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 0u, 0u, 0u}}}, {{{1u, 130u, {15u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u}, {1u, 190u, {12u, 19u, 0u, 0u}, {7u, 7u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 166u, {11u, 0u, 0u, 0u}, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 180u, {11u, 8u, 0u, 0u}, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 10 draws dropped */
    {0u, 1u, 1u, 46u, 20u, 3u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 0u, 0u, 0u}}}, {{{1u, 98u, {14u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u}, {1u, 181u, {12u, 18u, 0u, 0u}, {8u, 8u, 6u, 6u, 6u, 7u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 145u, {10u, 0u, 0u, 0u}, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 138u, {10u, 8u, 0u, 0u}, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 10 draws dropped */
    {0u, 1u, 1u, 66u, 28u, 4u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 0u, 0u, 0u}}}, {{{1u, 72u, {13u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u}, {1u, 174u, {11u, 18u, 0u, 0u}, {8u, 8u, 6u, 6u, 6u, 7u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 103u, {9u, 0u, 0u, 0u}, {6u, 6u, 3u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 48u, {9u, 8u, 0u, 0u}, {6u, 6u, 3u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 15 draws dropped */
    {0u, 1u, 1u, 94u, 17u, 5u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 0u, 0u, 0u}}}, {{{1u, 49u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u}, {1u, 168u, {11u, 17u, 0u, 0u}, {9u, 9u, 6u, 6u, 6u, 8u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 83u, {8u, 0u, 0u, 0u}, {6u, 6u, 2u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 48u, {8u, 8u, 0u, 0u}, {6u, 6u, 3u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 10 draws dropped */
    {0u, 1u, 1u, 111u, 17u, 6u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 0u, 0u, 0u}}}, {{{1u, 28u, {11u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u}, {1u, 139u, {11u, 16u, 0u, 0u}, {10u, 10u, 6u, 6u, 6u, 8u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 60u, {7u, 0u, 0u, 0u}, {6u, 6u, 1u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 48u, {7u, 8u, 0u, 0u}, {6u, 6u, 3u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 10 draws dropped */
    {0u, 1u, 1u, 128u, 16u, 7u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 0u, 0u, 0u}}}, {{{1u, 14u, {10u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u}, {1u, 139u, {10u, 16u, 0u, 0u}, {10u, 10u, 6u, 6u, 6u, 8u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 39u, {6u, 0u, 0u, 0u}, {6u, 6u, 1u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 5u, {6u, 8u, 0u, 0u}, {6u, 6u, 3u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 15 draws dropped */
};
/* s2_struggle: PP running out: Golisopod knows only Protect (8 PP) and must Struggle afterwards (random target, recoil); repeated Protect with the stall counter; the opponents only Coil. */
static const df_conf_member conf_s2_struggle_members[2][6] = {
    {{9u, 2u, 0u, {32u, 32u, 0u, 0u, 1u, 1u}, 0u, 0u, 1u, {7u, 0u, 0u, 0u}}, {3u, 2u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {4u, 1u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 1u, {14u, 0u, 0u, 0u}}, {7u, 3u, 15u, {17u, 0u, 2u, 17u, 16u, 14u}, 0u, 0u, 1u, {19u, 0u, 0u, 0u}}},
    {{3u, 1u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {11u, 1u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 1u, {7u, 0u, 0u, 0u}}, {4u, 2u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 1u, {14u, 0u, 0u, 0u}}, {7u, 3u, 15u, {17u, 0u, 2u, 17u, 16u, 14u}, 0u, 0u, 1u, {19u, 0u, 0u, 0u}}},
};
static const df_conf_step conf_s2_struggle_steps[] = {
    {1u, 1u, 1u, 144u, 0u, 1u, {{0u, 1u, 2u, 3u, 0u, 0u}, {0u, 1u, 2u, 3u, 0u, 0u}}, {{{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}, {{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}}, {{{1u, 182u, {8u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {8u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 5 draws dropped */
    {0u, 1u, 1u, 144u, 4u, 2u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {7u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {19u, 0u, 0u, 0u}, {7u, 7u, 6u, 6u, 6u, 7u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {19u, 0u, 0u, 0u}, {7u, 7u, 6u, 6u, 6u, 7u, 6u}, 0u, 0u}, {1u, 197u, {7u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 17 draws dropped */
    {0u, 1u, 1u, 148u, 6u, 3u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {6u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {18u, 0u, 0u, 0u}, {8u, 8u, 6u, 6u, 6u, 8u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {18u, 0u, 0u, 0u}, {8u, 8u, 6u, 6u, 6u, 8u, 6u}, 0u, 0u}, {1u, 197u, {6u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 11 draws dropped */
    {0u, 1u, 1u, 154u, 4u, 4u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {5u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {17u, 0u, 0u, 0u}, {9u, 9u, 6u, 6u, 6u, 9u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {17u, 0u, 0u, 0u}, {9u, 9u, 6u, 6u, 6u, 9u, 6u}, 0u, 0u}, {1u, 197u, {5u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 17 draws dropped */
    {0u, 1u, 1u, 158u, 6u, 5u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {4u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {16u, 0u, 0u, 0u}, {10u, 10u, 6u, 6u, 6u, 10u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {16u, 0u, 0u, 0u}, {10u, 10u, 6u, 6u, 6u, 10u, 6u}, 0u, 0u}, {1u, 197u, {4u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 17 draws dropped */
    {0u, 1u, 1u, 164u, 6u, 6u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {3u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {15u, 0u, 0u, 0u}, {11u, 11u, 6u, 6u, 6u, 11u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {15u, 0u, 0u, 0u}, {11u, 11u, 6u, 6u, 6u, 11u, 6u}, 0u, 0u}, {1u, 197u, {3u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 11 draws dropped */
    {0u, 1u, 1u, 170u, 4u, 7u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {2u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {14u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {14u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 197u, {2u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 17 draws dropped */
    {0u, 1u, 1u, 174u, 6u, 8u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {1u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {13u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {13u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 197u, {1u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 13 draws dropped */
    {0u, 1u, 1u, 180u, 6u, 9u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {12u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 202u, {12u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 197u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 10 draws dropped */
    {0u, 1u, 1u, 186u, 9u, 10u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 4u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 4u, 255u, 0u, 0u}}}, {{{1u, 136u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {11u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 194u, {11u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 148u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 20 draws dropped */
    {0u, 1u, 1u, 195u, 9u, 11u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 4u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 4u, 255u, 0u, 0u}}}, {{{1u, 74u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {10u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 186u, {10u, 0u, 0u, 0u}, {12u, 12u, 6u, 6u, 6u, 12u, 6u}, 0u, 0u}, {1u, 99u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 20 draws dropped */
};
/* s2_turn_core_1: Turn core without abilities or items: single-target damage, accuracy, crit and damage rolls, priority (Shadow Sneak), speed order, self-boosts (Swords Dance, Nasty Plot), Protect twice in a row (stall counter), PP use. */
static const df_conf_member conf_s2_turn_core_1_members[2][6] = {
    {{9u, 2u, 0u, {32u, 32u, 0u, 0u, 1u, 1u}, 0u, 0u, 2u, {23u, 7u, 0u, 0u}}, {4u, 1u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 3u, {13u, 14u, 7u, 0u}}, {3u, 2u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {0u, 1u, 0u, {18u, 32u, 2u, 0u, 6u, 8u}, 0u, 0u, 1u, {3u, 0u, 0u, 0u}}},
    {{11u, 1u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 2u, {24u, 7u, 0u, 0u}}, {7u, 3u, 15u, {17u, 0u, 2u, 17u, 16u, 14u}, 0u, 0u, 2u, {19u, 7u, 0u, 0u}}, {3u, 1u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {0u, 2u, 0u, {18u, 32u, 2u, 0u, 6u, 8u}, 0u, 0u, 1u, {3u, 0u, 0u, 0u}}},
};
static const df_conf_step conf_s2_turn_core_1_steps[] = {
    {1u, 1u, 1u, 204u, 0u, 1u, {{0u, 1u, 2u, 3u, 0u, 0u}, {0u, 1u, 2u, 3u, 0u, 0u}}, {{{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}, {{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}}, {{{1u, 182u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 20u, 8u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 197u, {12u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {20u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 2 draws dropped */
    {0u, 1u, 1u, 204u, 0u, 2u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 2u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}, {{1u, 1u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 182u, {11u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 19u, 8u, 0u}, {8u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 197u, {12u, 7u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 179u, {19u, 8u, 0u, 0u}, {6u, 6u, 8u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 1 draws dropped */
    {0u, 1u, 1u, 204u, 1u, 3u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 1u, 255u, 0u, 0u}, {1u, 0u, 3u, 0u, 0u}}, {{1u, 1u, 255u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}}, {{{1u, 182u, {11u, 7u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {19u, 19u, 8u, 0u}, {8u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 197u, {12u, 6u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 179u, {19u, 7u, 0u, 0u}, {6u, 6u, 8u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 3 draws dropped */
    {0u, 1u, 1u, 205u, 10u, 4u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 3u, 0u, 0u}, {1u, 0u, 2u, 0u, 0u}}, {{1u, 0u, 0u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}}, {{{1u, 118u, {10u, 7u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {18u, 19u, 8u, 0u}, {8u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 148u, {11u, 6u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 77u, {19u, 6u, 0u, 0u}, {6u, 6u, 8u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 0 draws dropped */
};
/* s2_turn_core_2: Speed ties between actives (two Rillaboom of equal speed on each side: action order and the per-action Update sort), a spread move with a stat-drop secondary per target (Snarl), Coil, accuracy against an evasion-free target. */
static const df_conf_member conf_s2_turn_core_2_members[2][6] = {
    {{0u, 1u, 0u, {18u, 32u, 2u, 0u, 6u, 8u}, 0u, 0u, 1u, {3u, 0u, 0u, 0u}}, {11u, 2u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 2u, {26u, 7u, 0u, 0u}}, {3u, 2u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {9u, 2u, 0u, {32u, 32u, 0u, 0u, 1u, 1u}, 0u, 0u, 1u, {23u, 0u, 0u, 0u}}},
    {{0u, 2u, 0u, {18u, 32u, 2u, 0u, 6u, 8u}, 0u, 0u, 1u, {3u, 0u, 0u, 0u}}, {3u, 1u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {11u, 1u, 2u, {32u, 0u, 1u, 0u, 24u, 9u}, 0u, 0u, 2u, {26u, 7u, 0u, 0u}}, {9u, 1u, 0u, {32u, 32u, 0u, 0u, 1u, 1u}, 0u, 0u, 1u, {23u, 0u, 0u, 0u}}},
};
static const df_conf_step conf_s2_turn_core_2_steps[] = {
    {1u, 1u, 1u, 215u, 0u, 1u, {{0u, 1u, 2u, 3u, 0u, 0u}, {0u, 1u, 2u, 3u, 0u, 0u}}, {{{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}, {{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}}, {{{1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {16u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {16u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 5 draws dropped */
    {0u, 1u, 1u, 215u, 14u, 2u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 2u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 0u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 160u, {11u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {15u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 137u, {11u, 0u, 0u, 0u}, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {19u, 0u, 0u, 0u}, {7u, 7u, 6u, 6u, 6u, 7u, 6u}, 0u, 0u}, {1u, 197u, {16u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 19 draws dropped */
    {0u, 1u, 1u, 229u, 15u, 3u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 3u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 0u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 126u, {10u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {14u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 113u, {10u, 0u, 0u, 0u}, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {18u, 0u, 0u, 0u}, {8u, 8u, 5u, 6u, 6u, 8u, 6u}, 0u, 0u}, {1u, 197u, {16u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 17 draws dropped */
    {0u, 1u, 1u, 244u, 6u, 4u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 2u, 0u, 0u}, {1u, 1u, 255u, 0u, 0u}}, {{1u, 0u, 1u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 126u, {9u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 197u, {14u, 7u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 79u, {9u, 0u, 0u, 0u}, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 179u, {17u, 0u, 0u, 0u}, {9u, 9u, 5u, 6u, 6u, 9u, 6u}, 0u, 0u}, {1u, 197u, {16u, 8u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 182u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 14 draws dropped */
};
/* s2_typeless_struggle: Struggle is typeless: Farigiraf (Normal) runs out of Protect and Struggles into Gholdengo (Steel/Ghost), which a Normal move could not touch; random targets. */
static const df_conf_member conf_s2_typeless_struggle_members[2][6] = {
    {{12u, 1u, 2u, {29u, 0u, 20u, 0u, 17u, 0u}, 0u, 0u, 1u, {7u, 0u, 0u, 0u}}, {4u, 2u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 1u, {14u, 0u, 0u, 0u}}, {3u, 2u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {0u, 1u, 0u, {18u, 32u, 2u, 0u, 6u, 8u}, 0u, 0u, 1u, {3u, 0u, 0u, 0u}}},
    {{7u, 3u, 15u, {17u, 0u, 2u, 17u, 16u, 14u}, 0u, 0u, 1u, {19u, 0u, 0u, 0u}}, {4u, 1u, 0u, {31u, 7u, 24u, 0u, 3u, 1u}, 0u, 0u, 1u, {14u, 0u, 0u, 0u}}, {3u, 1u, 4u, {32u, 0u, 29u, 0u, 5u, 0u}, 0u, 0u, 1u, {9u, 0u, 0u, 0u}}, {0u, 2u, 0u, {18u, 32u, 2u, 0u, 6u, 8u}, 0u, 0u, 1u, {3u, 0u, 0u, 0u}}},
};
static const df_conf_step conf_s2_typeless_struggle_steps[] = {
    {1u, 1u, 1u, 250u, 0u, 1u, {{0u, 1u, 2u, 3u, 0u, 0u}, {0u, 1u, 2u, 3u, 0u, 0u}}, {{{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}, {{0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u}}}, {{{1u, 224u, {8u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 6 draws dropped */
    {0u, 1u, 1u, 250u, 4u, 2u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 224u, {7u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {19u, 0u, 0u, 0u}, {8u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {19u, 0u, 0u, 0u}, {6u, 6u, 8u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {19u, 0u, 0u, 0u}, {8u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 16 draws dropped */
    {0u, 1u, 1u, 254u, 5u, 3u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 224u, {6u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {18u, 0u, 0u, 0u}, {10u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {18u, 0u, 0u, 0u}, {6u, 6u, 10u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {18u, 0u, 0u, 0u}, {10u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 13 draws dropped */
    {0u, 1u, 1u, 259u, 4u, 4u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 224u, {5u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {17u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {17u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {17u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 16 draws dropped */
    {0u, 1u, 1u, 263u, 5u, 5u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 224u, {4u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {16u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {16u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {16u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 7 draws dropped */
    {0u, 1u, 1u, 268u, 4u, 6u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 224u, {3u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {15u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {15u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {15u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 10 draws dropped */
    {0u, 1u, 1u, 272u, 5u, 7u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 224u, {2u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {14u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {14u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {14u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 7 draws dropped */
    {0u, 1u, 1u, 277u, 4u, 8u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 224u, {1u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 1u, 0u}, {1u, 181u, {13u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {13u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {13u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 10 draws dropped */
    {0u, 1u, 1u, 281u, 5u, 9u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 224u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {12u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 179u, {12u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {12u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 7 draws dropped */
    {0u, 1u, 1u, 286u, 6u, 10u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 4u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 168u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {11u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 160u, {11u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {11u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 15 draws dropped */
    {0u, 1u, 1u, 292u, 6u, 11u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 4u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 112u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {10u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 141u, {10u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {10u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 15 draws dropped */
    {0u, 1u, 1u, 298u, 6u, 12u, {{0u, 0u, 0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u}}, {{{1u, 4u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}, {{1u, 0u, 255u, 0u, 0u}, {1u, 0u, 255u, 0u, 0u}}}, {{{1u, 56u, {0u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 181u, {9u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}, {{1u, 141u, {9u, 0u, 0u, 0u}, {6u, 6u, 12u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 163u, {9u, 0u, 0u, 0u}, {12u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 202u, {20u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {1u, 193u, {12u, 0u, 0u, 0u}, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}, {0u, 0u, {0u, 0u, 0u, 0u}, {0u, 0u, 0u, 0u, 0u, 0u, 0u}, 0u, 0u}}}},  /* 15 draws dropped */
};

/* Every kept draw of every battle: site, lo, hi, value. */
static const dfi_tape_entry conf_tape[] = {
    {2u, 0u, 100u, 86u},
    {3u, 0u, 24u, 4u},
    {4u, 0u, 16u, 11u},
    {5u, 0u, 100u, 72u},
    {2u, 0u, 100u, 90u},
    {3u, 0u, 8u, 0u},
    {4u, 0u, 16u, 4u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {2u, 0u, 100u, 88u},
    {3u, 0u, 24u, 6u},
    {4u, 0u, 16u, 6u},
    {5u, 0u, 100u, 60u},
    {2u, 0u, 100u, 86u},
    {3u, 0u, 24u, 16u},
    {4u, 0u, 16u, 14u},
    {5u, 0u, 100u, 21u},
    {6u, 0u, 3u, 1u},
    {6u, 0u, 3u, 2u},
    {6u, 0u, 3u, 0u},
    {2u, 0u, 100u, 61u},
    {3u, 0u, 24u, 16u},
    {4u, 0u, 16u, 15u},
    {6u, 0u, 3u, 1u},
    {2u, 0u, 100u, 30u},
    {2u, 0u, 100u, 42u},
    {3u, 0u, 24u, 0u},
    {4u, 0u, 16u, 8u},
    {3u, 0u, 24u, 22u},
    {4u, 0u, 16u, 12u},
    {5u, 0u, 100u, 82u},
    {5u, 0u, 100u, 73u},
    {2u, 0u, 100u, 15u},
    {2u, 0u, 100u, 81u},
    {3u, 0u, 24u, 12u},
    {4u, 0u, 16u, 11u},
    {3u, 0u, 24u, 22u},
    {4u, 0u, 16u, 14u},
    {5u, 0u, 100u, 8u},
    {5u, 0u, 100u, 9u},
    {2u, 0u, 100u, 15u},
    {3u, 0u, 24u, 0u},
    {4u, 0u, 16u, 9u},
    {5u, 0u, 100u, 57u},
    {2u, 0u, 100u, 14u},
    {2u, 0u, 100u, 58u},
    {3u, 0u, 24u, 13u},
    {4u, 0u, 16u, 8u},
    {3u, 0u, 24u, 18u},
    {4u, 0u, 16u, 14u},
    {5u, 0u, 100u, 83u},
    {5u, 0u, 100u, 85u},
    {2u, 0u, 100u, 42u},
    {2u, 0u, 100u, 30u},
    {3u, 0u, 24u, 9u},
    {4u, 0u, 16u, 8u},
    {3u, 0u, 24u, 9u},
    {4u, 0u, 16u, 15u},
    {5u, 0u, 100u, 53u},
    {5u, 0u, 100u, 57u},
    {2u, 0u, 100u, 72u},
    {3u, 0u, 24u, 11u},
    {4u, 0u, 16u, 7u},
    {5u, 0u, 100u, 86u},
    {2u, 0u, 100u, 57u},
    {2u, 0u, 100u, 46u},
    {3u, 0u, 24u, 9u},
    {4u, 0u, 16u, 5u},
    {3u, 0u, 24u, 21u},
    {4u, 0u, 16u, 13u},
    {5u, 0u, 100u, 13u},
    {5u, 0u, 100u, 67u},
    {2u, 0u, 100u, 22u},
    {2u, 0u, 100u, 21u},
    {3u, 0u, 24u, 6u},
    {4u, 0u, 16u, 7u},
    {3u, 0u, 24u, 14u},
    {4u, 0u, 16u, 5u},
    {5u, 0u, 100u, 80u},
    {5u, 0u, 100u, 45u},
    {2u, 0u, 100u, 24u},
    {2u, 0u, 100u, 21u},
    {3u, 0u, 24u, 1u},
    {4u, 0u, 16u, 5u},
    {3u, 0u, 24u, 9u},
    {4u, 0u, 16u, 11u},
    {5u, 0u, 100u, 53u},
    {5u, 0u, 100u, 71u},
    {2u, 0u, 100u, 94u},
    {3u, 0u, 24u, 21u},
    {4u, 0u, 16u, 2u},
    {5u, 0u, 100u, 73u},
    {2u, 0u, 100u, 15u},
    {2u, 0u, 100u, 87u},
    {3u, 0u, 24u, 23u},
    {4u, 0u, 16u, 13u},
    {5u, 0u, 100u, 85u},
    {2u, 0u, 100u, 28u},
    {2u, 0u, 100u, 24u},
    {3u, 0u, 24u, 14u},
    {4u, 0u, 16u, 3u},
    {3u, 0u, 24u, 13u},
    {4u, 0u, 16u, 11u},
    {5u, 0u, 100u, 69u},
    {5u, 0u, 100u, 68u},
    {2u, 0u, 100u, 74u},
    {3u, 0u, 24u, 3u},
    {4u, 0u, 16u, 10u},
    {5u, 0u, 100u, 41u},
    {2u, 0u, 100u, 58u},
    {2u, 0u, 100u, 91u},
    {3u, 0u, 24u, 1u},
    {4u, 0u, 16u, 0u},
    {5u, 0u, 100u, 60u},
    {2u, 0u, 100u, 59u},
    {2u, 0u, 100u, 4u},
    {3u, 0u, 24u, 5u},
    {4u, 0u, 16u, 11u},
    {3u, 0u, 24u, 0u},
    {4u, 0u, 16u, 7u},
    {5u, 0u, 100u, 87u},
    {5u, 0u, 100u, 23u},
    {2u, 0u, 100u, 21u},
    {3u, 0u, 24u, 9u},
    {4u, 0u, 16u, 9u},
    {5u, 0u, 100u, 31u},
    {2u, 0u, 100u, 89u},
    {2u, 0u, 100u, 81u},
    {2u, 0u, 100u, 47u},
    {2u, 0u, 100u, 84u},
    {3u, 0u, 24u, 12u},
    {4u, 0u, 16u, 4u},
    {3u, 0u, 24u, 22u},
    {4u, 0u, 16u, 14u},
    {5u, 0u, 100u, 64u},
    {5u, 0u, 100u, 60u},
    {2u, 0u, 100u, 97u},
    {2u, 0u, 100u, 90u},
    {2u, 0u, 100u, 35u},
    {3u, 0u, 24u, 23u},
    {4u, 0u, 16u, 1u},
    {5u, 0u, 100u, 71u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 3u, 2u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 3u, 2u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 3u, 0u},
    {1u, 0u, 2u, 1u},
    {6u, 0u, 3u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {6u, 0u, 9u, 8u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 9u, 8u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {6u, 0u, 3u, 0u},
    {1u, 0u, 2u, 1u},
    {6u, 0u, 3u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {6u, 0u, 9u, 0u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 9u, 4u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {12u, 0u, 2u, 1u},
    {3u, 0u, 24u, 4u},
    {4u, 0u, 16u, 13u},
    {1u, 0u, 2u, 0u},
    {12u, 0u, 2u, 0u},
    {3u, 0u, 24u, 22u},
    {4u, 0u, 16u, 12u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {12u, 0u, 2u, 0u},
    {3u, 0u, 24u, 18u},
    {4u, 0u, 16u, 4u},
    {1u, 0u, 2u, 0u},
    {12u, 0u, 2u, 0u},
    {3u, 0u, 24u, 23u},
    {4u, 0u, 16u, 14u},
    {6u, 0u, 3u, 0u},
    {6u, 0u, 3u, 2u},
    {2u, 0u, 100u, 7u},
    {3u, 0u, 24u, 14u},
    {4u, 0u, 16u, 9u},
    {2u, 0u, 100u, 5u},
    {3u, 0u, 24u, 4u},
    {4u, 0u, 16u, 14u},
    {2u, 0u, 100u, 72u},
    {3u, 0u, 8u, 7u},
    {4u, 0u, 16u, 15u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {2u, 0u, 100u, 24u},
    {2u, 0u, 100u, 96u},
    {3u, 0u, 24u, 18u},
    {4u, 0u, 16u, 9u},
    {5u, 0u, 100u, 77u},
    {1u, 0u, 2u, 0u},
    {2u, 0u, 100u, 32u},
    {3u, 0u, 24u, 17u},
    {4u, 0u, 16u, 10u},
    {2u, 0u, 100u, 27u},
    {3u, 0u, 24u, 9u},
    {4u, 0u, 16u, 14u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {2u, 0u, 100u, 20u},
    {2u, 0u, 100u, 76u},
    {3u, 0u, 24u, 1u},
    {4u, 0u, 16u, 13u},
    {3u, 0u, 24u, 0u},
    {4u, 0u, 16u, 6u},
    {5u, 0u, 100u, 75u},
    {5u, 0u, 100u, 92u},
    {1u, 0u, 2u, 0u},
    {2u, 0u, 100u, 21u},
    {3u, 0u, 24u, 1u},
    {4u, 0u, 16u, 7u},
    {2u, 0u, 100u, 99u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {2u, 0u, 100u, 44u},
    {3u, 0u, 24u, 22u},
    {4u, 0u, 16u, 6u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 3u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 3u, 2u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 3u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {6u, 0u, 3u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {12u, 0u, 2u, 0u},
    {3u, 0u, 24u, 19u},
    {4u, 0u, 16u, 1u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {1u, 0u, 2u, 0u},
    {12u, 0u, 2u, 0u},
    {3u, 0u, 24u, 3u},
    {4u, 0u, 16u, 3u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {1u, 0u, 2u, 1u},
    {12u, 0u, 2u, 1u},
    {3u, 0u, 24u, 3u},
    {4u, 0u, 16u, 3u},
};

static const df_conf_battle conf_battles[] = {
    {"s2_ally_target", 4u, conf_s2_ally_target_members, conf_s2_ally_target_steps, sizeof conf_s2_ally_target_steps / sizeof conf_s2_ally_target_steps[0], 33u},
    {"s2_protect_last", 4u, conf_s2_protect_last_members, conf_s2_protect_last_steps, sizeof conf_s2_protect_last_steps / sizeof conf_s2_protect_last_steps[0], 8u},
    {"s2_stages", 4u, conf_s2_stages_members, conf_s2_stages_steps, sizeof conf_s2_stages_steps / sizeof conf_s2_stages_steps[0], 72u},
    {"s2_struggle", 4u, conf_s2_struggle_members, conf_s2_struggle_steps, sizeof conf_s2_struggle_steps / sizeof conf_s2_struggle_steps[0], 158u},
    {"s2_turn_core_1", 4u, conf_s2_turn_core_1_members, conf_s2_turn_core_1_steps, sizeof conf_s2_turn_core_1_steps / sizeof conf_s2_turn_core_1_steps[0], 6u},
    {"s2_turn_core_2", 4u, conf_s2_turn_core_2_members, conf_s2_turn_core_2_steps, sizeof conf_s2_turn_core_2_steps / sizeof conf_s2_turn_core_2_steps[0], 55u},
    {"s2_typeless_struggle", 4u, conf_s2_typeless_struggle_members, conf_s2_typeless_struggle_steps, sizeof conf_s2_typeless_struggle_steps / sizeof conf_s2_typeless_struggle_steps[0], 137u},
};

#endif
