/* GENERATED by tools/reference/party_expect.py from tests/reference/traces (do not edit). */
/* The side.pokemon order of the pinned Showdown after every step of the recorded battles: roster indices of the
 * brought members, in order (decision 0015 section 7, party_order). */
#ifndef DUOFORGE_TESTS_REFERENCE_PARTY_ORDER_G46_H
#define DUOFORGE_TESTS_REFERENCE_PARTY_ORDER_G46_H
#include <stdint.h>
typedef struct df_party_row {
    uint32_t step;
    uint8_t order[2][4]; /* roster index per side.pokemon position, 0-based */
} df_party_row;
typedef struct df_party_battle {
    const char *name;
    uint32_t row_count;
    const df_party_row *rows;
} df_party_battle;
static const df_party_row party_g41_shadow_tag_trace[] = {
    {0, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {1, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {2, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {3, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {4, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {5, {{0, 1, 2, 3}, {2, 1, 0, 3}}},
    {6, {{0, 1, 2, 3}, {2, 1, 0, 3}}},
    {7, {{0, 1, 2, 3}, {2, 1, 0, 3}}},
    {8, {{0, 1, 2, 3}, {3, 1, 0, 2}}},
    {9, {{0, 2, 1, 3}, {3, 1, 0, 2}}},
    {10, {{0, 1, 2, 3}, {3, 1, 0, 2}}},
    {11, {{0, 2, 1, 3}, {3, 1, 0, 2}}},
    {12, {{0, 1, 2, 3}, {3, 1, 0, 2}}},
    {13, {{0, 2, 1, 3}, {3, 1, 0, 2}}},
};
static const df_party_row party_g41_shadow_tag_fainted[] = {
    {0, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {1, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {2, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {3, {{0, 2, 1, 3}, {0, 1, 2, 3}}},
    {4, {{0, 2, 1, 3}, {0, 1, 2, 3}}},
    {5, {{0, 2, 1, 3}, {0, 1, 2, 3}}},
    {6, {{0, 3, 1, 2}, {0, 1, 2, 3}}},
    {7, {{0, 3, 1, 2}, {0, 1, 2, 3}}},
    {8, {{0, 3, 1, 2}, {0, 2, 1, 3}}},
    {9, {{0, 3, 1, 2}, {3, 2, 1, 0}}},
    {10, {{0, 3, 1, 2}, {0, 2, 1, 3}}},
    {11, {{0, 3, 1, 2}, {3, 2, 1, 0}}},
    {12, {{0, 3, 1, 2}, {0, 2, 1, 3}}},
};
static const df_party_row party_g5_uturn_e[] = {
    {0, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {1, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {2, {{0, 2, 1, 3}, {0, 1, 2, 3}}},
    {3, {{1, 2, 0, 3}, {0, 1, 2, 3}}},
    {4, {{1, 2, 0, 3}, {0, 1, 2, 3}}},
    {5, {{0, 2, 1, 3}, {0, 1, 2, 3}}},
    {6, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {7, {{2, 3, 0, 1}, {0, 1, 2, 3}}},
    {8, {{2, 3, 0, 1}, {0, 1, 2, 3}}},
};
static const df_party_row party_g37_toxic_spikes[] = {
    {0, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {1, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {2, {{0, 1, 2, 3}, {0, 2, 1, 3}}},
    {3, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {4, {{0, 1, 2, 3}, {2, 1, 0, 3}}},
    {5, {{0, 1, 2, 3}, {0, 1, 2, 3}}},
    {6, {{0, 1, 2, 3}, {0, 3, 2, 1}}},
    {7, {{0, 1, 2, 3}, {0, 3, 2, 1}}},
    {8, {{0, 1, 2, 3}, {0, 3, 2, 1}}},
    {9, {{0, 1, 2, 3}, {0, 3, 2, 1}}},
};
static const df_party_battle party_battles[] = {
    {"g41_shadow_tag_trace", sizeof party_g41_shadow_tag_trace / sizeof party_g41_shadow_tag_trace[0], party_g41_shadow_tag_trace},
    {"g41_shadow_tag_fainted", sizeof party_g41_shadow_tag_fainted / sizeof party_g41_shadow_tag_fainted[0], party_g41_shadow_tag_fainted},
    {"g5_uturn_e", sizeof party_g5_uturn_e / sizeof party_g5_uturn_e[0], party_g5_uturn_e},
    {"g37_toxic_spikes", sizeof party_g37_toxic_spikes / sizeof party_g37_toxic_spikes[0], party_g37_toxic_spikes},
};
#endif
