/*
 * Known-answer vector generator for the DuoForge PCG32 contract.
 *
 * Links the PINNED reference imneme/pcg-c-basic at
 * bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3 (pcg_basic.c sha256
 * b6582a071a8a090a293621523c063d125a532d772a2a1eb7d60b3e695fe47746) and
 * prints tests/data/pcg32_kat_vectors.h to stdout. Output is deterministic
 * (no dates). Draw counts per call are measured by re-stepping a copy of the
 * reference state until it matches, independent of DuoForge code.
 * Exits nonzero if any single call needs more than 255 draws.
 *
 * See tools/kat/README.md for the exact regeneration command.
 */
#include <inttypes.h>
#include <stdio.h>

#include "pcg_basic.h"

#define KAT_RAW 16u
#define KAT_CALLS 12u
#define KAT_SHUFFLE_FIRST 52u
#define KAT_SHUFFLE_LAST 2u
#define KAT_SHUFFLE_COUNT (KAT_SHUFFLE_FIRST - KAT_SHUFFLE_LAST + 1u)

static const uint64_t kat_seeds[][2] = {
    {UINT64_C(42), UINT64_C(54)},
    {UINT64_C(0), UINT64_C(0)},
    {UINT64_C(1), UINT64_C(1)},
    {UINT64_MAX, UINT64_MAX},
    {UINT64_C(0x853c49e6748fea9b), UINT64_C(0xda3e39cb94b95bdb)},
    {UINT64_C(0x0123456789abcdef), UINT64_C(0xfedcba9876543210)},
};
#define KAT_SEED_COUNT (sizeof kat_seeds / sizeof kat_seeds[0])

static const uint32_t kat_bounds[] = {
    1u, 2u, 3u, 6u, 7u, 100u, UINT32_C(0x80000000), UINT32_C(0x80000001), UINT32_C(0xFFFFFFFF),
};
#define KAT_BOUND_COUNT (sizeof kat_bounds / sizeof kat_bounds[0])

static int draw_overflow = 0;

static uint32_t draws_between(pcg32_random_t before, pcg32_random_t after)
{
    uint32_t n = 0u;
    while (before.state != after.state || before.inc != after.inc) {
        (void)pcg32_random_r(&before);
        ++n;
        if (n > 255u) {
            draw_overflow = 1;
            return n;
        }
    }
    return n;
}

static uint32_t bounded_counted(pcg32_random_t *rng, uint32_t bound, uint32_t *draws)
{
    const pcg32_random_t before = *rng;
    const uint32_t value = pcg32_boundedrand_r(rng, bound);
    *draws = draws_between(before, *rng);
    return value;
}

int main(void)
{
    printf("/*\n"
           " * GENERATED by tools/kat/gen_pcg32_kat.c against the pinned reference\n"
           " * imneme/pcg-c-basic@bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3\n"
           " * (pcg_basic.c sha256 b6582a071a8a090a293621523c063d125a532d772a2a1eb7d60b3e695fe47746,\n"
           " *  pcg_basic.h sha256 cd823ddc225da9be520a54f13ef2c491506c353800cae04e8b673b2de58f2cc4).\n"
           " * DO NOT EDIT. Regenerate with the command in tools/kat/README.md.\n"
           " */\n"
           "#ifndef DUOFORGE_TESTS_DATA_PCG32_KAT_VECTORS_H\n"
           "#define DUOFORGE_TESTS_DATA_PCG32_KAT_VECTORS_H\n\n"
           "#include <stdint.h>\n\n");
    printf("#define DF_KAT_SEED_COUNT %uu\n", (unsigned)KAT_SEED_COUNT);
    printf("#define DF_KAT_RAW_COUNT %uu\n", (unsigned)KAT_RAW);
    printf("#define DF_KAT_BOUND_COUNT %uu\n", (unsigned)KAT_BOUND_COUNT);
    printf("#define DF_KAT_CALLS %uu\n", (unsigned)KAT_CALLS);
    printf("#define DF_KAT_SHUFFLE_FIRST %uu\n", (unsigned)KAT_SHUFFLE_FIRST);
    printf("#define DF_KAT_SHUFFLE_COUNT %uu\n\n", (unsigned)KAT_SHUFFLE_COUNT);
    printf("typedef struct df_kat_bounded {\n"
           "    uint32_t bound;\n"
           "    uint32_t value[DF_KAT_CALLS];\n"
           "    uint32_t draws[DF_KAT_CALLS];\n"
           "} df_kat_bounded;\n\n"
           "typedef struct df_kat_seed {\n"
           "    uint64_t initstate;\n"
           "    uint64_t initseq;\n"
           "    uint64_t state; /* after seeding */\n"
           "    uint64_t inc;\n"
           "    uint32_t raw[DF_KAT_RAW_COUNT];\n"
           "    uint64_t state_after_raw;\n"
           "    df_kat_bounded bounded[DF_KAT_BOUND_COUNT]; /* each from a fresh seed */\n"
           "    uint32_t shuffle_value[DF_KAT_SHUFFLE_COUNT]; /* bounded(52), bounded(51), ... bounded(2) from a fresh seed */\n"
           "    uint32_t shuffle_draws[DF_KAT_SHUFFLE_COUNT];\n"
           "} df_kat_seed;\n\n"
           "static const df_kat_seed df_kat_seeds[DF_KAT_SEED_COUNT] = {\n");

    for (size_t s = 0; s < KAT_SEED_COUNT; ++s) {
        pcg32_random_t rng;
        pcg32_srandom_r(&rng, kat_seeds[s][0], kat_seeds[s][1]);
        printf("    {\n        UINT64_C(0x%016" PRIx64 "), UINT64_C(0x%016" PRIx64 "),\n",
               kat_seeds[s][0], kat_seeds[s][1]);
        printf("        UINT64_C(0x%016" PRIx64 "), UINT64_C(0x%016" PRIx64 "),\n", rng.state, rng.inc);
        printf("        {");
        for (uint32_t i = 0; i < KAT_RAW; ++i) {
            printf("%sUINT32_C(0x%08" PRIx32 ")", i == 0 ? "" : ", ", pcg32_random_r(&rng));
        }
        printf("},\n        UINT64_C(0x%016" PRIx64 "),\n        {\n", rng.state);
        for (size_t b = 0; b < KAT_BOUND_COUNT; ++b) {
            pcg32_random_t r2;
            uint32_t values[KAT_CALLS];
            uint32_t draws[KAT_CALLS];
            pcg32_srandom_r(&r2, kat_seeds[s][0], kat_seeds[s][1]);
            for (uint32_t i = 0; i < KAT_CALLS; ++i) {
                values[i] = bounded_counted(&r2, kat_bounds[b], &draws[i]);
            }
            printf("            {UINT32_C(0x%08" PRIx32 "), {", kat_bounds[b]);
            for (uint32_t i = 0; i < KAT_CALLS; ++i) {
                printf("%s%" PRIu32 "u", i == 0 ? "" : ", ", values[i]);
            }
            printf("}, {");
            for (uint32_t i = 0; i < KAT_CALLS; ++i) {
                printf("%s%" PRIu32 "u", i == 0 ? "" : ", ", draws[i]);
            }
            printf("}},\n");
        }
        printf("        },\n        {");
        pcg32_random_t r3;
        uint32_t sdraws[KAT_SHUFFLE_COUNT];
        pcg32_srandom_r(&r3, kat_seeds[s][0], kat_seeds[s][1]);
        for (uint32_t i = 0; i < KAT_SHUFFLE_COUNT; ++i) {
            const uint32_t v = bounded_counted(&r3, KAT_SHUFFLE_FIRST - i, &sdraws[i]);
            printf("%s%" PRIu32 "u", i == 0 ? "" : ", ", v);
        }
        printf("},\n        {");
        for (uint32_t i = 0; i < KAT_SHUFFLE_COUNT; ++i) {
            printf("%s%" PRIu32 "u", i == 0 ? "" : ", ", sdraws[i]);
        }
        printf("},\n    },\n");
    }
    printf("};\n\n#endif\n");

    if (draw_overflow) {
        fprintf(stderr, "gen_pcg32_kat: a call needed more than 255 draws\n");
        return 1;
    }
    return 0;
}
