/*
 * duoforge.unit.modifier (white-box): the damage and stat arithmetic of
 * src/core/modifier.c against values computed by the pinned reference
 * (tests/reference/arith_ref.h, generated by tools/reference/arith_ref.js),
 * and the draw sites of src/rng/draw.c: PCG draws in bounds, the test-only
 * tape (match, mismatch, exhaustion, never a fallback) and the draw log.
 */
#include <stdio.h>
#include <string.h>

#include "core/modifier.h"
#include "reference/arith_ref.h"
#include "rng/draw.h"
#include "support/check.h"

#define COUNT(a) (sizeof(a) / sizeof((a)[0]))

static void check_arith(df_test *t)
{
    unsigned bad = 0;
    for (size_t i = 0; i < COUNT(ref_modify); ++i) {
        uint32_t mod = 0;
        const bool ok = dfi_mod_fraction(ref_modify[i][1], ref_modify[i][2], &mod);
        const uint32_t got = ok ? dfi_modify(ref_modify[i][0], mod) : 0xFFFFFFFFu;
        if (!ok || got != ref_modify[i][3]) {
            ++bad;
            fprintf(stderr, "  modify(%u, %u/%u) = %u, reference %u\n", ref_modify[i][0], ref_modify[i][1],
                    ref_modify[i][2], got, ref_modify[i][3]);
        }
    }
    for (size_t i = 0; i < COUNT(ref_chain); ++i) {
        uint32_t acc = DFI_MOD_ONE;
        bool ok = true;
        for (size_t k = 0; k < 4 && ref_chain[i][2 * k + 1] != 0u; ++k) {
            uint32_t next = 0;
            ok = ok && dfi_mod_fraction(ref_chain[i][2 * k], ref_chain[i][2 * k + 1], &next) &&
                 dfi_chain_modify(acc, next, &acc);
        }
        if (!ok || acc != ref_chain[i][8]) {
            ++bad;
            fprintf(stderr, "  chain %zu = %u, reference %u\n", i, acc, ref_chain[i][8]);
        }
    }
    for (size_t i = 0; i < COUNT(ref_base_damage); ++i) {
        const uint32_t *r = ref_base_damage[i];
        uint32_t got = 0;
        if (!dfi_base_damage(r[0], r[1], r[2], r[3], &got) || got != r[4]) {
            ++bad;
            fprintf(stderr, "  base damage L%u P%u A%u D%u = %u, reference %u\n", r[0], r[1], r[2], r[3], got, r[4]);
        }
    }
    for (size_t i = 0; i < COUNT(ref_randomize); ++i) {
        uint32_t got = 0;
        if (!dfi_randomize(ref_randomize[i][0], ref_randomize[i][1], &got) || got != ref_randomize[i][2]) {
            ++bad;
            fprintf(stderr, "  randomize(%u, %u) = %u, reference %u\n", ref_randomize[i][0], ref_randomize[i][1],
                    got, ref_randomize[i][2]);
        }
    }
    for (size_t i = 0; i < COUNT(ref_damage_steps); ++i) {
        const uint32_t *r = ref_damage_steps[i];
        bad += dfi_crit_damage(r[0]) != r[1] ? 1u : 0u;
        for (uint32_t k = 0; k < 5; ++k) {
            uint32_t got = 0;
            const bool ok = dfi_type_damage(r[0], DFI_BIAS6 - 2u + k, &got);
            if (!ok || got != r[2 + k]) {
                ++bad;
                fprintf(stderr, "  type step %u on %u = %u, reference %u\n", k, r[0], got, r[2 + k]);
            }
        }
        if (dfi_final_damage(r[0]) != r[7]) {
            ++bad;
            fprintf(stderr, "  final(%u) = %u, reference %u\n", r[0], dfi_final_damage(r[0]), r[7]);
        }
    }
    for (size_t i = 0; i < COUNT(ref_stage_stat); ++i) {
        uint32_t got = 0;
        if (!dfi_stage_stat(ref_stage_stat[i][0], ref_stage_stat[i][1], &got) || got != ref_stage_stat[i][2]) {
            ++bad;
            fprintf(stderr, "  stage stat %u at %u = %u, reference %u\n", ref_stage_stat[i][0],
                    ref_stage_stat[i][1], got, ref_stage_stat[i][2]);
        }
    }
    for (size_t i = 0; i < COUNT(ref_stage_accuracy); ++i) {
        uint32_t got = 0;
        if (!dfi_stage_accuracy(ref_stage_accuracy[i][0], ref_stage_accuracy[i][1], &got) ||
            got != ref_stage_accuracy[i][2]) {
            ++bad;
            fprintf(stderr, "  accuracy %u at %u = %u, reference %u\n", ref_stage_accuracy[i][0],
                    ref_stage_accuracy[i][1], got, ref_stage_accuracy[i][2]);
        }
    }
    DF_CHECK_EQ_U64(t, bad, 0u);
    /* The table sizes, so a shortened header cannot pass silently. */
    DF_CHECK_EQ_U64(t, COUNT(ref_modify), 208u);
    DF_CHECK_EQ_U64(t, COUNT(ref_chain), 10u);
    DF_CHECK_EQ_U64(t, COUNT(ref_base_damage), 288u);
    DF_CHECK_EQ_U64(t, COUNT(ref_randomize), 36u);
    DF_CHECK_EQ_U64(t, COUNT(ref_damage_steps), 12u);
    DF_CHECK_EQ_U64(t, COUNT(ref_stage_stat), 117u);
    DF_CHECK_EQ_U64(t, COUNT(ref_stage_accuracy), 130u);

    /* Rejections instead of divergence. */
    uint32_t x = 7u;
    DF_CHECK(t, !dfi_mod_fraction(1u, 0u, &x) && x == 7u);
    DF_CHECK(t, !dfi_base_damage(50u, 90u, 100u, 0u, &x) && x == 7u);
    DF_CHECK(t, !dfi_randomize(100u, 16u, &x) && x == 7u);
    DF_CHECK(t, !dfi_type_damage(100u, 13u, &x) && x == 7u);
    DF_CHECK(t, !dfi_stage_stat(100u, 13u, &x) && x == 7u);
    DF_CHECK(t, !dfi_stage_accuracy(100u, 13u, &x) && x == 7u);
    DF_CHECK(t, !dfi_chain_modify(65536u, 32768u, &x) && x == 7u); /* 2^31: the signed shift would flip */
    DF_CHECK(t, dfi_chain_modify(32768u, 65535u, &x) && x == 524280u);
}

static void check_draws(df_test *t)
{
    /* PCG: every value in [lo, hi); draws are counted; the log keeps sites. */
    dfi_rng rng;
    dfi_rng_seed(&rng, 42u, 54u);
    uint8_t log[8];
    memset(log, 0xEE, sizeof log);
    dfi_draws d = dfi_draws_from_rng(&rng);
    d.log = log;
    d.log_cap = 4u;
    unsigned out_of_range = 0;
    for (uint32_t i = 0; i < 6u; ++i) {
        uint32_t v = 0;
        DF_CHECK(t, dfi_draw(&d, DFI_SITE_CONFUSION_TURNS, 2u, 6u, &v) == DUOFORGE_OK);
        out_of_range += (v < 2u || v >= 6u) ? 1u : 0u;
    }
    DF_CHECK_EQ_U64(t, out_of_range, 0u);
    DF_CHECK(t, d.log_len == 6u && log[0] == DFI_SITE_CONFUSION_TURNS && log[3] == DFI_SITE_CONFUSION_TURNS &&
                    log[4] == 0xEEu);
    DF_CHECK(t, rng.draws >= 6u);
    /* Bad arguments: E_INVARIANT, nothing drawn. */
    {
        const dfi_rng before = rng;
        uint32_t v = 99u;
        DF_CHECK(t, dfi_draw(&d, 0u, 0u, 2u, &v) == DUOFORGE_E_INVARIANT);
        DF_CHECK(t, dfi_draw(&d, DFI_SITE_COUNT, 0u, 2u, &v) == DUOFORGE_E_INVARIANT);
        DF_CHECK(t, dfi_draw(&d, DFI_SITE_CRIT, 5u, 5u, &v) == DUOFORGE_E_INVARIANT);
        DF_CHECK(t, v == 99u && rng.state == before.state && rng.draws == before.draws && d.log_len == 6u);
    }
    /* randomChance(1, 1) is always true, (0, n) never (a draw still happens). */
    {
        bool hit = false;
        DF_CHECK(t, dfi_draw_chance(&d, DFI_SITE_SECONDARY, 100u, 100u, &hit) == DUOFORGE_OK && hit);
        DF_CHECK(t, dfi_draw_chance(&d, DFI_SITE_SECONDARY, 0u, 100u, &hit) == DUOFORGE_OK && !hit);
        DF_CHECK_EQ_U64(t, d.log_len, 8u);
    }

    /* Tape: outcomes come from the tape, the generator is untouched. */
    static const dfi_tape_entry tape[] = {
        {DFI_SITE_ACCURACY, 0u, 100u, 84u},
        {DFI_SITE_CRIT, 0u, 24u, 0u},
        {DFI_SITE_DAMAGE_ROLL, 0u, 16u, 15u},
    };
    dfi_rng untouched;
    dfi_rng_seed(&untouched, 1u, 2u);
    const dfi_rng snapshot = untouched;
    dfi_draws tp = dfi_draws_from_rng(&untouched);
    tp.tape = tape;
    tp.tape_len = 3u;
    bool hit = false;
    DF_CHECK(t, dfi_draw_chance(&tp, DFI_SITE_ACCURACY, 85u, 100u, &hit) == DUOFORGE_OK && hit); /* 84 < 85 */
    uint32_t v = 0;
    DF_CHECK(t, dfi_draw(&tp, DFI_SITE_CRIT, 0u, 24u, &v) == DUOFORGE_OK && v == 0u);
    DF_CHECK(t, dfi_draw(&tp, DFI_SITE_DAMAGE_ROLL, 0u, 16u, &v) == DUOFORGE_OK && v == 15u);
    DF_CHECK(t, !tp.failed && tp.tape_pos == 3u);
    DF_CHECK(t, untouched.state == snapshot.state && untouched.draws == 0u);
    /* Exhausted: fails, no fallback to the generator. */
    v = 77u;
    DF_CHECK(t, dfi_draw(&tp, DFI_SITE_DAMAGE_ROLL, 0u, 16u, &v) == DUOFORGE_E_INVARIANT);
    DF_CHECK(t, tp.failed && v == 77u && untouched.draws == 0u);
    /* A different site or bound than the tape: fails. */
    static const dfi_tape_entry wrong[] = {
        {DFI_SITE_CRIT, 0u, 24u, 3u},
        {DFI_SITE_CRIT, 0u, 8u, 9u}, /* value outside its own bound */
    };
    dfi_draws w = dfi_draws_from_rng(&untouched);
    w.tape = wrong;
    w.tape_len = 2u;
    DF_CHECK(t, dfi_draw(&w, DFI_SITE_CRIT, 0u, 8u, &v) == DUOFORGE_E_INVARIANT && w.failed && w.tape_pos == 0u);
    w.failed = false;
    DF_CHECK(t, dfi_draw(&w, DFI_SITE_ACCURACY, 0u, 24u, &v) == DUOFORGE_E_INVARIANT && w.failed);
    w.failed = false;
    w.tape_pos = 1u;
    DF_CHECK(t, dfi_draw(&w, DFI_SITE_CRIT, 0u, 8u, &v) == DUOFORGE_E_INVARIANT && w.failed);
}

int main(void)
{
    df_test t;
    df_test_begin(&t, "duoforge.unit.modifier");
    check_arith(&t);
    check_draws(&t);
    return df_test_end(&t);
}
