/*
 * duoforge.reference.tiebreak (white-box): duoforge_battle_tiebreak against
 * Battle.tiebreak() of the pinned Showdown at every stop of the committed
 * battles. tests/reference/tiebreak_ref.h (generated by
 * tools/reference/tiebreak_ref.js) holds, for several prefixes of each battle
 * (tests/reference/specs), what the pin's tiebreak() decided on a fresh replay
 * of that prefix and the quantities it compared: the Pokemon not fainted, the
 * total HP and the HP percentage as the bits of its double.
 *
 * Here the same battles are replayed through the engine, with the reference's
 * draws as a tape as in duoforge.reference.conformance (test_conformance.c;
 * the data selection and the contexts are the same), and at each stop the
 * engine must give the same winner, the same counts and totals, and the very
 * bits of the reference's HP percentage among the values its bench orders can
 * give (the engine does not keep the reference's side.pokemon order, see
 * src/state/tiebreak.c). No stop of the committed battles may depend on that
 * order. A battle that had ended at its stop gives its own result.
 *
 * The same builds as test_conformance.c: DF_CONFORMANCE_TEAM_C,
 * DF_CONFORMANCE_POOL, DF_CONFORMANCE_POOL_DATA.
 */
#include <stdio.h>
#include <string.h>

#if defined(DF_CONFORMANCE_POOL_DATA)
#include "data/pool_tables.h"
#include "reference/conformance_pool.h"
#include "support/pool.h"
#elif defined(DF_CONFORMANCE_TEAM_C)
#include "data/extended_tables.h"
#include "reference/conformance_team_c.h"
#include "support/team_c.h"
#else
#include "data/closure_tables.h"
#include "reference/conformance.h"
#endif
#ifdef DF_CONFORMANCE_POOL
#include "data/pool_tables.h"
#include "support/pool.h"
#endif
#include "reference/tiebreak_ref.h"
#include "state/battle_internal.h"
#include "state/request.h"
#include "state/tiebreak.h"
#include "support/check.h"
#include "support/fixtures.h"

typedef struct tb_counts {
    unsigned stops, ended, ambiguous;
    unsigned by_stage[5]; /* the pin's deciding stage: 1 count, 2 percentage, 3 total, 4 tie */
} tb_counts;

static void build_setup(const df_conf_battle *cb, duoforge_battle_setup *s)
{
    memset(s, 0, sizeof *s);
    s->rng_initstate = 1u;
    s->rng_initseq = 2u;
    for (uint32_t side = 0; side < 2u; ++side) {
        s->sides[side].member_count = cb->member_count;
        for (uint32_t m = 0; m < cb->member_count; ++m) {
            const df_conf_member *src = &cb->members[side][m];
            duoforge_member_setup *dst = &s->sides[side].members[m];
            dst->species_id = src->species;
            dst->gender = src->gender;
            dst->nature = src->nature;
            for (uint32_t i = 0; i < 6u; ++i) {
                dst->stat_points[i] = src->sp[i];
            }
            dst->ability = src->ability;
            dst->item = src->item;
            dst->move_count = src->move_count;
            for (uint32_t k = 0; k < src->move_count; ++k) {
                dst->moves[k].move_id = src->moves[k];
            }
        }
    }
}

static bool has_bits(const dfi_tiebreak_report *r, uint32_t side, uint64_t bits)
{
    for (uint32_t i = 0; i < r->pct_count[side]; ++i) {
        if (r->pct_bits[side][i] == bits) {
            return true;
        }
    }
    return false;
}

/* The engine at one stop against the reference's. Returns the number of
 * differences found. */
static unsigned check_stop(df_test *t, const duoforge_context *ctx, const struct duoforge_battle *b,
                           const df_tb_stop *st, const char *name, tb_counts *counts)
{
    unsigned bad = 0;
    struct duoforge_battle before;
    memcpy(&before, b, sizeof before);
    dfi_tiebreak_report r;
    uint32_t out = 0xDEADBEEFu;
    const duoforge_status rs = dfi_battle_tiebreak_report(ctx, b, &r);
    const duoforge_status ps = duoforge_battle_tiebreak(ctx, b, &out);
    counts->stops += 1u;
    if (!DF_CHECK(t, rs == DUOFORGE_OK)) {
        fprintf(stderr, "  %s @%u: report %s\n", name, (unsigned)st->prefix, duoforge_status_name(rs));
        return 1u;
    }
    /* A pure query. */
    if (!DF_CHECK(t, memcmp(&before, b, sizeof before) == 0)) {
        fprintf(stderr, "  %s @%u: the battle changed\n", name, (unsigned)st->prefix);
        bad += 1u;
    }
    if (st->ended != 0u) {
        counts->ended += 1u;
        if (!DF_CHECK(t, b->boundary_kind == DUOFORGE_BOUNDARY_TERMINAL && ps == DUOFORGE_OK && out == st->result &&
                             r.result == st->result)) {
            fprintf(stderr, "  %s @%u: ended, the reference says %u, the engine %u (status %s)\n", name,
                    (unsigned)st->prefix, (unsigned)st->result, (unsigned)out, duoforge_status_name(ps));
            bad += 1u;
        }
        return bad;
    }
    counts->by_stage[st->stage] += 1u;
    bool ok = b->boundary_kind != DUOFORGE_BOUNDARY_TERMINAL;
    for (uint32_t s = 0; s < 2u; ++s) {
        ok = ok && r.not_fainted[s] == st->not_fainted[s] && r.hp_total[s] == st->hp_total[s] &&
             has_bits(&r, s, st->pct_bits[s]);
    }
    /* The reference's winner is one of the engine's possible results, the
     * only one when the order of a bench does not matter. */
    ok = ok && (r.result_mask & (1u << st->result)) != 0u;
    if (r.result == 0u) {
        counts->ambiguous += 1u;
        ok = ok && ps == DUOFORGE_E_UNSUPPORTED && out == 0xDEADBEEFu;
    } else {
        ok = ok && r.result == st->result && ps == DUOFORGE_OK && out == st->result;
    }
    if (!DF_CHECK(t, ok)) {
        fprintf(stderr,
                "  %s @%u: the reference %u (left %u/%u, total %u/%u, stage %u), the engine %u (mask %u, left "
                "%u/%u, total %u/%u, status %s)\n",
                name, (unsigned)st->prefix, (unsigned)st->result, (unsigned)st->not_fainted[0],
                (unsigned)st->not_fainted[1], (unsigned)st->hp_total[0], (unsigned)st->hp_total[1],
                (unsigned)st->stage, (unsigned)r.result, (unsigned)r.result_mask, (unsigned)r.not_fainted[0],
                (unsigned)r.not_fainted[1], (unsigned)r.hp_total[0], (unsigned)r.hp_total[1],
                duoforge_status_name(ps));
        bad += 1u;
    }
    return bad;
}

int main(void)
{
    df_test t;
#if defined(DF_CONFORMANCE_POOL_DATA)
    df_test_begin(&t, "duoforge.reference.tiebreak_pool_data");
#elif defined(DF_CONFORMANCE_POOL) && defined(DF_CONFORMANCE_TEAM_C)
    df_test_begin(&t, "duoforge.reference.tiebreak_team_c_pool");
#elif defined(DF_CONFORMANCE_POOL)
    df_test_begin(&t, "duoforge.reference.tiebreak_pool");
#elif defined(DF_CONFORMANCE_TEAM_C)
    df_test_begin(&t, "duoforge.reference.tiebreak_team_c");
#else
    df_test_begin(&t, "duoforge.reference.tiebreak");
#endif
#if defined(DF_CONFORMANCE_POOL) || defined(DF_CONFORMANCE_POOL_DATA)
    duoforge_context *k1 = df_make_context(&df_config_pool);
    duoforge_context *k2 = df_make_context(&df_config_pool_dev);
#elif defined(DF_CONFORMANCE_TEAM_C)
    duoforge_context *k1 = df_make_context(&df_config_team_c);
    duoforge_context *k2 = df_make_context(&df_config_team_c_dev);
#else
    duoforge_context *k1 = df_make_context(&df_config_k1);
    duoforge_context *k2 = df_make_context(&df_config_k2);
#endif
    tb_counts counts;
    memset(&counts, 0, sizeof counts);
    unsigned battles = 0;
    for (size_t bi = 0; bi < sizeof conf_battles / sizeof conf_battles[0]; ++bi) {
        const df_conf_battle *cb = &conf_battles[bi];
        const df_tb_battle *tb = NULL;
        for (size_t i = 0; i < sizeof tb_battles / sizeof tb_battles[0]; ++i) {
            if (strcmp(tb_battles[i].name, cb->name) == 0) {
                tb = &tb_battles[i];
            }
        }
        if (!DF_CHECK(&t, tb != NULL && tb->choice_entries == cb->step_count)) {
            fprintf(stderr, "  %s: no reference tiebreak values for exactly these steps\n", cb->name);
            continue;
        }
        duoforge_battle_setup setup;
        build_setup(cb, &setup);
        duoforge_battle *b = NULL;
        const duoforge_context *ctx = k1;
        duoforge_status created = duoforge_battle_create(k1, &setup, &b);
        if (created != DUOFORGE_OK) {
            ctx = k2;
            created = duoforge_battle_create(k2, &setup, &b);
        }
        if (!DF_CHECK(&t, created == DUOFORGE_OK && b != NULL)) {
            fprintf(stderr, "  %s: the setup is rejected: %s\n", cb->name, duoforge_status_name(created));
            continue;
        }
        battles += 1u;
        unsigned bad = 0;
        uint32_t stop = 0u;
        /* The stops with `done` choice entries made: before the first step, and after each. */
        for (uint32_t done = 0; done <= cb->step_count && bad == 0u; ++done) {
            if (done > 0u) {
                const df_conf_step *st = &cb->steps[done - 1u];
                duoforge_decision_bundle bd;
                memset(&bd, 0, sizeof bd);
                bd.epoch = b->request_epoch;
                bd.response_mask = (uint8_t)(st->answered0 | (st->answered1 << 1u)); /* wide-operands-reviewed */
                for (uint32_t s = 0; s < 2u; ++s) {
                    if ((s == 0u && !st->answered0) || (s == 1u && !st->answered1)) {
                        continue;
                    }
                    duoforge_side_choice *r = &bd.responses[s];
                    r->epoch = b->request_epoch;
                    r->side = (uint8_t)s;
                    if (st->team) {
                        r->kind = (uint8_t)DUOFORGE_CHOICE_TEAM_SELECTION;
                        r->pick_count = 4u;
                        for (uint32_t i = 0; i < 4u; ++i) {
                            r->picks[i] = st->picks[s][i];
                        }
                    } else {
                        r->kind = (uint8_t)DUOFORGE_CHOICE_SLOTS;
                        for (uint32_t k = 0; k < 2u; ++k) {
                            const df_conf_cmd *c = &st->cmds[s][k];
                            r->slots[k] = (duoforge_slot_command){c->kind, c->move_slot, c->target, c->mega,
                                                                  c->reserve, {0u, 0u, 0u}};
                        }
                    }
                }
                duoforge_step_result res;
                uint32_t used = 0xFFFFFFFFu;
                const duoforge_status status =
                    dfi_battle_step_tape(ctx, b, &bd, &conf_tape[st->tape_off], st->tape_len, &used, &res);
                if (!DF_CHECK(&t, status == DUOFORGE_OK && used == st->tape_len)) {
                    fprintf(stderr, "  %s step %u: %s, tape %u of %u\n", cb->name, (unsigned)(done - 1u),
                            duoforge_status_name(status), (unsigned)used, (unsigned)st->tape_len);
                    ++bad;
                    break;
                }
            }
            while (stop < tb->stop_count && tb->stops[stop].prefix == done) {
                bad += check_stop(&t, ctx, b, &tb->stops[stop], cb->name, &counts);
                stop += 1u;
            }
        }
        DF_CHECK_EQ_U64(&t, stop, tb->stop_count); /* every recorded stop was reached */
        DF_CHECK_EQ_U64(&t, bad, 0u);
        duoforge_battle_destroy(b);
    }
    fprintf(stderr, "  %u battles, %u stops (%u of an ended battle); the pin decided %u by the count, %u by the HP "
                    "percentage, %u by the total, %u ties; %u stops depend on a bench order\n",
            battles, counts.stops, counts.ended, counts.by_stage[1], counts.by_stage[2], counts.by_stage[3],
            counts.by_stage[4], counts.ambiguous);
    /* No committed stop depends on the order of a bench. */
    DF_CHECK_EQ_U64(&t, counts.ambiguous, 0u);
#if defined(DF_CONFORMANCE_POOL_DATA)
    DF_CHECK_EQ_U64(&t, battles, 187u);
    DF_CHECK_EQ_U64(&t, counts.stops, 1006u);
#else
    /* Every kind of decision of the pin is among the stops (the pool battles are too few for that). */
    DF_CHECK(&t, counts.by_stage[1] > 0u && counts.by_stage[2] > 0u && counts.by_stage[3] > 0u &&
                     counts.by_stage[4] > 0u);
#if defined(DF_CONFORMANCE_TEAM_C)
    DF_CHECK_EQ_U64(&t, battles, 73u);
    DF_CHECK_EQ_U64(&t, counts.stops, 734u);
#else
    DF_CHECK_EQ_U64(&t, battles, 90u);
    DF_CHECK_EQ_U64(&t, counts.stops, 833u);
#endif
#endif
    duoforge_context_destroy(k1);
    duoforge_context_destroy(k2);
    return df_test_end(&t);
}
