"""Generate the canonical state encoding's offsets from C: python gen_state_layout.py <state_layout_dump>."""
import json
from pathlib import Path
import pprint
import subprocess
import sys


def generate(tool):
    offsets = json.loads(subprocess.run([tool], check=True, capture_output=True, text=True).stdout)
    return ('"""Generated by tools/layout/gen_state_layout.py from src/codec/state_codec.h; do not edit."""\n'
            + "OFFSETS = " + pprint.pformat(offsets, sort_dicts=False) + "\n")


if __name__ == "__main__":
    target = Path(__file__).resolve().parents[2] / "python/duoforge/_state_layout.py"
    target.write_text(generate(sys.argv[1]), encoding="utf-8", newline="\n")
