"""Generate record offsets from C: python gen_view_layout.py <layout_dump>."""
import json
from pathlib import Path
import pprint
import subprocess
import sys


def generate(tool):
    dump = json.loads(subprocess.run([tool], check=True, capture_output=True, text=True).stdout)
    structs = {k: dump["structs"][k] for k in ("duoforge_public_state", "duoforge_hypothesis")}
    constants = {k: v for k, v in dump["constants"].items()
                 if k.startswith(("DUOFORGE_VIEW_", "DUOFORGE_HYPOTHESIS_"))}
    return ('"""Generated by tools/layout/gen_view_layout.py; do not edit offsets."""\n'
            + "STRUCTS = " + pprint.pformat(structs, sort_dicts=False) + "\n"
            + "CONSTANTS = " + pprint.pformat(constants, sort_dicts=False) + "\n")


if __name__ == "__main__":
    target = Path(__file__).resolve().parents[2] / "python/duoforge/_view_layout.py"
    target.write_text(generate(sys.argv[1]), encoding="utf-8", newline="\n")
