#!/usr/bin/env node
// Reference values of the damage and stat arithmetic, computed by the pinned
// Pokemon Showdown itself (decision 0006 sections 4 and 7).
//
// usage: node tools/reference/arith_ref.js <pinned checkout> [--check <file>]
//
// Without --check it prints tests/reference/arith_ref.h to stdout. With
// --check it compares the output to the given file byte for byte and exits
// non-zero on a difference. CTest never needs Node: the header is committed,
// and this check runs only when DUOFORGE_PS_REFERENCE_DIR is set.
//
// Where the reference exposes a function, the script calls it: Battle.modify,
// chainModify (through battle.event), Battle.randomizer (with a fixed roll),
// Dex.trunc and Pokemon.calculateStat. Where the reference computes inline,
// the expression is evaluated with the reference's own trunc and cited:
// the base damage (sim/battle-actions.ts:1718), the critical hit, type and
// final steps of modifyDamage (data/mods/champions/scripts.ts:196-312) and
// the accuracy stages (sim/battle-actions.ts:722-727).
'use strict';

const path = require('path');
const fs = require('fs');

const PIN = 'b2cb775b0616115b775534eaeff50300e1fc81fc';
const HARNESS_VERSION = 1;

function main() {
    const args = process.argv.slice(2);
    if (args.length !== 1 && !(args.length === 3 && args[1] === '--check')) {
        process.stderr.write('usage: arith_ref.js <pinned checkout> [--check <file>]\n');
        process.exit(2);
    }
    const root = path.resolve(args[0]);
    const {Battle} = require(path.join(root, 'dist', 'sim', 'battle'));
    const {Teams} = require(path.join(root, 'dist', 'sim', 'teams'));
    const battle = new Battle({formatid: 'gen9championsvgc2026regmc'});
    const tr = battle.trunc;
    const out = [];
    const line = (s) => out.push(s);

    line('/*');
    line(' * GENERATED by tools/reference/arith_ref.js (harness version ' + HARNESS_VERSION + ') from Pokemon');
    line(' * Showdown at ' + PIN + ',');
    line(' * format gen9championsvgc2026regmc. Do not edit by hand.');
    line(' */');
    line('#ifndef DUOFORGE_TESTS_REFERENCE_ARITH_REF_H');
    line('#define DUOFORGE_TESTS_REFERENCE_ARITH_REF_H');
    line('#include <stdint.h>');
    line('');

    // modify(value, [numerator, denominator])
    const values = [0, 1, 2, 3, 7, 50, 99, 100, 101, 255, 1000, 4095, 4096, 4097, 65535, 123456];
    const fractions = [[1, 4], [1, 2], [3, 4], [1, 1], [6, 5], [13, 10], [3, 2], [2, 1], [4915, 4096],
        [5324, 4096], [2, 3], [5, 4], [8, 1]];
    line('/* value, numerator, denominator, Battle.modify(value, [numerator, denominator]) */');
    line('static const uint32_t ref_modify[][4] = {');
    for (const v of values) {
        for (const [n, d] of fractions) {
            line(`    {${v}u, ${n}u, ${d}u, ${battle.modify(v, [n, d])}u},`);
        }
    }
    line('};');
    line('');

    // chainModify sequences, starting from modifier 1
    const chains = [[[3, 2], [3, 2]], [[1, 2], [3, 2]], [[5325, 4096], [6144, 4096]], [[4915, 4096], [4915, 4096]],
        [[2, 1], [3, 4]], [[1, 1]], [[3, 4], [2, 1], [13, 10]], [[1, 4], [1, 4], [1, 4]], [[2, 1], [2, 1], [2, 1]],
        [[5, 4], [6, 5], [13, 10], [3, 2]]];
    line('/* up to four (numerator, denominator) pairs chained from 1; the result tr(modifier * 4096) */');
    line('static const uint32_t ref_chain[][9] = {');
    for (const c of chains) {
        battle.event = {modifier: 1};
        for (const [n, d] of c) battle.chainModify(n, d);
        const flat = [];
        for (let i = 0; i < 4; i++) flat.push(i < c.length ? c[i][0] : 0, i < c.length ? c[i][1] : 0);
        line(`    {${flat.map((x) => x + 'u').join(', ')}, ${tr(battle.event.modifier * 4096)}u},`);
    }
    line('};');
    line('');

    // base damage, inline at sim/battle-actions.ts:1718
    const levels = [1, 50, 100];
    const powers = [20, 40, 55, 90, 120, 250];
    const stats = [50, 120, 300, 999];
    line('/* level, base power, attack, defense, tr(tr(tr(tr(2 * L / 5 + 2) * P * A) / D) / 50) */');
    line('static const uint32_t ref_base_damage[][5] = {');
    for (const level of levels) {
        for (const bp of powers) {
            for (const a of stats) {
                for (const d of stats) {
                    const base = tr(tr(tr(tr(2 * level / 5 + 2) * bp * a) / d) / 50);
                    line(`    {${level}u, ${bp}u, ${a}u, ${d}u, ${base}u},`);
                }
            }
        }
    }
    line('};');
    line('');

    // randomizer with a fixed roll
    const damages = [1, 2, 10, 50, 100, 101, 999, 4000, 65535];
    line('/* damage, roll, Battle.randomizer(damage) with random(16) == roll */');
    line('static const uint32_t ref_randomize[][3] = {');
    for (const dmg of damages) {
        for (const roll of [0, 1, 7, 15]) {
            battle.random = (n) => {
                if (n !== 16) throw new Error('unexpected bound');
                return roll;
            };
            line(`    {${dmg}u, ${roll}u, ${battle.randomizer(dmg)}u},`);
        }
    }
    delete battle.random;
    line('};');
    line('');

    // crit, type steps and the final steps of modifyDamage
    const dm = [0, 1, 2, 3, 9, 100, 101, 65535, 65536, 65537, 131071, 200000];
    line('/* damage, tr(damage * 1.5), types -2..+2 (index 0..4), final (0 -> 1, tr(d, 16)) */');
    line('static const uint32_t ref_damage_steps[][8] = {');
    for (const d0 of dm) {
        const crit = tr(d0 * 1.5);
        const types = [];
        for (let typeMod = -2; typeMod <= 2; typeMod++) {
            let d = d0;
            if (typeMod > 0) for (let i = 0; i < typeMod; i++) d *= 2;
            if (typeMod < 0) for (let i = 0; i > typeMod; i--) d = tr(d / 2);
            types.push(d);
        }
        const fin = !d0 ? 1 : tr(d0, 16);
        line(`    {${d0}u, ${crit}u, ${types.map((x) => x + 'u').join(', ')}, ${fin}u},`);
    }
    line('};');
    line('');

    // Pokemon.calculateStat with a stage, on a real Pokemon of the format
    const team = Teams.import('Rillaboom @ Miracle Seed\nAbility: Grassy Surge\nLevel: 50\n' +
        'EVs: 18 HP / 32 Atk / 2 Def / 6 SpD / 8 Spe\nAdamant Nature\n- Wood Hammer\n');
    battle.setPlayer('p1', {name: 'A', team: Teams.pack(team)});
    battle.setPlayer('p2', {name: 'B', team: Teams.pack(team)});
    const mon = battle.p1.pokemon[0];
    line('/* stat, stage + 6, Pokemon.calculateStat(atk, stage) with storedStats.atk = stat */');
    line('static const uint32_t ref_stage_stat[][3] = {');
    for (const s of [1, 2, 3, 57, 100, 194, 255, 333, 999]) {
        mon.storedStats.atk = s;
        for (let stage = -6; stage <= 6; stage++) {
            line(`    {${s}u, ${stage + 6}u, ${mon.calculateStat('atk', stage)}u},`);
        }
    }
    line('};');
    line('');

    // accuracy stages, inline at sim/battle-actions.ts:722-727
    line('/* accuracy, stage + 6, accuracy after the stage */');
    line('static const uint32_t ref_stage_accuracy[][3] = {');
    for (const acc of [1, 30, 50, 60, 70, 80, 85, 90, 95, 100]) {
        for (let boost = -6; boost <= 6; boost++) {
            let a = acc;
            if (boost > 0) a = tr(a * (3 + boost) / 3);
            else if (boost < 0) a = tr(a * 3 / (3 - boost));
            line(`    {${acc}u, ${boost + 6}u, ${a}u},`);
        }
    }
    line('};');
    line('');
    line('#endif');
    const text = out.join('\n') + '\n';

    if (args.length === 3) {
        const have = fs.readFileSync(args[2], 'utf8').replace(/\r\n/g, '\n');
        if (have !== text) {
            process.stderr.write('arith_ref: ' + args[2] + ' differs from the reference output\n');
            process.exit(1);
        }
        process.stdout.write('arith_ref: ' + args[2] + ' matches the reference\n');
        return;
    }
    process.stdout.write(text);
}

main();
