#!/usr/bin/env python3
"""Reference battles of the real teams for the certification (decision 0010, M5 step 3).

For every pairing (A-B, B-A, A-A, B-B) and candidate index the generator
builds a spec: both teams (tests/reference/teams/team_a.txt, team_b.txt)
in a seeded random order (team preview brings the first four), a seeded
random plan and a seeded reference PRNG seed. It records every candidate
with the pinned reference (tools/reference/ps_trace.js) and keeps per
pairing the battles that add the most new coverage, greedily: protocol
line kinds with their effect, and draw sites with their context. A trace
with an UNKNOWN draw site or without a result is never kept.

The kept specs are written as <prefix>_<pairing>_<k>.json and recorded
again from that committed path (a trace stores its spec file name).
Everything is deterministic for the same arguments and the same pin.

usage: gen_real_specs.py --checkout <pinned reference> [--candidates 40]
       [--keep 4] [--seed 2026100101] [--prefix m5_real] [--jobs 8]
"""
import argparse
import concurrent.futures
import json
import os
import subprocess
import sys
import tempfile

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
SPECS = os.path.join(ROOT, 'tests', 'reference', 'specs')
TRACES = os.path.join(ROOT, 'tests', 'reference', 'traces')
HARNESS = os.path.join(ROOT, 'tools', 'reference', 'ps_trace.js')
FORMAT = 'gen9championsvgc2026regmc'
PAIRINGS = (('ab', 0, 1), ('ba', 1, 0), ('aa', 0, 0), ('bb', 1, 1))
MASK = (1 << 64) - 1


class SplitMix64:
    """The generator's only source of randomness (stable across Python versions)."""

    def __init__(self, seed):
        self.state = seed & MASK

    def next(self):
        self.state = (self.state + 0x9E3779B97F4A7C15) & MASK
        z = self.state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
        return z ^ (z >> 31)

    def below(self, n):
        return self.next() % n


def read_team(name):
    with open(os.path.join(ROOT, 'tests', 'reference', 'teams', name), encoding='utf-8') as f:
        sets = [s.strip() for s in f.read().split('\n\n') if s.strip()]
    assert len(sets) == 6, name
    return sets


def shuffled(rng, items):
    items = list(items)
    for i in range(len(items) - 1, 0, -1):
        j = rng.below(i + 1)
        items[i], items[j] = items[j], items[i]
    return items


def plan_entry(rng):
    """Two slot choices: a move (1..4) at foe 1 or 2, Mega declared half the
    time; one in eight is a switch to bench slot 3 or 4. The harness repairs
    what does not apply (no PP, no target, no Mega, a switch that cannot
    happen)."""
    parts = []
    for _ in range(2):
        if rng.below(8) == 0:
            parts.append('switch %d' % (3 + rng.below(2)))
        else:
            mega = ' mega' if rng.below(2) == 0 else ''
            parts.append('move %d %d%s' % (1 + rng.below(4), 1 + rng.below(2), mega))
    return ', '.join(parts)


def make_spec(name, pairing, teams, seed):
    rng = SplitMix64(seed)
    tag, first, second = pairing
    side_teams = ['\n\n'.join(shuffled(rng, teams[first])), '\n\n'.join(shuffled(rng, teams[second]))]
    ps_seed = 'sodium,' + ''.join('%016x' % rng.next() for _ in range(4))
    plan = {'p1': [plan_entry(rng) for _ in range(40)], 'p2': [plan_entry(rng) for _ in range(40)],
            'max_steps': 120}
    who = {'ab': 'team A against team B', 'ba': 'team B against team A', 'aa': 'team A against team A',
           'bb': 'team B against team B'}[tag]
    return {
        'name': name,
        'purpose': ('Certification (decision 0010, M5 step 3): the reference teams of decision 0004, %s, '
                    'four of six brought in a seeded random order and a seeded random plan, from team preview '
                    'to the end. Generated by tools/reference/gen_real_specs.py (candidate seed %d), kept for '
                    'the coverage it adds.' % (who, seed)),
        'format': FORMAT,
        'seed': ps_seed,
        'teams': side_teams,
        'plan': plan,
    }


def record(checkout, spec_path):
    out = subprocess.run(['node', HARNESS, checkout, spec_path], capture_output=True, text=True, encoding='utf-8')
    if out.returncode != 0:
        return None, out.stderr.strip()[-300:]
    return out.stdout, None


def features(trace):
    """The coverage of a trace, or None if it must not become a fixture."""
    found = set()
    ended = False
    for step in trace['steps']:
        for d in step['draws']:
            if d['site'] == 'UNKNOWN':
                return None
            found.add('draw:%s:%s' % (d['site'], d['context']))
        for line in step['log']:
            parts = line.split('|')
            if len(parts) < 2:
                continue
            kind = parts[1]
            if kind in ('win', 'tie'):
                ended = True
            if kind in ('', 'split', 't:', 'turn', 'upkeep', 'player', 'teamsize', 'gen', 'tier', 'rule', 'start',
                        'gametype', 'poke', 'clearpoke', 'teampreview', 'j', 'l', 'title', 'inactive'):
                continue
            if kind == 'move':
                flags = [p for p in parts[4:] if p.startswith('[')]
                found.add('move:%s%s' % (parts[3], ''.join(flags)))
            elif kind in ('-damage', '-heal'):
                src = [p for p in parts[4:] if p.startswith('[from]')]
                found.add('%s%s' % (kind, src[0] if src else ''))
            elif kind in ('-boost', '-unboost'):
                found.add('%s:%s:%s' % (kind, parts[3], parts[4] if len(parts) > 4 else ''))
            elif kind in ('switch', 'drag', 'faint', '-crit', '-miss', '-supereffective', '-resisted', 'detailschange',
                          '-mega', 'win', 'tie', 'replace', '-hitcount', '-notarget', '-nothing', '-clearallboost'):
                found.add(kind)
            else:
                effect = [p for p in parts[3:] if p and not p.startswith('p1') and not p.startswith('p2')]
                found.add('%s:%s' % (kind, '|'.join(effect)))
    return found if ended else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--checkout', required=True)
    ap.add_argument('--candidates', type=int, default=40)
    ap.add_argument('--keep', type=int, default=4)
    ap.add_argument('--seed', type=int, default=2026100101)
    ap.add_argument('--prefix', default='m5_real')
    ap.add_argument('--jobs', type=int, default=os.cpu_count() or 4)
    args = ap.parse_args()
    teams = [read_team('team_a.txt'), read_team('team_b.txt')]
    rng = SplitMix64(args.seed)
    seeds = {p[0]: [rng.next() for _ in range(args.candidates)] for p in PAIRINGS}
    with tempfile.TemporaryDirectory() as tmp:
        jobs = []
        for pairing in PAIRINGS:
            for i, seed in enumerate(seeds[pairing[0]]):
                spec = make_spec('candidate', pairing, teams, seed)
                path = os.path.join(tmp, '%s_%03d.json' % (pairing[0], i))
                with open(path, 'w', encoding='utf-8', newline='\n') as f:
                    json.dump(spec, f, indent=2, ensure_ascii=False)
                    f.write('\n')
                jobs.append((pairing, i, seed, path))
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
            results = list(pool.map(lambda j: record(args.checkout, j[3]), jobs))
    by_pairing = {p[0]: [] for p in PAIRINGS}
    for (pairing, i, seed, _), (out, err) in zip(jobs, results):
        if out is None:
            print('  %s candidate %d: the harness failed: %s' % (pairing[0], i, err), file=sys.stderr)
            continue
        f = features(json.loads(out))
        if f is not None:
            by_pairing[pairing[0]].append((i, seed, f))
    covered = set()
    kept = []
    for pairing in PAIRINGS:
        pool_ = by_pairing[pairing[0]]
        print('%s: %d of %d candidates usable' % (pairing[0], len(pool_), args.candidates))
        for k in range(1, args.keep + 1):
            best = max(pool_, key=lambda c: (len(c[2] - covered), -c[0]))
            pool_.remove(best)
            print('  keep candidate %d (seed %d): %d new' % (best[0], best[1], len(best[2] - covered)))
            covered |= best[2]
            kept.append(('%s_%s_%d' % (args.prefix, pairing[0], k), pairing, best[1]))
    for name, pairing, seed in kept:
        spec_path = os.path.join(SPECS, name + '.json')
        with open(spec_path, 'w', encoding='utf-8', newline='\n') as f:
            json.dump(make_spec(name, pairing, teams, seed), f, indent=2, ensure_ascii=False)
            f.write('\n')
        out, err = record(args.checkout, spec_path)
        if out is None:
            sys.exit('%s: the harness failed: %s' % (name, err))
        with open(os.path.join(TRACES, name + '.json'), 'w', encoding='utf-8', newline='\n') as f:
            f.write(out)
    print('covered %d features with %d battles' % (len(covered), len(kept)))


if __name__ == '__main__':
    main()
