#!/usr/bin/env python3
"""Expected party orders of recorded POOL battles (step G46, decision 0015 section 7).

For each recorded battle, after every step (the team step included), the order of side.pokemon of the pinned Showdown:
the trace's `state.sides[s].pokemon` list, which holds the brought members in that order. Each name is mapped to its roster
index through the battle's `start` log (`|poke|pN|Species, ...|` lines, the roster in team order).

Writes tests/reference/party_order_g46.h (committed); `--check` only compares. The C test
tests/test_pool_g46_party.c compares the engine's tail.party_order with these rows after every conformance step.

usage: python tools/reference/party_expect.py [--check]
"""
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
TRACES = os.path.join(ROOT, 'tests', 'reference', 'traces')
OUT = os.path.join(ROOT, 'tests', 'reference', 'party_order_g46.h')

# The recorded battles whose switches the replay check covers (POOL traces with the most switches).
BATTLES = ['g41_shadow_tag_trace', 'g41_shadow_tag_fainted', 'g5_uturn_e', 'g37_toxic_spikes']
BROUGHT = 4


def roster_of(start_log, side):
    """The species names of a side in roster (team) order, from the start log."""
    names = []
    tag = '|poke|p%d|' % (side + 1)
    for line in start_log:
        if line.startswith(tag):
            body = line[len(tag):].rstrip('|')
            names.append(body.split(',')[0].strip())
    return names


def expected_rows(name):
    path = os.path.join(TRACES, name + '.json')
    trace = json.load(open(path, encoding='utf-8'))
    rosters = [roster_of(trace['start']['log'], s) for s in range(2)]
    rows = []
    for si, step in enumerate(trace['steps']):
        per_side = []
        for s in range(2):
            mons = step['state']['sides'][s]['pokemon']
            if len(mons) != BROUGHT:
                raise SystemExit('%s step %d side %d: %d pokemon, expected %d' % (name, si, s, len(mons), BROUGHT))
            idx = []
            for m in mons:
                key = m.get('set_species', m['species'])
                if key not in rosters[s]:
                    raise SystemExit('%s step %d side %d: %r is not in the roster %r' % (name, si, s, key, rosters[s]))
                idx.append(rosters[s].index(key))
            if len(set(idx)) != len(idx):
                raise SystemExit('%s step %d side %d: a member twice: %r' % (name, si, s, idx))
            per_side.append(idx)
        rows.append((si, per_side))
    return rows


def render():
    out = []
    out.append('/* GENERATED by tools/reference/party_expect.py from tests/reference/traces (do not edit). */')
    out.append('/* The side.pokemon order of the pinned Showdown after every step of the recorded battles: roster indices of the')
    out.append(' * brought members, in order (decision 0015 section 7, party_order). */')
    out.append('#ifndef DUOFORGE_TESTS_REFERENCE_PARTY_ORDER_G46_H')
    out.append('#define DUOFORGE_TESTS_REFERENCE_PARTY_ORDER_G46_H')
    out.append('#include <stdint.h>')
    out.append('typedef struct df_party_row {')
    out.append('    uint32_t step;')
    out.append('    uint8_t order[2][%d]; /* roster index per side.pokemon position, 0-based */' % BROUGHT)
    out.append('} df_party_row;')
    out.append('typedef struct df_party_battle {')
    out.append('    const char *name;')
    out.append('    uint32_t row_count;')
    out.append('    const df_party_row *rows;')
    out.append('} df_party_battle;')
    for name in BATTLES:
        rows = expected_rows(name)
        ident = name.replace('-', '_')
        out.append('static const df_party_row party_%s[] = {' % ident)
        for si, per_side in rows:
            out.append('    {%d, {{%s}, {%s}}},' % (si, ', '.join(str(v) for v in per_side[0]),
                                                    ', '.join(str(v) for v in per_side[1])))
        out.append('};')
    out.append('static const df_party_battle party_battles[] = {')
    for name in BATTLES:
        ident = name.replace('-', '_')
        out.append('    {"%s", sizeof party_%s / sizeof party_%s[0], party_%s},' % (name, ident, ident, ident))
    out.append('};')
    out.append('#endif')
    return '\n'.join(out) + '\n'


def main(argv):
    text = render()
    if '--check' in argv:
        have = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if have != text:
            print('party_order_g46.h is out of date; run tools/reference/party_expect.py')
            return 1
        print('party_order_g46.h is up to date')
        return 0
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote', OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
