#!/usr/bin/env node
// Reference values of the reflectable moves (step G57, Magic Bounce): every move of the Champions format whose
// flags.reflectable is set in the pinned Dex, with its target class. Magic Bounce (data/abilities.ts:2437-2464) bounces
// a reflectable move aimed at its holder, so the C test compares the generated bit DFI_MOVE_FLAG3_REFLECTABLE (dfi_pool_move_flags3) with this
// list, and the marked moves with a fixed set of handled moves.
//
//   node tools/reference/reflect_ref.js <checkout> > tests/reference/reflect_ref.h
//   node tools/reference/reflect_ref.js <checkout> --check tests/reference/reflect_ref.h
//
// The Dex is the pinned checkout's own (dist/sim/dex.js, built by `node build`), with the Champions mod. Nothing is
// written except the header on stdout.
'use strict';
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const checkout = path.resolve(args[0] || '');
const check = args.indexOf('--check');
const dexPath = path.join(checkout, 'dist', 'sim', 'dex.js');
if (!fs.existsSync(dexPath)) {
    process.stderr.write('reflect_ref: no built sim at ' + dexPath + '\n');
    process.exit(2);
}
const { Dex } = require(dexPath);
const dex = Dex.mod('champions');
const rows = [];
for (const id of Object.keys(dex.data.Moves).sort()) {
    const move = dex.moves.get(id);
    if (!move.exists || !move.flags || !move.flags.reflectable) continue;
    rows.push({ id, target: move.target });
}

const lines = [
    '/* GENERATED by tools/reference/reflect_ref.js (step G57) -- do not edit.',
    ' * The Champions moves with flags.reflectable in the pinned Showdown Dex, by Showdown id, with their target class. */',
    '#define DF_REFLECT_REF_COUNT ' + rows.length + 'u',
    'static const struct { const char *id; const char *target; } df_reflect_ref[DF_REFLECT_REF_COUNT] = {',
];
for (const r of rows) lines.push('    {"' + r.id + '", "' + r.target + '"},');
lines.push('};', '');
const text = lines.join('\n');

if (check >= 0) {
    const expected = fs.readFileSync(args[check + 1], 'utf8');
    if (expected !== text) {
        process.stderr.write('reflect_ref: ' + args[check + 1] + ' differs from the pinned Dex\n');
        process.exit(1);
    }
    process.stdout.write('reflect_ref: ok (' + rows.length + ' moves)\n');
} else {
    process.stdout.write(text);
}
