# Negative control of duoforge.certify.dataset: a copy of the dataset with one
# change must fail the verification. KIND digest changes a final digest,
# KIND choice a stored choice, KIND seed a policy seed (first battle each).
# -DCERTIFY=<tool> -DDATASET=<file> -DOUT=<copy> -DKIND=<kind>
file(STRINGS "${DATASET}" _lines)
set(_out "")
set(_done FALSE)
foreach(_line IN LISTS _lines)
    if(NOT _done AND _line MATCHES "^b ")
        string(REPLACE " " ";" _f "${_line}")
        if(KIND STREQUAL "digest")
            list(GET _f 8 _v)
            string(SUBSTRING "${_v}" 0 1 _c)
            if(_c STREQUAL "0")
                set(_c "1")
            else()
                set(_c "0")
            endif()
            string(SUBSTRING "${_v}" 1 -1 _rest)
            list(REMOVE_AT _f 8)
            list(INSERT _f 8 "${_c}${_rest}")
        elseif(KIND STREQUAL "choice")
            list(GET _f 9 _v)
            string(SUBSTRING "${_v}" 0 3 _c)
            if(_c STREQUAL "000")
                set(_c "001")
            else()
                set(_c "000")
            endif()
            string(SUBSTRING "${_v}" 3 -1 _rest)
            list(REMOVE_AT _f 9)
            list(INSERT _f 9 "${_c}${_rest}")
        elseif(KIND STREQUAL "seed")
            list(GET _f 4 _v)
            string(SUBSTRING "${_v}" 0 15 _head)
            string(SUBSTRING "${_v}" 15 1 _c)
            if(_c STREQUAL "0")
                set(_c "1")
            else()
                set(_c "0")
            endif()
            list(REMOVE_AT _f 4)
            list(INSERT _f 4 "${_head}${_c}")
        else()
            message(FATAL_ERROR "unknown KIND ${KIND}")
        endif()
        string(REPLACE ";" " " _line "${_f}")
        set(_done TRUE)
    endif()
    string(APPEND _out "${_line}\n")
endforeach()
file(WRITE "${OUT}" "${_out}")
execute_process(COMMAND "${CERTIFY}" verify "${OUT}" RESULT_VARIABLE _rc OUTPUT_QUIET ERROR_QUIET)
if(_rc EQUAL 0)
    message(FATAL_ERROR "the verification accepts a dataset with a changed ${KIND}")
endif()
message(STATUS "a changed ${KIND} fails the verification, as it must")
