/*
 * GENERATED by tools/kat/gen_pcg32_kat.c against the pinned reference
 * imneme/pcg-c-basic@bc39cd76ac3d541e618606bcc6e1e5ba5e5e6aa3
 * (pcg_basic.c sha256 b6582a071a8a090a293621523c063d125a532d772a2a1eb7d60b3e695fe47746,
 *  pcg_basic.h sha256 cd823ddc225da9be520a54f13ef2c491506c353800cae04e8b673b2de58f2cc4).
 * DO NOT EDIT. Regenerate with the command in tools/kat/README.md.
 */
#ifndef DUOFORGE_TESTS_DATA_PCG32_KAT_VECTORS_H
#define DUOFORGE_TESTS_DATA_PCG32_KAT_VECTORS_H

#include <stdint.h>

#define DF_KAT_SEED_COUNT 6u
#define DF_KAT_RAW_COUNT 16u
#define DF_KAT_BOUND_COUNT 9u
#define DF_KAT_CALLS 12u
#define DF_KAT_SHUFFLE_FIRST 52u
#define DF_KAT_SHUFFLE_COUNT 51u

typedef struct df_kat_bounded {
    uint32_t bound;
    uint32_t value[DF_KAT_CALLS];
    uint32_t draws[DF_KAT_CALLS];
} df_kat_bounded;

typedef struct df_kat_seed {
    uint64_t initstate;
    uint64_t initseq;
    uint64_t state; /* after seeding */
    uint64_t inc;
    uint32_t raw[DF_KAT_RAW_COUNT];
    uint64_t state_after_raw;
    df_kat_bounded bounded[DF_KAT_BOUND_COUNT]; /* each from a fresh seed */
    uint32_t shuffle_value[DF_KAT_SHUFFLE_COUNT]; /* bounded(52), bounded(51), ... bounded(2) from a fresh seed */
    uint32_t shuffle_draws[DF_KAT_SHUFFLE_COUNT];
} df_kat_seed;

static const df_kat_seed df_kat_seeds[DF_KAT_SEED_COUNT] = {
    {
        UINT64_C(0x000000000000002a), UINT64_C(0x0000000000000036),
        UINT64_C(0x185706b82c2e03f8), UINT64_C(0x000000000000006d),
        {UINT32_C(0xa15c02b7), UINT32_C(0x7b47f409), UINT32_C(0xba1d3330), UINT32_C(0x83d2f293), UINT32_C(0xbfa4784b), UINT32_C(0xcbed606e), UINT32_C(0xbfc6a3ad), UINT32_C(0x812fff6d), UINT32_C(0xe61f305a), UINT32_C(0xf9384b90), UINT32_C(0x32db86fe), UINT32_C(0x1dc035f9), UINT32_C(0xed786826), UINT32_C(0x3822441d), UINT32_C(0x2ba113d7), UINT32_C(0x1c5b818b)},
        UINT64_C(0xbdaaa7a4f94ba8e8),
        {
            {UINT32_C(0x00000001), {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000002), {1u, 1u, 0u, 1u, 1u, 0u, 1u, 1u, 0u, 0u, 0u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000003), {0u, 0u, 2u, 1u, 1u, 1u, 2u, 0u, 0u, 2u, 0u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000006), {3u, 3u, 2u, 1u, 1u, 4u, 5u, 3u, 0u, 2u, 0u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000007), {4u, 4u, 6u, 0u, 3u, 2u, 5u, 1u, 0u, 0u, 4u, 6u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000064), {83u, 97u, 24u, 55u, 55u, 66u, 85u, 45u, 74u, 44u, 42u, 93u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000000), {559678135u, 2068313097u, 974992176u, 64156307u, 1067743307u, 1273847918u, 1069982637u, 19922797u, 1713320026u, 2033732496u, 853247742u, 499135993u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000001), {559678134u, 974992175u, 64156306u, 1067743306u, 1273847917u, 1069982636u, 19922796u, 1713320025u, 2033732495u, 1836607525u, 573805929u, 81421794u}, {1u, 2u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 3u, 4u, 1u}},
            {UINT32_C(0xffffffff), {2707161783u, 2068313097u, 3122475824u, 2211639955u, 3215226955u, 3421331566u, 3217466285u, 2167406445u, 3860803674u, 4181216144u, 853247742u, 499135993u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
        },
        {27u, 39u, 24u, 14u, 43u, 30u, 11u, 30u, 2u, 32u, 18u, 25u, 14u, 19u, 29u, 0u, 6u, 23u, 0u, 9u, 16u, 11u, 1u, 17u, 11u, 7u, 18u, 10u, 12u, 6u, 1u, 1u, 12u, 12u, 12u, 9u, 0u, 9u, 12u, 9u, 7u, 2u, 2u, 7u, 7u, 6u, 1u, 3u, 1u, 2u, 0u},
        {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u},
    },
    {
        UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000),
        UINT64_C(0x5851f42d4c957f2e), UINT64_C(0x0000000000000001),
        {UINT32_C(0xe4c14788), UINT32_C(0x379c6516), UINT32_C(0x5c4ab3bb), UINT32_C(0x601d23e0), UINT32_C(0x1c382b8c), UINT32_C(0xd1faab16), UINT32_C(0x67680a2d), UINT32_C(0x92014a6e), UINT32_C(0x628ae389), UINT32_C(0xa794034d), UINT32_C(0x5cc38cd9), UINT32_C(0xfc913a3b), UINT32_C(0x81c851dc), UINT32_C(0x90c820e4), UINT32_C(0x60dfa703), UINT32_C(0xd613ae14)},
        UINT64_C(0x742d2f7a98716b5e),
        {
            {UINT32_C(0x00000001), {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000002), {0u, 0u, 1u, 0u, 0u, 0u, 1u, 0u, 1u, 1u, 1u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000003), {1u, 1u, 1u, 0u, 0u, 1u, 1u, 1u, 0u, 2u, 2u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000006), {4u, 4u, 1u, 0u, 0u, 4u, 1u, 4u, 3u, 5u, 5u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000007), {5u, 2u, 2u, 0u, 4u, 1u, 4u, 1u, 5u, 6u, 6u, 0u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000064), {8u, 74u, 47u, 64u, 12u, 42u, 97u, 26u, 85u, 45u, 49u, 59u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000000), {1690388360u, 932996374u, 1548399547u, 1612522464u, 473443212u, 1375382294u, 1734871597u, 302074478u, 1653269385u, 664011597u, 1556319449u, 2089892411u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000001), {1690388359u, 1375382293u, 302074477u, 664011596u, 2089892410u, 29905371u, 281551075u, 1444130323u, 1156514208u, 51107104u, 1940458944u, 567008472u}, {1u, 5u, 2u, 2u, 2u, 1u, 1u, 2u, 3u, 7u, 5u, 1u}},
            {UINT32_C(0xffffffff), {3837872008u, 932996374u, 1548399547u, 1612522464u, 473443212u, 3522865942u, 1734871597u, 2449558126u, 1653269385u, 2811495245u, 1556319449u, 4237376059u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
        },
        {48u, 28u, 47u, 35u, 12u, 24u, 43u, 1u, 9u, 15u, 41u, 24u, 20u, 25u, 25u, 33u, 9u, 0u, 19u, 9u, 23u, 21u, 23u, 16u, 19u, 4u, 24u, 20u, 20u, 9u, 9u, 12u, 11u, 3u, 1u, 4u, 11u, 9u, 0u, 4u, 5u, 1u, 5u, 5u, 6u, 1u, 5u, 4u, 0u, 2u, 0u},
        {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u},
    },
    {
        UINT64_C(0x0000000000000001), UINT64_C(0x0000000000000001),
        UINT64_C(0x6147d0b53255fcb7), UINT64_C(0x0000000000000003),
        {UINT32_C(0xc9828f91), UINT32_C(0x1592e274), UINT32_C(0xc0262657), UINT32_C(0xa5c2b6d3), UINT32_C(0xaf811256), UINT32_C(0x6c1c2879), UINT32_C(0x30130b26), UINT32_C(0x9cc21c33), UINT32_C(0xd137ef42), UINT32_C(0x908262ab), UINT32_C(0xd24d7799), UINT32_C(0xaa1118ab), UINT32_C(0xe16c3ebd), UINT32_C(0xbd77a511), UINT32_C(0x87d285e4), UINT32_C(0x260276e8)},
        UINT64_C(0x45d34e10fa7ef287),
        {
            {UINT32_C(0x00000001), {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000002), {1u, 0u, 1u, 1u, 0u, 1u, 0u, 1u, 0u, 1u, 1u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000003), {1u, 2u, 1u, 2u, 0u, 0u, 2u, 0u, 2u, 0u, 1u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000006), {1u, 2u, 1u, 5u, 0u, 3u, 2u, 3u, 2u, 3u, 1u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000007), {2u, 3u, 3u, 1u, 3u, 4u, 0u, 0u, 4u, 1u, 6u, 2u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000064), {49u, 64u, 55u, 27u, 38u, 97u, 6u, 99u, 74u, 43u, 49u, 47u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000000), {1233293201u, 361947764u, 1076242007u, 633517779u, 796987990u, 1813784697u, 806554406u, 482483251u, 1362620226u, 276980395u, 1380808601u, 705763499u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000001), {1233293200u, 1076242006u, 633517778u, 796987989u, 482483250u, 1362620225u, 276980394u, 1380808600u, 705763498u, 1634483900u, 1031251216u, 131237347u}, {1u, 2u, 1u, 1u, 3u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0xffffffff), {3380776849u, 361947764u, 3223725655u, 2781001427u, 2944471638u, 1813784697u, 806554406u, 2629966899u, 3510103874u, 2424464043u, 3528292249u, 2853247147u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
        },
        {21u, 50u, 5u, 8u, 6u, 36u, 20u, 39u, 2u, 31u, 13u, 34u, 29u, 7u, 0u, 17u, 20u, 34u, 0u, 7u, 23u, 26u, 5u, 3u, 21u, 20u, 11u, 13u, 9u, 13u, 10u, 13u, 11u, 5u, 8u, 6u, 12u, 10u, 9u, 3u, 0u, 6u, 0u, 8u, 3u, 5u, 1u, 3u, 2u, 2u, 0u},
        {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u},
    },
    {
        UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff),
        UINT64_C(0x4f5c17a566d501a5), UINT64_C(0xffffffffffffffff),
        {UINT32_C(0x2675c047), UINT32_C(0x7779a837), UINT32_C(0xa145aa13), UINT32_C(0x5f6be726), UINT32_C(0x523c44c5), UINT32_C(0x75a406d6), UINT32_C(0xe6643b13), UINT32_C(0x8e3d51a0), UINT32_C(0x45bdd0c6), UINT32_C(0x157fd45c), UINT32_C(0xc5899fc0), UINT32_C(0x1f7821df), UINT32_C(0x85e92559), UINT32_C(0xbb68a3ff), UINT32_C(0x1d80c5de), UINT32_C(0x80b7742f)},
        UINT64_C(0xa28710e43663e435),
        {
            {UINT32_C(0x00000001), {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000002), {1u, 1u, 1u, 0u, 1u, 0u, 1u, 0u, 0u, 0u, 0u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000003), {1u, 1u, 2u, 0u, 2u, 0u, 0u, 0u, 1u, 2u, 1u, 2u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000006), {1u, 1u, 5u, 0u, 5u, 0u, 3u, 0u, 4u, 2u, 4u, 5u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000007), {5u, 3u, 4u, 4u, 6u, 4u, 6u, 6u, 0u, 4u, 4u, 3u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000064), {43u, 23u, 99u, 46u, 77u, 26u, 3u, 64u, 54u, 72u, 80u, 87u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000000), {645251143u, 2004461623u, 558213651u, 1600907046u, 1379681477u, 1973683926u, 1717844755u, 238899616u, 1170067654u, 360698972u, 1166647232u, 527966687u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000001), {558213650u, 1717844754u, 238899615u, 1166647231u, 99165528u, 996713470u, 12022830u, 1502067927u, 1647347587u, 1230683528u, 1319275551u, 702381123u}, {3u, 4u, 1u, 3u, 2u, 1u, 2u, 2u, 1u, 3u, 2u, 2u}},
            {UINT32_C(0xffffffff), {645251143u, 2004461623u, 2705697299u, 1600907046u, 1379681477u, 1973683926u, 3865328403u, 2386383264u, 1170067654u, 360698972u, 3314130880u, 527966687u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
        },
        {43u, 4u, 49u, 18u, 5u, 1u, 15u, 9u, 30u, 8u, 4u, 11u, 17u, 37u, 26u, 36u, 26u, 6u, 14u, 20u, 29u, 23u, 6u, 20u, 11u, 3u, 3u, 15u, 6u, 16u, 1u, 1u, 8u, 9u, 3u, 2u, 1u, 5u, 1u, 8u, 1u, 6u, 7u, 7u, 2u, 5u, 0u, 1u, 0u, 0u, 0u},
        {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u},
    },
    {
        UINT64_C(0x853c49e6748fea9b), UINT64_C(0xda3e39cb94b95bdb),
        UINT64_C(0xea1b84321029ee21), UINT64_C(0xb47c73972972b7b7),
        {UINT32_C(0x1bbeb4f2), UINT32_C(0xe82e89e9), UINT32_C(0x681cfdeb), UINT32_C(0xe00fa2ec), UINT32_C(0xb1e1a434), UINT32_C(0xbe56068d), UINT32_C(0x2add8c94), UINT32_C(0x9f1b63f5), UINT32_C(0x38bfe349), UINT32_C(0xe5601e3d), UINT32_C(0x66ad0ba4), UINT32_C(0x6587fa97), UINT32_C(0x58ce0bbf), UINT32_C(0xa76b235a), UINT32_C(0xca5a9c9b), UINT32_C(0xe28a991b)},
        UINT64_C(0xfe76f203a5af6631),
        {
            {UINT32_C(0x00000001), {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000002), {0u, 1u, 1u, 0u, 0u, 1u, 0u, 1u, 1u, 1u, 0u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000003), {0u, 0u, 2u, 1u, 0u, 0u, 2u, 2u, 1u, 2u, 0u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000006), {0u, 3u, 5u, 4u, 0u, 3u, 2u, 5u, 1u, 5u, 0u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000007), {4u, 6u, 0u, 4u, 5u, 2u, 2u, 0u, 5u, 0u, 5u, 3u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000064), {94u, 73u, 75u, 32u, 68u, 13u, 16u, 5u, 57u, 61u, 40u, 27u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000000), {465482994u, 1747880425u, 1746730475u, 1611637484u, 836871220u, 1045825165u, 719162516u, 521888757u, 952099657u, 1700798013u, 1722616740u, 1703410327u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000001), {1747880424u, 1611637483u, 836871219u, 1045825164u, 521888756u, 1700798012u, 661332825u, 1247452314u, 1653250330u, 498296710u, 1629825684u, 502453583u}, {2u, 2u, 1u, 1u, 2u, 2u, 4u, 1u, 1u, 1u, 8u, 2u}},
            {UINT32_C(0xffffffff), {465482994u, 3895364073u, 1746730475u, 3759121132u, 2984354868u, 3193308813u, 719162516u, 2669372405u, 952099657u, 3848281661u, 1722616740u, 1703410327u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
        },
        {2u, 36u, 25u, 39u, 36u, 33u, 34u, 35u, 25u, 15u, 12u, 14u, 31u, 9u, 3u, 36u, 31u, 4u, 17u, 7u, 12u, 3u, 10u, 8u, 21u, 3u, 20u, 14u, 21u, 18u, 6u, 12u, 8u, 16u, 3u, 10u, 13u, 14u, 5u, 6u, 0u, 4u, 2u, 0u, 5u, 5u, 3u, 0u, 3u, 0u, 1u},
        {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u},
    },
    {
        UINT64_C(0x0123456789abcdef), UINT64_C(0xfedcba9876543210),
        UINT64_C(0x8c89cf5f619b20f1), UINT64_C(0xfdb97530eca86421),
        {UINT32_C(0xc7d1489e), UINT32_C(0x038cf20c), UINT32_C(0xa6447e87), UINT32_C(0x3d5a66c3), UINT32_C(0x2abd7746), UINT32_C(0x3c336fb6), UINT32_C(0xe7c82888), UINT32_C(0x40a9cf96), UINT32_C(0xb5ddec84), UINT32_C(0x9a3bae92), UINT32_C(0xa81b65e5), UINT32_C(0x164225af), UINT32_C(0x1f3b8e2b), UINT32_C(0xe28b6143), UINT32_C(0xca5cbc82), UINT32_C(0x27ded18a)},
        UINT64_C(0x4568bc0856308de1),
        {
            {UINT32_C(0x00000001), {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000002), {0u, 0u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 1u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000003), {2u, 1u, 0u, 1u, 0u, 2u, 1u, 2u, 2u, 2u, 0u, 0u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000006), {2u, 4u, 3u, 1u, 0u, 2u, 4u, 2u, 2u, 2u, 3u, 3u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000007), {6u, 3u, 3u, 4u, 0u, 4u, 3u, 1u, 5u, 1u, 1u, 1u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x00000064), {98u, 52u, 95u, 23u, 10u, 94u, 72u, 50u, 0u, 78u, 45u, 75u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000000), {1204897950u, 59568652u, 642023047u, 1029334723u, 717059910u, 1010003894u, 1741170824u, 1084870550u, 903736452u, 440118930u, 672884197u, 373433775u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
            {UINT32_C(0x80000001), {1204897949u, 642023046u, 1741170823u, 903736451u, 440118929u, 672884196u, 1653301570u, 1247591553u, 1815796402u, 651802837u, 1142854331u, 755311204u}, {1u, 2u, 4u, 2u, 1u, 1u, 3u, 1u, 3u, 3u, 1u, 4u}},
            {UINT32_C(0xffffffff), {3352381598u, 59568652u, 2789506695u, 1029334723u, 717059910u, 1010003894u, 3888654472u, 1084870550u, 3051220100u, 2587602578u, 2820367845u, 373433775u}, {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u}},
        },
        {46u, 40u, 45u, 4u, 6u, 26u, 36u, 20u, 16u, 6u, 15u, 35u, 35u, 10u, 10u, 12u, 14u, 31u, 5u, 10u, 22u, 26u, 22u, 14u, 11u, 13u, 11u, 9u, 21u, 18u, 18u, 8u, 4u, 16u, 10u, 2u, 4u, 0u, 1u, 3u, 6u, 0u, 7u, 4u, 0u, 1u, 5u, 0u, 0u, 2u, 1u},
        {1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u},
    },
};

#endif
