# Writes the revision and the dirty flag of the source tree for the benchmark
# manifest (docs/decisions/0008), at every build; the file changes only when
# its content does. usage: cmake -DSRC=<repo> -DOUT=<header> -P bench_revision.cmake

execute_process(COMMAND git -C "${SRC}" rev-parse HEAD
    OUTPUT_VARIABLE _rev OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _r1 ERROR_QUIET)
if(NOT _r1 EQUAL 0 OR _rev STREQUAL "")
    set(_rev "unknown")
endif()
execute_process(COMMAND git -C "${SRC}" status --porcelain --untracked-files=no
    OUTPUT_VARIABLE _status RESULT_VARIABLE _r2 ERROR_QUIET)
if(_r2 EQUAL 0 AND _status STREQUAL "")
    set(_dirty 0)
else()
    set(_dirty 1)
endif()
set(_content "/* Generated by cmake/bench_revision.cmake at build time. */\n#define DFB_REVISION \"${_rev}\"\n#define DFB_DIRTY ${_dirty}\n")
set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
