#ifndef DUOFORGE_DATA_CLOSURE_TABLES_H
#define DUOFORGE_DATA_CLOSURE_TABLES_H
/*
 * GENERATED by tools/datagen/gen_closure.py -- do not edit.
 *
 * Immutable data of the two reference teams (docs/decisions/0004, 0006),
 * read from Pokemon Showdown b2cb775b0616115b775534eaeff50300e1fc81fc.
 * Input files (sha256 after CRLF -> LF):
 *   73048386b864be5aff093e9393acf32e8016299e9d7b76078bf5120b769e2fe0  data/pokedex.ts
 *   6b44af2a393739e00fc444dc574eaa79659b68867777012b0f7ce4727a9b7734  data/moves.ts
 *   818edd100c8eb5bdf4d4ded8dd1b1ce9d394f87f40f7d9d53a5414276e84f82b  data/abilities.ts
 *   75da206e2cb09868bb549360f38a144c2f50b24e1d189e03b485d550a4f6357a  data/items.ts
 *   7b0eae126bdcf98edfd71cbe75af00b763f5f0d5db36024b6f3e7c5e4aea95ac  data/typechart.ts
 *   5cfefee4c23dd19f629deb9a67f75361226bd24fe34cefe9a13d30d985428416  data/natures.ts
 *   1d317da33d3e36d430a9cbe195c2ef9bb9a6fc2f3e0516ba2200da8a394080bc  data/mods/champions/moves.ts
 *   b39dafa66d136ebb1a8576367ced2c9f4519aa1c17d5d65c59b368ac15d7de77  data/mods/champions/items.ts
 *   86c3843d402f1ff7be276d8f2da08d6744b8a8822349560b300ddcfa9c1fbc52  data/mods/champions/abilities.ts
 *   a512b537a84574a324c250c6ff99ad60f0cf1e82420fdae60d4635eec8661e13  data/mods/champions/formats-data.ts
 *   826d302703358260a1c4967e2bf8edd15f1fe7e0f664c8ab14aff734906cc9d0  data/mods/champions/learnsets.ts
 *   a6cc11eeb525ad58dee9010dd0d42274a5b4dacb39ce8653f4888cbd2f4f459d  data/mods/champions/scripts.ts
 *
 * Data only. An id names a record; every effect needs a typed handler in C
 * and an entry in the support manifest before a battle may use it.
 */
#include <stddef.h>
#include <stdint.h>

#define DFI_CLOSURE_NONE 0xFFu

/* ---- formes (base formes are selectable; Mega formes are reached in battle) ---- */
#define DFI_FORME_RILLABOOM 0u
#define DFI_FORME_STARAPTOR 1u
#define DFI_FORME_STARAPTORMEGA 2u
#define DFI_FORME_MILOTIC 3u
#define DFI_FORME_CERULEDGE 4u
#define DFI_FORME_RAICHU 5u
#define DFI_FORME_RAICHUMEGAY 6u
#define DFI_FORME_GHOLDENGO 7u
#define DFI_FORME_POLITOED 8u
#define DFI_FORME_GOLISOPOD 9u
#define DFI_FORME_GOLISOPODMEGA 10u
#define DFI_FORME_ARCHALUDON 11u
#define DFI_FORME_FARIGIRAF 12u
#define DFI_FORME_CHARIZARD 13u
#define DFI_FORME_CHARIZARDMEGAY 14u
#define DFI_FORME_GRIMMSNARL 15u
#define DFI_FORME_COUNT 16u

/* ---- moves: ids 0..35 follow decision 0005 (fixture table T1) ---- */
#define DFI_MOVE_WOODHAMMER 0u
#define DFI_MOVE_GRASSYGLIDE 1u
#define DFI_MOVE_FAKEOUT 2u
#define DFI_MOVE_HIGHHORSEPOWER 3u
#define DFI_MOVE_BRAVEBIRD 4u
#define DFI_MOVE_CLOSECOMBAT 5u
#define DFI_MOVE_TAILWIND 6u
#define DFI_MOVE_PROTECT 7u
#define DFI_MOVE_MUDDYWATER 8u
#define DFI_MOVE_COIL 9u
#define DFI_MOVE_ICEBEAM 10u
#define DFI_MOVE_HYPNOSIS 11u
#define DFI_MOVE_BITTERBLADE 12u
#define DFI_MOVE_SHADOWSNEAK 13u
#define DFI_MOVE_SWORDSDANCE 14u
#define DFI_MOVE_ZAPCANNON 15u
#define DFI_MOVE_FOCUSBLAST 16u
#define DFI_MOVE_MAKEITRAIN 17u
#define DFI_MOVE_SHADOWBALL 18u
#define DFI_MOVE_NASTYPLOT 19u
#define DFI_MOVE_WEATHERBALL 20u
#define DFI_MOVE_LEECHLIFE 21u
#define DFI_MOVE_IRONHEAD 22u
#define DFI_MOVE_DRILLRUN 23u
#define DFI_MOVE_DRAGONPULSE 24u
#define DFI_MOVE_ELECTROSHOT 25u
#define DFI_MOVE_SNARL 26u
#define DFI_MOVE_PSYCHIC 27u
#define DFI_MOVE_GRASSKNOT 28u
#define DFI_MOVE_TRICKROOM 29u
#define DFI_MOVE_HEATWAVE 30u
#define DFI_MOVE_HURRICANE 31u
#define DFI_MOVE_SPIRITBREAK 32u
#define DFI_MOVE_REFLECT 33u
#define DFI_MOVE_LIGHTSCREEN 34u
#define DFI_MOVE_PARTINGSHOT 35u
#define DFI_MOVE_STRUGGLE 36u
#define DFI_MOVE_COUNT 37u

/* ---- abilities ---- */
#define DFI_ABILITY_GRASSYSURGE 0u
#define DFI_ABILITY_INTIMIDATE 1u
#define DFI_ABILITY_COMPETITIVE 2u
#define DFI_ABILITY_FLASHFIRE 3u
#define DFI_ABILITY_LIGHTNINGROD 4u
#define DFI_ABILITY_GOODASGOLD 5u
#define DFI_ABILITY_DRIZZLE 6u
#define DFI_ABILITY_EMERGENCYEXIT 7u
#define DFI_ABILITY_STAMINA 8u
#define DFI_ABILITY_ARMORTAIL 9u
#define DFI_ABILITY_BLAZE 10u
#define DFI_ABILITY_PRANKSTER 11u
#define DFI_ABILITY_CONTRARY 12u
#define DFI_ABILITY_NOGUARD 13u
#define DFI_ABILITY_TOUGHCLAWS 14u
#define DFI_ABILITY_DROUGHT 15u
#define DFI_ABILITY_COUNT 16u

/* ---- items ---- */
#define DFI_ITEM_MIRACLESEED 0u
#define DFI_ITEM_STARAPTITE 1u
#define DFI_ITEM_SITRUSBERRY 2u
#define DFI_ITEM_GRASSYSEED 3u
#define DFI_ITEM_RAICHUNITEY 4u
#define DFI_ITEM_LIFEORB 5u
#define DFI_ITEM_MYSTICWATER 6u
#define DFI_ITEM_GOLISOPITE 7u
#define DFI_ITEM_LEFTOVERS 8u
#define DFI_ITEM_CHARIZARDITEY 9u
#define DFI_ITEM_LIGHTCLAY 10u
#define DFI_ITEM_COUNT 11u

/* ---- types (the 18 battle types; Stellar is not part of Champions) ---- */
#define DFI_TYPE_BUG 0u
#define DFI_TYPE_DARK 1u
#define DFI_TYPE_DRAGON 2u
#define DFI_TYPE_ELECTRIC 3u
#define DFI_TYPE_FAIRY 4u
#define DFI_TYPE_FIGHTING 5u
#define DFI_TYPE_FIRE 6u
#define DFI_TYPE_FLYING 7u
#define DFI_TYPE_GHOST 8u
#define DFI_TYPE_GRASS 9u
#define DFI_TYPE_GROUND 10u
#define DFI_TYPE_ICE 11u
#define DFI_TYPE_NORMAL 12u
#define DFI_TYPE_POISON 13u
#define DFI_TYPE_PSYCHIC 14u
#define DFI_TYPE_ROCK 15u
#define DFI_TYPE_STEEL 16u
#define DFI_TYPE_WATER 17u
#define DFI_TYPE_COUNT 18u

/* ---- natures ---- */
#define DFI_NATURE_ADAMANT 0u
#define DFI_NATURE_BASHFUL 1u
#define DFI_NATURE_BOLD 2u
#define DFI_NATURE_BRAVE 3u
#define DFI_NATURE_CALM 4u
#define DFI_NATURE_CAREFUL 5u
#define DFI_NATURE_DOCILE 6u
#define DFI_NATURE_GENTLE 7u
#define DFI_NATURE_HARDY 8u
#define DFI_NATURE_HASTY 9u
#define DFI_NATURE_IMPISH 10u
#define DFI_NATURE_JOLLY 11u
#define DFI_NATURE_LAX 12u
#define DFI_NATURE_LONELY 13u
#define DFI_NATURE_MILD 14u
#define DFI_NATURE_MODEST 15u
#define DFI_NATURE_NAIVE 16u
#define DFI_NATURE_NAUGHTY 17u
#define DFI_NATURE_QUIET 18u
#define DFI_NATURE_QUIRKY 19u
#define DFI_NATURE_RASH 20u
#define DFI_NATURE_RELAXED 21u
#define DFI_NATURE_SASSY 22u
#define DFI_NATURE_SERIOUS 23u
#define DFI_NATURE_TIMID 24u
#define DFI_NATURE_COUNT 25u

/* ---- stat and stage indices ---- */
#define DFI_STAT_HP 0u
#define DFI_STAT_ATK 1u
#define DFI_STAT_DEF 2u
#define DFI_STAT_SPA 3u
#define DFI_STAT_SPD 4u
#define DFI_STAT_SPE 5u
#define DFI_STAT_COUNT 6u
#define DFI_STAGE_ATK 0u
#define DFI_STAGE_DEF 1u
#define DFI_STAGE_SPA 2u
#define DFI_STAGE_SPD 3u
#define DFI_STAGE_SPE 4u
#define DFI_STAGE_ACCURACY 5u
#define DFI_STAGE_EVASION 6u
#define DFI_STAGE_COUNT 7u
#define DFI_STAGE_BIAS 6u /* a stored stage value v means v - 6 */

#define DFI_CATEGORY_PHYSICAL 0u
#define DFI_CATEGORY_SPECIAL 1u
#define DFI_CATEGORY_STATUS 2u

#define DFI_STATUS_NONE 0u
#define DFI_STATUS_BRN 1u
#define DFI_STATUS_FRZ 2u
#define DFI_STATUS_PAR 3u
#define DFI_STATUS_SLP 4u

#define DFI_VOLATILE_FLINCH 1u
#define DFI_VOLATILE_CONFUSION 2u

#define DFI_GENDER_RULE_ANY 0u    /* male or female */
#define DFI_GENDER_RULE_MALE 1u
#define DFI_GENDER_RULE_FEMALE 2u
#define DFI_GENDER_RULE_NONE 3u   /* genderless */

/* Move flags. */
#define DFI_MOVE_FLAG_CONTACT 1u
#define DFI_MOVE_FLAG_PROTECT 2u
#define DFI_MOVE_FLAG_CHARGE 4u
#define DFI_MOVE_FLAG_STALLING 8u
#define DFI_MOVE_FLAG_SELF_SWITCH 16u
#define DFI_MOVE_FLAG_NO_PP_BOOSTS 32u
#define DFI_MOVE_FLAG_STRUGGLE_RECOIL 64u

#define DFI_PRIORITY_BIAS 8u /* a stored priority p means p - 8 */
#define DFI_TARGET_CLASS_RANDOM_NORMAL 10u /* Struggle only; never selectable */

#define DFI_SECONDARY_NONE 0u
#define DFI_SECONDARY_BOOST 1u    /* boosts[] applied to the target */
#define DFI_SECONDARY_STATUS 2u   /* sec_param is a DFI_STATUS_* */
#define DFI_SECONDARY_VOLATILE 3u /* sec_param is a DFI_VOLATILE_* */

#define DFI_BOOST_ROLE_NONE 0u
#define DFI_BOOST_ROLE_PRIMARY_SELF 1u     /* a status move boosting its user */
#define DFI_BOOST_ROLE_SECONDARY_TARGET 2u /* applied with the secondary roll */
#define DFI_BOOST_ROLE_SELF_AFTER_HIT 3u   /* applied to the user after a hit */

#define DFI_SIDE_CONDITION_TAILWIND 1u
#define DFI_SIDE_CONDITION_REFLECT 2u
#define DFI_SIDE_CONDITION_LIGHT_SCREEN 3u
#define DFI_PSEUDO_WEATHER_TRICK_ROOM 1u

/* Handlers for callbacks that are code in the reference. */
#define DFI_SPECIAL_NONE 0u
#define DFI_SPECIAL_GRASS_KNOT 1u
#define DFI_SPECIAL_WEATHER_BALL 2u
#define DFI_SPECIAL_HURRICANE 3u
#define DFI_SPECIAL_GRASSY_GLIDE 4u
#define DFI_SPECIAL_ELECTRO_SHOT 5u
#define DFI_SPECIAL_FAKE_OUT 6u
#define DFI_SPECIAL_PARTING_SHOT 7u
#define DFI_SPECIAL_PROTECT 8u
#define DFI_SPECIAL_STRUGGLE 9u

/* Type chart codes (the reference's damageTaken values). */
#define DFI_EFFECT_NEUTRAL 0u
#define DFI_EFFECT_SUPER 1u
#define DFI_EFFECT_RESISTED 2u
#define DFI_EFFECT_IMMUNE 3u
#define DFI_IMMUNE_BRN 1u
#define DFI_IMMUNE_FRZ 2u
#define DFI_IMMUNE_PAR 4u
#define DFI_IMMUNE_PRANKSTER 8u

typedef struct dfi_forme_data {
    uint16_t dex_num;
    uint16_t weight_hg;
    uint8_t types[2]; /* second is DFI_CLOSURE_NONE for a single type */
    uint8_t base[DFI_STAT_COUNT];
    uint8_t ability;     /* the set's ability; for a Mega forme its own */
    uint8_t gender_rule; /* DFI_GENDER_RULE_* */
    uint8_t is_mega;
    uint8_t base_forme;
    uint8_t mega_forme; /* DFI_CLOSURE_NONE if the species has no Mega in the closure */
    uint8_t mega_item;  /* the stone, or DFI_CLOSURE_NONE */
    uint8_t set_item;   /* the item of the set in decision 0004 */
    uint8_t set_move_count;
    uint8_t set_moves[4]; /* the moves of the set in decision 0004 */
} dfi_forme_data;

typedef struct dfi_move_data {
    uint8_t type;
    uint8_t category;
    uint8_t base_power;
    uint8_t accuracy; /* 0: never misses */
    uint8_t pp_base;  /* the reference's pp before the Champions rules */
    uint8_t pp_max;   /* Champions maximum PP */
    uint8_t priority; /* biased by DFI_PRIORITY_BIAS */
    uint8_t target_class;
    uint8_t crit_ratio;
    uint8_t flags;
    uint8_t recoil[2]; /* numerator, denominator of damage dealt; 0/0 none */
    uint8_t drain[2];
    uint8_t sec_chance; /* 0: no secondary effect */
    uint8_t sec_kind;
    uint8_t sec_param;
    uint8_t boost_role;
    uint8_t boosts[DFI_STAGE_COUNT]; /* biased by DFI_STAGE_BIAS */
    uint8_t primary_status;
    uint8_t side_condition;
    uint8_t pseudo_weather;
    uint8_t special;
} dfi_move_data;

typedef struct dfi_item_data {
    uint8_t mega_base;  /* forme that can hold it as a Mega Stone, or DFI_CLOSURE_NONE */
    uint8_t mega_forme;
} dfi_item_data;

typedef struct dfi_nature_data {
    uint8_t plus;  /* DFI_STAT_* or DFI_CLOSURE_NONE */
    uint8_t minus;
} dfi_nature_data;

extern const dfi_forme_data dfi_closure_formes[DFI_FORME_COUNT];
extern const dfi_move_data dfi_closure_moves[DFI_MOVE_COUNT];
extern const dfi_item_data dfi_closure_items[DFI_ITEM_COUNT];
extern const dfi_nature_data dfi_closure_natures[DFI_NATURE_COUNT];
/* [defender type][attacking type] -> DFI_EFFECT_* */
extern const uint8_t dfi_closure_type_chart[DFI_TYPE_COUNT][DFI_TYPE_COUNT];
extern const uint8_t dfi_closure_type_immunity[DFI_TYPE_COUNT]; /* DFI_IMMUNE_* bits */

/* SHA-256 of the canonical table bytes (written by the generator). */
#define DFI_CLOSURE_CANONICAL_SIZE 1883u
extern const uint8_t dfi_closure_table_hash[32];
/* Writes the canonical table bytes from the tables above; returns the size
 * (DFI_CLOSURE_CANONICAL_SIZE) or 0 if capacity is too small. */
size_t dfi_closure_canonical_bytes(uint8_t *out, size_t capacity);

#endif
