#include "data/closure_tables.h"

/* GENERATED by tools/datagen/gen_closure.py -- do not edit. Showdown b2cb775b0616115b775534eaeff50300e1fc81fc. */

const dfi_forme_data dfi_closure_formes[DFI_FORME_COUNT] = {
    /* Rillaboom -- data/pokedex.ts:15678-15692 */
    {812u, 900u, {9u, 255u}, {100u, 125u, 90u, 60u, 70u, 85u}, 0u, 0u, 0u, 0u, 255u, 255u, 0u, 4u, {0u, 1u, 2u, 3u}},
    /* Staraptor -- data/pokedex.ts:7423-7437 */
    {398u, 249u, {12u, 7u}, {85u, 120u, 70u, 50u, 60u, 100u}, 1u, 0u, 0u, 1u, 2u, 1u, 1u, 4u, {4u, 5u, 6u, 7u}},
    /* Staraptor-Mega -- data/pokedex.ts:7438-7452 */
    {398u, 500u, {5u, 7u}, {85u, 140u, 100u, 60u, 90u, 110u}, 12u, 0u, 1u, 1u, 255u, 1u, 1u, 0u, {0u, 0u, 0u, 0u}},
    /* Milotic -- data/pokedex.ts:6502-6515 */
    {350u, 1620u, {17u, 255u}, {95u, 60u, 79u, 100u, 125u, 81u}, 2u, 0u, 0u, 3u, 255u, 255u, 2u, 4u, {8u, 9u, 10u, 11u}},
    /* Ceruledge -- data/pokedex.ts:18122-18135 */
    {937u, 620u, {6u, 8u}, {75u, 125u, 80u, 60u, 100u, 85u}, 3u, 0u, 0u, 4u, 255u, 255u, 3u, 4u, {12u, 13u, 14u, 7u}},
    /* Raichu -- data/pokedex.ts:804-819 */
    {26u, 300u, {3u, 255u}, {60u, 90u, 55u, 90u, 80u, 110u}, 4u, 0u, 0u, 5u, 6u, 4u, 4u, 4u, {15u, 16u, 2u, 7u}},
    /* Raichu-Mega-Y -- data/pokedex.ts:852-866 */
    {26u, 260u, {3u, 255u}, {60u, 100u, 55u, 160u, 80u, 130u}, 13u, 0u, 1u, 5u, 255u, 4u, 4u, 0u, {0u, 0u, 0u, 0u}},
    /* Gholdengo -- data/pokedex.ts:19101-19115 */
    {1000u, 300u, {16u, 8u}, {87u, 60u, 95u, 133u, 91u, 84u}, 5u, 3u, 0u, 7u, 255u, 255u, 5u, 4u, {17u, 18u, 19u, 7u}},
    /* Politoed -- data/pokedex.ts:3980-3993 */
    {186u, 339u, {17u, 255u}, {90u, 75u, 75u, 90u, 100u, 70u}, 6u, 0u, 0u, 8u, 255u, 255u, 6u, 4u, {20u, 8u, 10u, 7u}},
    /* Golisopod -- data/pokedex.ts:14516-14530 */
    {768u, 1080u, {0u, 17u}, {75u, 125u, 140u, 60u, 90u, 40u}, 7u, 0u, 0u, 9u, 10u, 7u, 7u, 4u, {21u, 22u, 23u, 7u}},
    /* Golisopod-Mega -- data/pokedex.ts:14531-14545 */
    {768u, 1480u, {0u, 16u}, {75u, 150u, 175u, 70u, 120u, 40u}, 14u, 0u, 1u, 9u, 255u, 7u, 7u, 0u, {0u, 0u, 0u, 0u}},
    /* Archaludon -- data/pokedex.ts:19501-19514 */
    {1018u, 600u, {16u, 2u}, {90u, 105u, 130u, 125u, 65u, 85u}, 8u, 0u, 0u, 11u, 255u, 255u, 8u, 4u, {24u, 25u, 26u, 7u}},
    /* Farigiraf -- data/pokedex.ts:18798-18811 */
    {981u, 1600u, {12u, 14u}, {120u, 90u, 70u, 110u, 70u, 60u}, 9u, 0u, 0u, 12u, 255u, 255u, 2u, 4u, {27u, 28u, 29u, 7u}},
    /* Charizard -- data/pokedex.ts:106-122 */
    {6u, 905u, {6u, 7u}, {78u, 84u, 78u, 109u, 85u, 100u}, 10u, 0u, 0u, 13u, 14u, 9u, 9u, 4u, {30u, 20u, 31u, 7u}},
    /* Charizard-Mega-Y -- data/pokedex.ts:138-152 */
    {6u, 1005u, {6u, 7u}, {78u, 104u, 78u, 159u, 115u, 100u}, 15u, 0u, 1u, 13u, 255u, 9u, 9u, 0u, {0u, 0u, 0u, 0u}},
    /* Grimmsnarl -- data/pokedex.ts:16636-16650 */
    {861u, 610u, {1u, 4u}, {95u, 120u, 65u, 95u, 75u, 60u}, 11u, 1u, 0u, 15u, 255u, 255u, 10u, 4u, {32u, 33u, 34u, 35u}},
};

const dfi_move_data dfi_closure_moves[DFI_MOVE_COUNT] = {
    /* Wood Hammer -- data/moves.ts:21018-21031 */
    {9u, 0u, 120u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Grassy Glide -- data/moves.ts:7655-7672 */
    {9u, 0u, 55u, 100u, 20u, 20u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 4u},
    /* Fake Out -- data/moves.ts:5087-5109, data/mods/champions/moves.ts:354-361 */
    {12u, 0u, 40u, 100u, 10u, 12u, 11u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 100u, 3u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 6u},
    /* High Horsepower -- data/moves.ts:8885-8897 */
    {10u, 0u, 95u, 95u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Brave Bird -- data/moves.ts:1775-1788 */
    {7u, 0u, 120u, 100u, 15u, 16u, 8u, 2u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Close Combat -- data/moves.ts:2571-2589 */
    {5u, 0u, 120u, 100u, 5u, 8u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 3u, {6u, 5u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Tailwind -- data/moves.ts:18875-18914 */
    {7u, 2u, 0u, 0u, 15u, 16u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 1u, 0u, 0u},
    /* Protect -- data/moves.ts:13961-14005, data/mods/champions/moves.ts:765-768 */
    {12u, 2u, 0u, 0u, 5u, 8u, 12u, 6u, 1u, 8u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 8u},
    /* Muddy Water -- data/moves.ts:12398-12416 */
    {17u, 1u, 90u, 85u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 30u, 1u, 0u, 2u, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u, 0u, 0u},
    /* Coil -- data/moves.ts:2606-2624 */
    {13u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {7u, 7u, 6u, 6u, 6u, 7u, 6u}, 0u, 0u, 0u, 0u},
    /* Ice Beam -- data/moves.ts:9302-9318 */
    {11u, 1u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 2u, 2u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Hypnosis -- data/moves.ts:9220-9234 */
    {14u, 2u, 0u, 60u, 20u, 20u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 4u, 0u, 0u, 0u},
    /* Bitter Blade -- data/moves.ts:1368-1380 */
    {6u, 0u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {1u, 2u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Shadow Sneak -- data/moves.ts:16115-16127 */
    {8u, 0u, 40u, 100u, 30u, 20u, 9u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Swords Dance -- data/moves.ts:18691-18707 */
    {12u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {8u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Zap Cannon -- data/moves.ts:21163-21179 */
    {3u, 1u, 120u, 50u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 100u, 2u, 3u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Focus Blast -- data/moves.ts:5952-5970 */
    {5u, 1u, 120u, 70u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Make It Rain -- data/moves.ts:10934-10951, data/mods/champions/moves.ts:609-617 */
    {16u, 1u, 120u, 95u, 5u, 8u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 3u, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Shadow Ball -- data/moves.ts:16020-16038 */
    {8u, 1u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 20u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Nasty Plot -- data/moves.ts:12548-12564 */
    {1u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {6u, 6u, 8u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Weather Ball -- data/moves.ts:20692-20745 */
    {12u, 1u, 50u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 2u},
    /* Leech Life -- data/moves.ts:10188-10201 */
    {0u, 0u, 80u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {1u, 2u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Iron Head -- data/moves.ts:9722-9738, data/mods/champions/moves.ts:545-551 */
    {16u, 0u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 20u, 3u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Drill Run -- data/moves.ts:4280-4293 */
    {10u, 0u, 80u, 95u, 10u, 12u, 8u, 1u, 2u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Dragon Pulse -- data/moves.ts:4163-4175 */
    {2u, 1u, 85u, 100u, 10u, 12u, 8u, 2u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Electro Shot -- data/moves.ts:4630-4659 */
    {3u, 1u, 130u, 100u, 10u, 12u, 8u, 1u, 1u, 6u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 5u},
    /* Snarl -- data/moves.ts:17085-17103 */
    {1u, 1u, 55u, 95u, 15u, 16u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 100u, 1u, 0u, 2u, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Psychic -- data/moves.ts:14041-14059 */
    {14u, 1u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Grass Knot -- data/moves.ts:7537-7577 */
    {9u, 1u, 0u, 100u, 20u, 20u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 1u},
    /* Trick Room -- data/moves.ts:19940-19980 */
    {14u, 2u, 0u, 0u, 5u, 8u, 1u, 9u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 1u, 0u},
    /* Heat Wave -- data/moves.ts:8516-8532 */
    {6u, 1u, 95u, 90u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 2u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Hurricane -- data/moves.ts:9026-9054 */
    {7u, 1u, 110u, 70u, 10u, 12u, 8u, 2u, 1u, 2u, {0u, 0u}, {0u, 0u}, 30u, 3u, 2u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 3u},
    /* Spirit Break -- data/moves.ts:17602-17619 */
    {4u, 0u, 75u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 100u, 1u, 0u, 2u, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Reflect -- data/moves.ts:14842-14882 */
    {14u, 2u, 0u, 0u, 20u, 20u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 2u, 0u, 0u},
    /* Light Screen -- data/moves.ts:10315-10355 */
    {14u, 2u, 0u, 0u, 30u, 20u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 3u, 0u, 0u},
    /* Parting Shot -- data/moves.ts:13165-13185 */
    {1u, 2u, 0u, 100u, 20u, 20u, 8u, 1u, 1u, 18u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 7u},
    /* Struggle -- data/moves.ts:18211-18232 */
    {12u, 0u, 50u, 0u, 1u, 1u, 8u, 10u, 1u, 99u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 9u},
};

const dfi_item_data dfi_closure_items[DFI_ITEM_COUNT] = {
    /* Miracle Seed -- data/items.ts:4135-4149 */
    {255u, 255u},
    /* Staraptite -- data/items.ts:5977-5988, data/mods/champions/items.ts:898-901 */
    {1u, 2u},
    /* Sitrus Berry -- data/items.ts:5744-5765 */
    {255u, 255u},
    /* Grassy Seed -- data/items.ts:2595-2617 */
    {255u, 255u},
    /* Raichunite Y -- data/items.ts:5047-5058, data/mods/champions/items.ts:766-769 */
    {5u, 6u},
    /* Life Orb -- data/items.ts:3404-3420 */
    {255u, 255u},
    /* Mystic Water -- data/items.ts:4254-4268 */
    {255u, 255u},
    /* Golisopite -- data/items.ts:2529-2540, data/mods/champions/items.ts:402-405 */
    {9u, 10u},
    /* Leftovers -- data/items.ts:3338-3351 */
    {255u, 255u},
    /* Charizardite Y -- data/items.ts:800-811, data/mods/champions/items.ts:142-145 */
    {13u, 14u},
    /* Light Clay -- data/items.ts:3444-3453 */
    {255u, 255u},
};

/* Abilities carry no table data. Provenance:
 *   grassysurge -- data/abilities.ts:1707-1715
 *   intimidate -- data/abilities.ts:2193-2212
 *   competitive -- data/abilities.ts:645-665
 *   flashfire -- data/abilities.ts:1341-1381
 *   lightningrod -- data/abilities.ts:2343-2367
 *   goodasgold -- data/abilities.ts:1630-1641
 *   drizzle -- data/abilities.ts:1078-1087
 *   emergencyexit -- data/abilities.ts:1250-1265, data/mods/champions/abilities.ts:22-29
 *   stamina -- data/abilities.ts:4514-4522
 *   armortail -- data/abilities.ts:215-233
 *   blaze -- data/abilities.ts:460-479
 *   prankster -- data/abilities.ts:3425-3436
 *   contrary -- data/abilities.ts:678-690
 *   noguard -- data/abilities.ts:2970-2985
 *   toughclaws -- data/abilities.ts:5066-5077
 *   drought -- data/abilities.ts:1088-1097
 */

const dfi_nature_data dfi_closure_natures[DFI_NATURE_COUNT] = {
    {1u, 3u}, /* adamant */
    {255u, 255u}, /* bashful */
    {2u, 1u}, /* bold */
    {1u, 5u}, /* brave */
    {4u, 1u}, /* calm */
    {4u, 3u}, /* careful */
    {255u, 255u}, /* docile */
    {4u, 2u}, /* gentle */
    {255u, 255u}, /* hardy */
    {5u, 2u}, /* hasty */
    {2u, 3u}, /* impish */
    {5u, 3u}, /* jolly */
    {2u, 4u}, /* lax */
    {1u, 2u}, /* lonely */
    {3u, 2u}, /* mild */
    {3u, 1u}, /* modest */
    {5u, 4u}, /* naive */
    {1u, 4u}, /* naughty */
    {3u, 5u}, /* quiet */
    {255u, 255u}, /* quirky */
    {3u, 4u}, /* rash */
    {2u, 5u}, /* relaxed */
    {4u, 5u}, /* sassy */
    {255u, 255u}, /* serious */
    {5u, 1u}, /* timid */
};

/* data/typechart.ts: rows are defender types, columns attacking types. */
const uint8_t dfi_closure_type_chart[DFI_TYPE_COUNT][DFI_TYPE_COUNT] = {
    {0u, 0u, 0u, 0u, 0u, 2u, 1u, 1u, 0u, 2u, 2u, 0u, 0u, 0u, 0u, 1u, 0u, 0u}, /* Bug */
    {1u, 2u, 0u, 0u, 1u, 1u, 0u, 0u, 2u, 0u, 0u, 0u, 0u, 0u, 3u, 0u, 0u, 0u}, /* Dark */
    {0u, 0u, 1u, 2u, 1u, 0u, 2u, 0u, 0u, 2u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 2u}, /* Dragon */
    {0u, 0u, 0u, 2u, 0u, 0u, 0u, 2u, 0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 2u, 0u}, /* Electric */
    {2u, 2u, 3u, 0u, 0u, 2u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 1u, 0u, 0u, 1u, 0u}, /* Fairy */
    {2u, 2u, 0u, 0u, 1u, 0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 1u, 2u, 0u, 0u}, /* Fighting */
    {2u, 0u, 0u, 0u, 2u, 0u, 2u, 0u, 0u, 2u, 1u, 2u, 0u, 0u, 0u, 1u, 2u, 1u}, /* Fire */
    {2u, 0u, 0u, 1u, 0u, 2u, 0u, 0u, 0u, 2u, 3u, 1u, 0u, 0u, 0u, 1u, 0u, 0u}, /* Flying */
    {2u, 1u, 0u, 0u, 0u, 3u, 0u, 0u, 1u, 0u, 0u, 0u, 3u, 2u, 0u, 0u, 0u, 0u}, /* Ghost */
    {1u, 0u, 0u, 2u, 0u, 0u, 1u, 1u, 0u, 2u, 2u, 1u, 0u, 1u, 0u, 0u, 0u, 2u}, /* Grass */
    {0u, 0u, 0u, 3u, 0u, 0u, 0u, 0u, 0u, 1u, 0u, 1u, 0u, 2u, 0u, 2u, 0u, 1u}, /* Ground */
    {0u, 0u, 0u, 0u, 0u, 1u, 1u, 0u, 0u, 0u, 0u, 2u, 0u, 0u, 0u, 1u, 1u, 0u}, /* Ice */
    {0u, 0u, 0u, 0u, 0u, 1u, 0u, 0u, 3u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u}, /* Normal */
    {2u, 0u, 0u, 0u, 2u, 2u, 0u, 0u, 0u, 2u, 1u, 0u, 0u, 2u, 1u, 0u, 0u, 0u}, /* Poison */
    {1u, 1u, 0u, 0u, 0u, 2u, 0u, 0u, 1u, 0u, 0u, 0u, 0u, 0u, 2u, 0u, 0u, 0u}, /* Psychic */
    {0u, 0u, 0u, 0u, 0u, 1u, 2u, 2u, 0u, 1u, 1u, 0u, 2u, 2u, 0u, 0u, 1u, 1u}, /* Rock */
    {2u, 0u, 2u, 0u, 2u, 1u, 1u, 2u, 0u, 2u, 1u, 2u, 2u, 3u, 2u, 2u, 2u, 0u}, /* Steel */
    {0u, 0u, 0u, 1u, 0u, 0u, 2u, 0u, 0u, 1u, 0u, 2u, 0u, 0u, 0u, 0u, 2u, 2u}, /* Water */
};

const uint8_t dfi_closure_type_immunity[DFI_TYPE_COUNT] = {0u, 8u, 0u, 4u, 0u, 0u, 1u, 0u, 0u, 0u, 0u, 2u, 0u, 0u, 0u, 0u, 0u, 0u};

const uint8_t dfi_closure_table_hash[32] = {
    0x86u, 0xcau, 0x9du, 0x9fu, 0x54u, 0x80u, 0x42u, 0x47u,
    0x3cu, 0x09u, 0x80u, 0xc4u, 0x96u, 0xe9u, 0xbdu, 0x6bu,
    0xebu, 0xbdu, 0xe4u, 0xb3u, 0xdfu, 0x0eu, 0xd1u, 0x0au,
    0x9bu, 0xa2u, 0x5au, 0xa6u, 0x23u, 0x16u, 0xefu, 0x5cu,
};

static size_t dfi_put_u16(uint8_t *out, size_t n, uint32_t v)
{
    out[n] = (uint8_t)(v & 0xFFu);             /* wide-operands-reviewed */
    out[n + 1u] = (uint8_t)((v >> 8u) & 0xFFu); /* wide-operands-reviewed */
    return n + 2u;
}

size_t dfi_closure_canonical_bytes(uint8_t *out, size_t capacity)
{
    size_t n = 0u;
    if (capacity < DFI_CLOSURE_CANONICAL_SIZE) {
        return 0u;
    }
    n = dfi_put_u16(out, n, DFI_FORME_COUNT);
    n = dfi_put_u16(out, n, DFI_MOVE_COUNT);
    n = dfi_put_u16(out, n, DFI_ITEM_COUNT);
    n = dfi_put_u16(out, n, DFI_ABILITY_COUNT);
    n = dfi_put_u16(out, n, DFI_TYPE_COUNT);
    n = dfi_put_u16(out, n, DFI_NATURE_COUNT);
    for (uint32_t i = 0u; i < DFI_FORME_COUNT; ++i) {
        const dfi_forme_data *f = &dfi_closure_formes[i];
        n = dfi_put_u16(out, n, f->dex_num);
        out[n++] = f->types[0];
        out[n++] = f->types[1];
        for (uint32_t k = 0u; k < DFI_STAT_COUNT; ++k) {
            out[n++] = f->base[k];
        }
        n = dfi_put_u16(out, n, f->weight_hg);
        out[n++] = f->ability;
        out[n++] = f->gender_rule;
        out[n++] = f->is_mega;
        out[n++] = f->base_forme;
        out[n++] = f->mega_forme;
        out[n++] = f->mega_item;
        out[n++] = f->set_item;
        out[n++] = f->set_move_count;
        for (uint32_t k = 0u; k < 4u; ++k) {
            out[n++] = f->set_moves[k];
        }
    }
    for (uint32_t i = 0u; i < DFI_MOVE_COUNT; ++i) {
        const dfi_move_data *m = &dfi_closure_moves[i];
        out[n++] = m->type;
        out[n++] = m->category;
        out[n++] = m->base_power;
        out[n++] = m->accuracy;
        out[n++] = m->pp_base;
        out[n++] = m->pp_max;
        out[n++] = m->priority;
        out[n++] = m->target_class;
        out[n++] = m->crit_ratio;
        out[n++] = m->flags;
        out[n++] = m->recoil[0];
        out[n++] = m->recoil[1];
        out[n++] = m->drain[0];
        out[n++] = m->drain[1];
        out[n++] = m->sec_chance;
        out[n++] = m->sec_kind;
        out[n++] = m->sec_param;
        out[n++] = m->boost_role;
        for (uint32_t k = 0u; k < DFI_STAGE_COUNT; ++k) {
            out[n++] = m->boosts[k];
        }
        out[n++] = m->primary_status;
        out[n++] = m->side_condition;
        out[n++] = m->pseudo_weather;
        out[n++] = m->special;
    }
    for (uint32_t i = 0u; i < DFI_ITEM_COUNT; ++i) {
        out[n++] = dfi_closure_items[i].mega_base;
        out[n++] = dfi_closure_items[i].mega_forme;
    }
    for (uint32_t d = 0u; d < DFI_TYPE_COUNT; ++d) {
        for (uint32_t a = 0u; a < DFI_TYPE_COUNT; ++a) {
            out[n++] = dfi_closure_type_chart[d][a];
        }
    }
    for (uint32_t i = 0u; i < DFI_TYPE_COUNT; ++i) {
        out[n++] = dfi_closure_type_immunity[i];
    }
    for (uint32_t i = 0u; i < DFI_NATURE_COUNT; ++i) {
        out[n++] = dfi_closure_natures[i].plus;
        out[n++] = dfi_closure_natures[i].minus;
    }
    return n;
}
