#ifndef DUOFORGE_DATA_EXTENDED_TABLES_H
#define DUOFORGE_DATA_EXTENDED_TABLES_H
/*
 * GENERATED by tools/datagen/gen_closure.py --team-c -- do not edit.
 *
 * The extended tables of decision 0009: the closure tables followed by
 * Team C, read from Pokemon Showdown b2cb775b0616115b775534eaeff50300e1fc81fc (the input files of
 * closure_tables.h). Every id below a closure count (DFI_FORME_COUNT,
 * DFI_MOVE_COUNT, DFI_ITEM_COUNT, DFI_ABILITY_COUNT) is the closure's and
 * its row equals the closure row; the only extension inside that prefix is
 * DFI_IMMUNE_PSN. Team C ids follow. Natures and the type chart are the
 * closure's.
 *
 * Data only. An id names a record; every effect needs a typed handler in C
 * and an entry in the support manifest before a battle may use it.
 */
#include <stddef.h>
#include <stdint.h>

#include "data/closure_tables.h"

/* ---- Team C formes (appended; base formes are selectable) ---- */
#define DFI_FORME_SNEASLER 16u
#define DFI_FORME_INCINEROAR 17u
#define DFI_FORME_SALAMENCE 18u
#define DFI_FORME_SALAMENCEMEGA 19u
#define DFI_FORME_INDEEDEEF 20u
#define DFI_FORME_KINGAMBIT 21u
#define DFI_FORME_BASCULEGION 22u
#define DFI_EXT_FORME_COUNT 23u

/* ---- Team C moves (appended after Struggle) ---- */
#define DFI_MOVE_DIRECLAW 37u
#define DFI_MOVE_FLAREBLITZ 38u
#define DFI_MOVE_DARKESTLARIAT 39u
#define DFI_MOVE_HYPERVOICE 40u
#define DFI_MOVE_DRACOMETEOR 41u
#define DFI_MOVE_FOLLOWME 42u
#define DFI_MOVE_HELPINGHAND 43u
#define DFI_MOVE_KOWTOWCLEAVE 44u
#define DFI_MOVE_SUCKERPUNCH 45u
#define DFI_MOVE_LASTRESPECTS 46u
#define DFI_MOVE_WAVECRASH 47u
#define DFI_MOVE_AQUAJET 48u
#define DFI_MOVE_FLIPTURN 49u
#define DFI_EXT_MOVE_COUNT 50u

/* ---- Team C abilities ---- */
#define DFI_ABILITY_UNBURDEN 16u
#define DFI_ABILITY_PSYCHICSURGE 17u
#define DFI_ABILITY_DEFIANT 18u
#define DFI_ABILITY_ADAPTABILITY 19u
#define DFI_ABILITY_AERILATE 20u
#define DFI_EXT_ABILITY_COUNT 21u

/* ---- Team C items ---- */
#define DFI_ITEM_WHITEHERB 11u
#define DFI_ITEM_SALAMENCITE 12u
#define DFI_ITEM_ROCKYHELMET 13u
#define DFI_ITEM_CHOPLEBERRY 14u
#define DFI_ITEM_CHOICESCARF 15u
#define DFI_EXT_ITEM_COUNT 16u

/* ---- encodings new in the extended tables (decision 0009 section 3.3) ---- */
#define DFI_STATUS_PSN 5u
#define DFI_MOVE_FLAG_DEFROST 128u
#define DFI_SECONDARY_STATUS_PICK 4u /* on a hit: sample(['psn', 'par', 'slp']), then trySetStatus */
#define DFI_SPECIAL_DARKEST_LARIAT 10u
#define DFI_SPECIAL_LAST_RESPECTS 11u
#define DFI_SPECIAL_SUCKER_PUNCH 12u
#define DFI_SPECIAL_HELPING_HAND 13u
#define DFI_SPECIAL_FOLLOW_ME 14u
#define DFI_IMMUNE_PSN 16u

extern const dfi_forme_data dfi_ext_formes[DFI_EXT_FORME_COUNT];
extern const dfi_move_data dfi_ext_moves[DFI_EXT_MOVE_COUNT];
extern const dfi_item_data dfi_ext_items[DFI_EXT_ITEM_COUNT];
extern const uint8_t dfi_ext_type_immunity[DFI_TYPE_COUNT]; /* DFI_IMMUNE_* bits */

/* SHA-256 of the extended canonical bytes (written by the generator). */
#define DFI_EXT_CANONICAL_SIZE 2438u
extern const uint8_t dfi_ext_table_hash[32];
/* The canonical bytes of the closure layout over the first `formes`, `moves`,
 * `items` and `abilities` rows of the tables above, with every immunity byte
 * masked by `immunity_mask`; natures and the type chart are the closure's.
 * Returns the size, or 0 if a count exceeds its table or capacity is too
 * small. With the closure counts and the closure's immunity bits these are
 * exactly the closure's canonical bytes. */
size_t dfi_ext_canonical_bytes_of(uint8_t *out, size_t capacity, uint32_t formes, uint32_t moves, uint32_t items,
                                  uint32_t abilities, uint32_t immunity_mask);
/* The extended canonical bytes: every row, every immunity bit. */
size_t dfi_ext_canonical_bytes(uint8_t *out, size_t capacity);

#endif
