#include "data/extended_tables.h"

/* GENERATED by tools/datagen/gen_closure.py --team-c -- do not edit. Showdown b2cb775b0616115b775534eaeff50300e1fc81fc. */

const dfi_forme_data dfi_ext_formes[DFI_EXT_FORME_COUNT] = {
    /* Rillaboom -- data/pokedex.ts:15678-15692 */
    {812u, 900u, {9u, 255u}, {100u, 125u, 90u, 60u, 70u, 85u}, 0u, 0u, 0u, 0u, 255u, 255u, 0u, 4u, {0u, 1u, 2u, 3u}},
    /* Staraptor -- data/pokedex.ts:7423-7437 */
    {398u, 249u, {12u, 7u}, {85u, 120u, 70u, 50u, 60u, 100u}, 1u, 0u, 0u, 1u, 2u, 1u, 1u, 4u, {4u, 5u, 6u, 7u}},
    /* Staraptor-Mega -- data/pokedex.ts:7438-7452 */
    {398u, 500u, {5u, 7u}, {85u, 140u, 100u, 60u, 90u, 110u}, 12u, 0u, 1u, 1u, 255u, 1u, 1u, 0u, {0u, 0u, 0u, 0u}},
    /* Milotic -- data/pokedex.ts:6502-6515 */
    {350u, 1620u, {17u, 255u}, {95u, 60u, 79u, 100u, 125u, 81u}, 2u, 0u, 0u, 3u, 255u, 255u, 2u, 4u, {8u, 9u, 10u, 11u}},
    /* Ceruledge -- data/pokedex.ts:18122-18135 */
    {937u, 620u, {6u, 8u}, {75u, 125u, 80u, 60u, 100u, 85u}, 3u, 0u, 0u, 4u, 255u, 255u, 3u, 4u, {12u, 13u, 14u, 7u}},
    /* Raichu -- data/pokedex.ts:804-819 */
    {26u, 300u, {3u, 255u}, {60u, 90u, 55u, 90u, 80u, 110u}, 4u, 0u, 0u, 5u, 6u, 4u, 4u, 4u, {15u, 16u, 2u, 7u}},
    /* Raichu-Mega-Y -- data/pokedex.ts:852-866 */
    {26u, 260u, {3u, 255u}, {60u, 100u, 55u, 160u, 80u, 130u}, 13u, 0u, 1u, 5u, 255u, 4u, 4u, 0u, {0u, 0u, 0u, 0u}},
    /* Gholdengo -- data/pokedex.ts:19101-19115 */
    {1000u, 300u, {16u, 8u}, {87u, 60u, 95u, 133u, 91u, 84u}, 5u, 3u, 0u, 7u, 255u, 255u, 5u, 4u, {17u, 18u, 19u, 7u}},
    /* Politoed -- data/pokedex.ts:3980-3993 */
    {186u, 339u, {17u, 255u}, {90u, 75u, 75u, 90u, 100u, 70u}, 6u, 0u, 0u, 8u, 255u, 255u, 6u, 4u, {20u, 8u, 10u, 7u}},
    /* Golisopod -- data/pokedex.ts:14516-14530 */
    {768u, 1080u, {0u, 17u}, {75u, 125u, 140u, 60u, 90u, 40u}, 7u, 0u, 0u, 9u, 10u, 7u, 7u, 4u, {21u, 22u, 23u, 7u}},
    /* Golisopod-Mega -- data/pokedex.ts:14531-14545 */
    {768u, 1480u, {0u, 16u}, {75u, 150u, 175u, 70u, 120u, 40u}, 14u, 0u, 1u, 9u, 255u, 7u, 7u, 0u, {0u, 0u, 0u, 0u}},
    /* Archaludon -- data/pokedex.ts:19501-19514 */
    {1018u, 600u, {16u, 2u}, {90u, 105u, 130u, 125u, 65u, 85u}, 8u, 0u, 0u, 11u, 255u, 255u, 8u, 4u, {24u, 25u, 26u, 7u}},
    /* Farigiraf -- data/pokedex.ts:18798-18811 */
    {981u, 1600u, {12u, 14u}, {120u, 90u, 70u, 110u, 70u, 60u}, 9u, 0u, 0u, 12u, 255u, 255u, 2u, 4u, {27u, 28u, 29u, 7u}},
    /* Charizard -- data/pokedex.ts:106-122 */
    {6u, 905u, {6u, 7u}, {78u, 84u, 78u, 109u, 85u, 100u}, 10u, 0u, 0u, 13u, 14u, 9u, 9u, 4u, {30u, 20u, 31u, 7u}},
    /* Charizard-Mega-Y -- data/pokedex.ts:138-152 */
    {6u, 1005u, {6u, 7u}, {78u, 104u, 78u, 159u, 115u, 100u}, 15u, 0u, 1u, 13u, 255u, 9u, 9u, 0u, {0u, 0u, 0u, 0u}},
    /* Grimmsnarl -- data/pokedex.ts:16636-16650 */
    {861u, 610u, {1u, 4u}, {95u, 120u, 65u, 95u, 75u, 60u}, 11u, 1u, 0u, 15u, 255u, 255u, 10u, 4u, {32u, 33u, 34u, 35u}},
    /* Sneasler -- data/pokedex.ts:17573-17587 */
    {903u, 430u, {5u, 13u}, {80u, 130u, 60u, 40u, 80u, 120u}, 16u, 0u, 0u, 16u, 255u, 255u, 11u, 4u, {5u, 37u, 7u, 2u}},
    /* Incineroar -- data/pokedex.ts:13756-13769 */
    {727u, 830u, {6u, 1u}, {95u, 115u, 90u, 80u, 90u, 60u}, 1u, 0u, 0u, 17u, 255u, 255u, 2u, 4u, {2u, 38u, 35u, 39u}},
    /* Salamence -- data/pokedex.ts:6920-6934 */
    {373u, 1026u, {2u, 7u}, {95u, 135u, 80u, 110u, 80u, 100u}, 1u, 0u, 0u, 18u, 19u, 12u, 12u, 4u, {7u, 40u, 41u, 6u}},
    /* Salamence-Mega -- data/pokedex.ts:6935-6948 */
    {373u, 1126u, {2u, 7u}, {95u, 145u, 130u, 120u, 90u, 120u}, 20u, 0u, 1u, 18u, 255u, 12u, 12u, 0u, {0u, 0u, 0u, 0u}},
    /* Indeedee-F -- data/pokedex.ts:16969-16982 */
    {876u, 280u, {14u, 12u}, {70u, 55u, 65u, 95u, 105u, 85u}, 17u, 2u, 0u, 20u, 255u, 255u, 13u, 4u, {42u, 29u, 43u, 27u}},
    /* Kingambit -- data/pokedex.ts:18845-18858 */
    {983u, 1200u, {1u, 16u}, {100u, 135u, 120u, 60u, 85u, 50u}, 18u, 0u, 0u, 21u, 255u, 255u, 14u, 4u, {44u, 45u, 22u, 7u}},
    /* Basculegion -- data/pokedex.ts:17538-17555 */
    {902u, 1100u, {17u, 8u}, {120u, 112u, 65u, 80u, 75u, 78u}, 19u, 1u, 0u, 22u, 255u, 255u, 15u, 4u, {47u, 46u, 49u, 48u}},
};

const dfi_move_data dfi_ext_moves[DFI_EXT_MOVE_COUNT] = {
    /* Wood Hammer -- data/moves.ts:21018-21031 */
    {9u, 0u, 120u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Grassy Glide -- data/moves.ts:7655-7672 */
    {9u, 0u, 55u, 100u, 20u, 20u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 4u},
    /* Fake Out -- data/moves.ts:5087-5109, data/mods/champions/moves.ts:354-361 */
    {12u, 0u, 40u, 100u, 10u, 12u, 11u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 100u, 3u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 6u},
    /* High Horsepower -- data/moves.ts:8885-8897 */
    {10u, 0u, 95u, 95u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Brave Bird -- data/moves.ts:1775-1788 */
    {7u, 0u, 120u, 100u, 15u, 16u, 8u, 2u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Close Combat -- data/moves.ts:2571-2589 */
    {5u, 0u, 120u, 100u, 5u, 8u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 3u, {6u, 5u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Tailwind -- data/moves.ts:18875-18914 */
    {7u, 2u, 0u, 0u, 15u, 16u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 1u, 0u, 0u},
    /* Protect -- data/moves.ts:13961-14005, data/mods/champions/moves.ts:765-768 */
    {12u, 2u, 0u, 0u, 5u, 8u, 12u, 6u, 1u, 8u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 8u},
    /* Muddy Water -- data/moves.ts:12398-12416 */
    {17u, 1u, 90u, 85u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 30u, 1u, 0u, 2u, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u, 0u, 0u},
    /* Coil -- data/moves.ts:2606-2624 */
    {13u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {7u, 7u, 6u, 6u, 6u, 7u, 6u}, 0u, 0u, 0u, 0u},
    /* Ice Beam -- data/moves.ts:9302-9318 */
    {11u, 1u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 2u, 2u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Hypnosis -- data/moves.ts:9220-9234 */
    {14u, 2u, 0u, 60u, 20u, 20u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 4u, 0u, 0u, 0u},
    /* Bitter Blade -- data/moves.ts:1368-1380 */
    {6u, 0u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {1u, 2u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Shadow Sneak -- data/moves.ts:16115-16127 */
    {8u, 0u, 40u, 100u, 30u, 20u, 9u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Swords Dance -- data/moves.ts:18691-18707 */
    {12u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {8u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Zap Cannon -- data/moves.ts:21163-21179 */
    {3u, 1u, 120u, 50u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 100u, 2u, 3u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Focus Blast -- data/moves.ts:5952-5970 */
    {5u, 1u, 120u, 70u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Make It Rain -- data/moves.ts:10934-10951, data/mods/champions/moves.ts:609-617 */
    {16u, 1u, 120u, 95u, 5u, 8u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 3u, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Shadow Ball -- data/moves.ts:16020-16038 */
    {8u, 1u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 20u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Nasty Plot -- data/moves.ts:12548-12564 */
    {1u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {6u, 6u, 8u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Weather Ball -- data/moves.ts:20692-20745 */
    {12u, 1u, 50u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 2u},
    /* Leech Life -- data/moves.ts:10188-10201 */
    {0u, 0u, 80u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {1u, 2u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Iron Head -- data/moves.ts:9722-9738, data/mods/champions/moves.ts:545-551 */
    {16u, 0u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 20u, 3u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Drill Run -- data/moves.ts:4280-4293 */
    {10u, 0u, 80u, 95u, 10u, 12u, 8u, 1u, 2u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Dragon Pulse -- data/moves.ts:4163-4175 */
    {2u, 1u, 85u, 100u, 10u, 12u, 8u, 2u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Electro Shot -- data/moves.ts:4630-4659 */
    {3u, 1u, 130u, 100u, 10u, 12u, 8u, 1u, 1u, 6u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 5u},
    /* Snarl -- data/moves.ts:17085-17103 */
    {1u, 1u, 55u, 95u, 15u, 16u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 100u, 1u, 0u, 2u, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Psychic -- data/moves.ts:14041-14059 */
    {14u, 1u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Grass Knot -- data/moves.ts:7537-7577 */
    {9u, 1u, 0u, 100u, 20u, 20u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 1u},
    /* Trick Room -- data/moves.ts:19940-19980 */
    {14u, 2u, 0u, 0u, 5u, 8u, 1u, 9u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 1u, 0u},
    /* Heat Wave -- data/moves.ts:8516-8532 */
    {6u, 1u, 95u, 90u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 2u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Hurricane -- data/moves.ts:9026-9054 */
    {7u, 1u, 110u, 70u, 10u, 12u, 8u, 2u, 1u, 2u, {0u, 0u}, {0u, 0u}, 30u, 3u, 2u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 3u},
    /* Spirit Break -- data/moves.ts:17602-17619 */
    {4u, 0u, 75u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 100u, 1u, 0u, 2u, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Reflect -- data/moves.ts:14842-14882 */
    {14u, 2u, 0u, 0u, 20u, 20u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 2u, 0u, 0u},
    /* Light Screen -- data/moves.ts:10315-10355 */
    {14u, 2u, 0u, 0u, 30u, 20u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 3u, 0u, 0u},
    /* Parting Shot -- data/moves.ts:13165-13185 */
    {1u, 2u, 0u, 100u, 20u, 20u, 8u, 1u, 1u, 18u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 7u},
    /* Struggle -- data/moves.ts:18211-18232 */
    {12u, 0u, 50u, 0u, 1u, 1u, 8u, 10u, 1u, 99u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 9u},
    /* Dire Claw -- data/moves.ts:3629-3647, data/mods/champions/moves.ts:217-227 */
    {13u, 0u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 30u, 4u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Flare Blitz -- data/moves.ts:5642-5659 */
    {6u, 0u, 120u, 100u, 15u, 16u, 8u, 1u, 1u, 131u, {33u, 100u}, {0u, 0u}, 10u, 2u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Darkest Lariat -- data/moves.ts:3323-3337 */
    {1u, 0u, 85u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 10u},
    /* Hyper Voice -- data/moves.ts:9207-9219 */
    {12u, 1u, 90u, 100u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Draco Meteor -- data/moves.ts:4002-4019 */
    {2u, 1u, 130u, 90u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 3u, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Follow Me -- data/moves.ts:6039-6074 */
    {12u, 2u, 0u, 0u, 20u, 20u, 10u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 14u},
    /* Helping Hand -- data/moves.ts:8573-8606 */
    {12u, 2u, 0u, 0u, 20u, 20u, 13u, 3u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 13u},
    /* Kowtow Cleave -- data/moves.ts:9985-9996 */
    {1u, 0u, 85u, 0u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Sucker Punch -- data/moves.ts:18396-18415 */
    {1u, 0u, 70u, 100u, 5u, 8u, 9u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 12u},
    /* Last Respects -- data/moves.ts:10091-10105 */
    {8u, 0u, 50u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 11u},
    /* Wave Crash -- data/moves.ts:20679-20691 */
    {17u, 0u, 120u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Aqua Jet -- data/moves.ts:453-465 */
    {17u, 0u, 40u, 100u, 20u, 20u, 9u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Flip Turn -- data/moves.ts:5787-5799 */
    {17u, 0u, 60u, 100u, 20u, 20u, 8u, 1u, 1u, 19u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
};

const dfi_item_data dfi_ext_items[DFI_EXT_ITEM_COUNT] = {
    /* Miracle Seed -- data/items.ts:4135-4149 */
    {255u, 255u},
    /* Staraptite -- data/items.ts:5977-5988, data/mods/champions/items.ts:898-901 */
    {1u, 2u},
    /* Sitrus Berry -- data/items.ts:5744-5765 */
    {255u, 255u},
    /* Grassy Seed -- data/items.ts:2595-2617 */
    {255u, 255u},
    /* Raichunite Y -- data/items.ts:5047-5058, data/mods/champions/items.ts:766-769 */
    {5u, 6u},
    /* Life Orb -- data/items.ts:3404-3420 */
    {255u, 255u},
    /* Mystic Water -- data/items.ts:4254-4268 */
    {255u, 255u},
    /* Golisopite -- data/items.ts:2529-2540, data/mods/champions/items.ts:402-405 */
    {9u, 10u},
    /* Leftovers -- data/items.ts:3338-3351 */
    {255u, 255u},
    /* Charizardite Y -- data/items.ts:800-811, data/mods/champions/items.ts:142-145 */
    {13u, 14u},
    /* Light Clay -- data/items.ts:3444-3453 */
    {255u, 255u},
    /* White Herb -- data/items.ts:7658-7712 */
    {255u, 255u},
    /* Salamencite -- data/items.ts:5506-5517, data/mods/champions/items.ts:830-833 */
    {18u, 19u},
    /* Rocky Helmet -- data/items.ts:5295-5309 */
    {255u, 255u},
    /* Chople Berry -- data/items.ts:1030-1053 */
    {255u, 255u},
    /* Choice Scarf -- data/items.ts:983-1005 */
    {255u, 255u},
};

/* Abilities carry no table data. Provenance of the Team C abilities:
 *   unburden -- data/abilities.ts:5235-5257
 *   psychicsurge -- data/abilities.ts:3580-3588
 *   defiant -- data/abilities.ts:901-921
 *   adaptability -- data/abilities.ts:43-56
 *   aerilate -- data/abilities.ts:57-77
 */

/* data/typechart.ts: the closure bits plus psn (Poison, Steel). */
const uint8_t dfi_ext_type_immunity[DFI_TYPE_COUNT] = {0u, 8u, 0u, 4u, 0u, 0u, 1u, 0u, 0u, 0u, 0u, 2u, 0u, 16u, 0u, 0u, 16u, 0u};

const uint8_t dfi_ext_table_hash[32] = {
    0xd1u, 0x6bu, 0x1cu, 0xefu, 0x1bu, 0x41u, 0xf0u, 0xa5u,
    0x73u, 0xaeu, 0x74u, 0xc1u, 0x01u, 0x02u, 0xc9u, 0x32u,
    0xc1u, 0xf4u, 0xdeu, 0x0eu, 0xc3u, 0xc1u, 0xf3u, 0x34u,
    0x49u, 0xf9u, 0x20u, 0xe5u, 0x33u, 0xa9u, 0x43u, 0xe5u,
};

static size_t dfi_ext_put_u16(uint8_t *out, size_t n, uint32_t v)
{
    out[n] = (uint8_t)(v & 0xFFu);             /* wide-operands-reviewed */
    out[n + 1u] = (uint8_t)((v >> 8u) & 0xFFu); /* wide-operands-reviewed */
    return n + 2u;
}

size_t dfi_ext_canonical_bytes_of(uint8_t *out, size_t capacity, uint32_t formes, uint32_t moves, uint32_t items,
                                  uint32_t abilities, uint32_t immunity_mask)
{
    if (formes > DFI_EXT_FORME_COUNT || moves > DFI_EXT_MOVE_COUNT || items > DFI_EXT_ITEM_COUNT ||
        abilities > DFI_EXT_ABILITY_COUNT) {
        return 0u;
    }
    /* counts, 24 bytes per forme, 29 per move, 2 per item, chart, immunity, natures */
    const size_t size = 12u + (size_t)formes * 24u + (size_t)moves * 29u + (size_t)items * 2u +
                        DFI_TYPE_COUNT * DFI_TYPE_COUNT + DFI_TYPE_COUNT + DFI_NATURE_COUNT * 2u;
    if (capacity < size) {
        return 0u;
    }
    size_t n = 0u;
    n = dfi_ext_put_u16(out, n, formes);
    n = dfi_ext_put_u16(out, n, moves);
    n = dfi_ext_put_u16(out, n, items);
    n = dfi_ext_put_u16(out, n, abilities);
    n = dfi_ext_put_u16(out, n, DFI_TYPE_COUNT);
    n = dfi_ext_put_u16(out, n, DFI_NATURE_COUNT);
    for (uint32_t i = 0u; i < formes; ++i) {
        const dfi_forme_data *f = &dfi_ext_formes[i];
        n = dfi_ext_put_u16(out, n, f->dex_num);
        out[n++] = f->types[0];
        out[n++] = f->types[1];
        for (uint32_t k = 0u; k < DFI_STAT_COUNT; ++k) {
            out[n++] = f->base[k];
        }
        n = dfi_ext_put_u16(out, n, f->weight_hg);
        out[n++] = f->ability;
        out[n++] = f->gender_rule;
        out[n++] = f->is_mega;
        out[n++] = f->base_forme;
        out[n++] = f->mega_forme;
        out[n++] = f->mega_item;
        out[n++] = f->set_item;
        out[n++] = f->set_move_count;
        for (uint32_t k = 0u; k < 4u; ++k) {
            out[n++] = f->set_moves[k];
        }
    }
    for (uint32_t i = 0u; i < moves; ++i) {
        const dfi_move_data *m = &dfi_ext_moves[i];
        out[n++] = m->type;
        out[n++] = m->category;
        out[n++] = m->base_power;
        out[n++] = m->accuracy;
        out[n++] = m->pp_base;
        out[n++] = m->pp_max;
        out[n++] = m->priority;
        out[n++] = m->target_class;
        out[n++] = m->crit_ratio;
        out[n++] = m->flags;
        out[n++] = m->recoil[0];
        out[n++] = m->recoil[1];
        out[n++] = m->drain[0];
        out[n++] = m->drain[1];
        out[n++] = m->sec_chance;
        out[n++] = m->sec_kind;
        out[n++] = m->sec_param;
        out[n++] = m->boost_role;
        for (uint32_t k = 0u; k < DFI_STAGE_COUNT; ++k) {
            out[n++] = m->boosts[k];
        }
        out[n++] = m->primary_status;
        out[n++] = m->side_condition;
        out[n++] = m->pseudo_weather;
        out[n++] = m->special;
    }
    for (uint32_t i = 0u; i < items; ++i) {
        out[n++] = dfi_ext_items[i].mega_base;
        out[n++] = dfi_ext_items[i].mega_forme;
    }
    for (uint32_t d = 0u; d < DFI_TYPE_COUNT; ++d) {
        for (uint32_t a = 0u; a < DFI_TYPE_COUNT; ++a) {
            out[n++] = dfi_closure_type_chart[d][a];
        }
    }
    for (uint32_t i = 0u; i < DFI_TYPE_COUNT; ++i) {
        out[n++] = (uint8_t)(dfi_ext_type_immunity[i] & immunity_mask); /* wide-operands-reviewed: < 256 */
    }
    for (uint32_t i = 0u; i < DFI_NATURE_COUNT; ++i) {
        out[n++] = dfi_closure_natures[i].plus;
        out[n++] = dfi_closure_natures[i].minus;
    }
    return n;
}

size_t dfi_ext_canonical_bytes(uint8_t *out, size_t capacity)
{
    return dfi_ext_canonical_bytes_of(out, capacity, DFI_EXT_FORME_COUNT, DFI_EXT_MOVE_COUNT, DFI_EXT_ITEM_COUNT,
                                      DFI_EXT_ABILITY_COUNT, 0xFFu);
}
