#ifndef DUOFORGE_DATA_POOL_TABLES_H
#define DUOFORGE_DATA_POOL_TABLES_H
/*
 * GENERATED by tools/datagen/gen_closure.py --pool -- do not edit.
 *
 * The pool tables of decision 0015: the extended tables (the closure tables
 * followed by Team C, decision 0009) unchanged as the prefix, then the rows
 * that the steps of the content expansion add, read from Pokemon Showdown
 * b2cb775b0616115b775534eaeff50300e1fc81fc (the input files of
 * closure_tables.h). Every id below an extended count (DFI_EXT_FORME_COUNT,
 * DFI_EXT_MOVE_COUNT, DFI_EXT_ITEM_COUNT, DFI_EXT_ABILITY_COUNT) is the
 * extended table's and its row equals the extended row. Natures and the type
 * chart are the closure's.
 *
 * The family columns are arrays of their own, so that the row types stay
 * those of the closure tables. They hold, for every item and ability
 * (the prefix included), its family and the parameter the family rule reads;
 * each is the result of one strict pattern over the pinned handler. They are
 * part of the canonical pool bytes and so of the pool table hash, and not of
 * the closure or extended bytes. A family column says what an id is, not
 * that the engine implements it: the support manifest decides that.
 *
 * Data only. An id names a record; every effect needs a typed handler in C
 * and an entry in the support manifest before a battle may use it.
 */
#include <stddef.h>
#include <stdint.h>

#include "data/extended_tables.h"

/* ---- the pool has the extended formes and moves so far ---- */
#define DFI_POOL_FORME_COUNT 23u
#define DFI_POOL_MOVE_COUNT 50u

/* ---- pool abilities (appended after the extended ones) ---- */
#define DFI_ABILITY_PIXILATE 21u
#define DFI_ABILITY_REFRIGERATE 22u
#define DFI_ABILITY_OVERGROW 23u
#define DFI_ABILITY_TORRENT 24u
#define DFI_ABILITY_SWARM 25u
#define DFI_POOL_ABILITY_COUNT 26u

/* ---- pool items (appended after the extended ones): type boosters, then resist berries ---- */
#define DFI_ITEM_BLACKBELT 16u
#define DFI_ITEM_BLACKGLASSES 17u
#define DFI_ITEM_CHARCOAL 18u
#define DFI_ITEM_DRAGONFANG 19u
#define DFI_ITEM_FAIRYFEATHER 20u
#define DFI_ITEM_HARDSTONE 21u
#define DFI_ITEM_MAGNET 22u
#define DFI_ITEM_METALCOAT 23u
#define DFI_ITEM_NEVERMELTICE 24u
#define DFI_ITEM_POISONBARB 25u
#define DFI_ITEM_SHARPBEAK 26u
#define DFI_ITEM_SILKSCARF 27u
#define DFI_ITEM_SILVERPOWDER 28u
#define DFI_ITEM_SOFTSAND 29u
#define DFI_ITEM_SPELLTAG 30u
#define DFI_ITEM_TWISTEDSPOON 31u
#define DFI_ITEM_BABIRIBERRY 32u
#define DFI_ITEM_CHARTIBERRY 33u
#define DFI_ITEM_CHILANBERRY 34u
#define DFI_ITEM_COBABERRY 35u
#define DFI_ITEM_COLBURBERRY 36u
#define DFI_ITEM_HABANBERRY 37u
#define DFI_ITEM_KASIBBERRY 38u
#define DFI_ITEM_KEBIABERRY 39u
#define DFI_ITEM_OCCABERRY 40u
#define DFI_ITEM_PASSHOBERRY 41u
#define DFI_ITEM_PAYAPABERRY 42u
#define DFI_ITEM_RINDOBERRY 43u
#define DFI_ITEM_ROSELIBERRY 44u
#define DFI_ITEM_SHUCABERRY 45u
#define DFI_ITEM_TANGABERRY 46u
#define DFI_ITEM_WACANBERRY 47u
#define DFI_ITEM_YACHEBERRY 48u
#define DFI_POOL_ITEM_COUNT 49u

/* ---- family columns ----
 * Items: TYPE_BOOSTER holds BasePower x4915/4096 for a move of the type
 * (priority 15); RESIST_BERRY is eaten on a super effective hit of the type
 * (ModifyDamage x0.5); the Normal berry (Chilan) halves any Normal hit,
 * since a Normal move is never super effective.
 * Abilities: ATE turns Normal moves into the type and gives them BasePower
 * x4915/4096 (priority 23); PINCH gives Atk and SpA x1.5 for a move of the
 * type at a third of the HP or less; WEATHER_SETTER and TERRAIN_SETTER set
 * the field condition on entry.
 * The parameter is a DFI_TYPE_* (items; ATE and PINCH), a
 * DFI_FAMILY_WEATHER_* or a DFI_FAMILY_TERRAIN_*, and DFI_FAMILY_PARAM_NONE
 * where there is no family. The weather and terrain codes are the state
 * values of the engine (DFI_WEATHER_*, DFI_TERRAIN_*). */
#define DFI_ITEM_FAMILY_NONE 0u
#define DFI_ITEM_FAMILY_TYPE_BOOSTER 1u
#define DFI_ITEM_FAMILY_RESIST_BERRY 2u
#define DFI_ABILITY_FAMILY_NONE 0u
#define DFI_ABILITY_FAMILY_ATE 1u
#define DFI_ABILITY_FAMILY_PINCH 2u
#define DFI_ABILITY_FAMILY_WEATHER_SETTER 3u
#define DFI_ABILITY_FAMILY_TERRAIN_SETTER 4u
#define DFI_FAMILY_WEATHER_RAIN 1u
#define DFI_FAMILY_WEATHER_SUN 2u
#define DFI_FAMILY_TERRAIN_GRASSY 1u
#define DFI_FAMILY_TERRAIN_PSYCHIC 2u
#define DFI_FAMILY_PARAM_NONE 0xFFu

typedef struct dfi_item_family {
    uint8_t family; /* DFI_ITEM_FAMILY_* */
    uint8_t type;   /* the type of the family rule (DFI_TYPE_*), DFI_FAMILY_PARAM_NONE without a family */
} dfi_item_family;

typedef struct dfi_ability_family {
    uint8_t family; /* DFI_ABILITY_FAMILY_* */
    uint8_t param;  /* ATE, PINCH: DFI_TYPE_*; WEATHER_SETTER: DFI_FAMILY_WEATHER_*; TERRAIN_SETTER: DFI_FAMILY_TERRAIN_* */
} dfi_ability_family;

extern const dfi_forme_data dfi_pool_formes[DFI_POOL_FORME_COUNT];
extern const dfi_move_data dfi_pool_moves[DFI_POOL_MOVE_COUNT];
extern const dfi_item_data dfi_pool_items[DFI_POOL_ITEM_COUNT];
extern const uint8_t dfi_pool_type_immunity[DFI_TYPE_COUNT]; /* DFI_IMMUNE_* bits */
extern const dfi_item_family dfi_pool_item_family[DFI_POOL_ITEM_COUNT];
extern const dfi_ability_family dfi_pool_ability_family[DFI_POOL_ABILITY_COUNT];

/* SHA-256 of the canonical pool bytes (written by the generator). */
#define DFI_POOL_CANONICAL_SIZE 2654u
extern const uint8_t dfi_pool_table_hash[32];
/* The canonical bytes of the closure layout over the first `formes`, `moves`,
 * `items` and `abilities` rows of the tables above, with every immunity byte
 * masked by `immunity_mask`; natures and the type chart are the closure's.
 * The family columns are not part of them. Returns the size, or 0 if a count
 * exceeds its table or capacity is too small. With the closure counts and the
 * closure's immunity bits these are exactly the closure's canonical bytes;
 * with the extended counts and every immunity bit, the extended ones. */
size_t dfi_pool_canonical_bytes_of(uint8_t *out, size_t capacity, uint32_t formes, uint32_t moves, uint32_t items,
                                   uint32_t abilities, uint32_t immunity_mask);
/* The canonical pool bytes: every row, every immunity bit, then the family
 * column of every item and of every ability (family, parameter). */
size_t dfi_pool_canonical_bytes(uint8_t *out, size_t capacity);

#endif
