#include "data/pool_tables.h"

/* GENERATED by tools/datagen/gen_closure.py --pool -- do not edit. Showdown b2cb775b0616115b775534eaeff50300e1fc81fc. */

const dfi_forme_data dfi_pool_formes[DFI_POOL_FORME_COUNT] = {
    /* Rillaboom -- data/pokedex.ts:15678-15692 */
    {812u, 900u, {9u, 255u}, {100u, 125u, 90u, 60u, 70u, 85u}, 0u, 0u, 0u, 0u, 255u, 255u, 0u, 4u, {0u, 1u, 2u, 3u}},
    /* Staraptor -- data/pokedex.ts:7423-7437 */
    {398u, 249u, {12u, 7u}, {85u, 120u, 70u, 50u, 60u, 100u}, 1u, 0u, 0u, 1u, 2u, 1u, 1u, 4u, {4u, 5u, 6u, 7u}},
    /* Staraptor-Mega -- data/pokedex.ts:7438-7452 */
    {398u, 500u, {5u, 7u}, {85u, 140u, 100u, 60u, 90u, 110u}, 12u, 0u, 1u, 1u, 255u, 1u, 1u, 0u, {0u, 0u, 0u, 0u}},
    /* Milotic -- data/pokedex.ts:6502-6515 */
    {350u, 1620u, {17u, 255u}, {95u, 60u, 79u, 100u, 125u, 81u}, 2u, 0u, 0u, 3u, 255u, 255u, 2u, 4u, {8u, 9u, 10u, 11u}},
    /* Ceruledge -- data/pokedex.ts:18122-18135 */
    {937u, 620u, {6u, 8u}, {75u, 125u, 80u, 60u, 100u, 85u}, 3u, 0u, 0u, 4u, 255u, 255u, 3u, 4u, {12u, 13u, 14u, 7u}},
    /* Raichu -- data/pokedex.ts:804-819 */
    {26u, 300u, {3u, 255u}, {60u, 90u, 55u, 90u, 80u, 110u}, 4u, 0u, 0u, 5u, 6u, 4u, 4u, 4u, {15u, 16u, 2u, 7u}},
    /* Raichu-Mega-Y -- data/pokedex.ts:852-866 */
    {26u, 260u, {3u, 255u}, {60u, 100u, 55u, 160u, 80u, 130u}, 13u, 0u, 1u, 5u, 255u, 4u, 4u, 0u, {0u, 0u, 0u, 0u}},
    /* Gholdengo -- data/pokedex.ts:19101-19115 */
    {1000u, 300u, {16u, 8u}, {87u, 60u, 95u, 133u, 91u, 84u}, 5u, 3u, 0u, 7u, 255u, 255u, 5u, 4u, {17u, 18u, 19u, 7u}},
    /* Politoed -- data/pokedex.ts:3980-3993 */
    {186u, 339u, {17u, 255u}, {90u, 75u, 75u, 90u, 100u, 70u}, 6u, 0u, 0u, 8u, 255u, 255u, 6u, 4u, {20u, 8u, 10u, 7u}},
    /* Golisopod -- data/pokedex.ts:14516-14530 */
    {768u, 1080u, {0u, 17u}, {75u, 125u, 140u, 60u, 90u, 40u}, 7u, 0u, 0u, 9u, 10u, 7u, 7u, 4u, {21u, 22u, 23u, 7u}},
    /* Golisopod-Mega -- data/pokedex.ts:14531-14545 */
    {768u, 1480u, {0u, 16u}, {75u, 150u, 175u, 70u, 120u, 40u}, 14u, 0u, 1u, 9u, 255u, 7u, 7u, 0u, {0u, 0u, 0u, 0u}},
    /* Archaludon -- data/pokedex.ts:19501-19514 */
    {1018u, 600u, {16u, 2u}, {90u, 105u, 130u, 125u, 65u, 85u}, 8u, 0u, 0u, 11u, 255u, 255u, 8u, 4u, {24u, 25u, 26u, 7u}},
    /* Farigiraf -- data/pokedex.ts:18798-18811 */
    {981u, 1600u, {12u, 14u}, {120u, 90u, 70u, 110u, 70u, 60u}, 9u, 0u, 0u, 12u, 255u, 255u, 2u, 4u, {27u, 28u, 29u, 7u}},
    /* Charizard -- data/pokedex.ts:106-122 */
    {6u, 905u, {6u, 7u}, {78u, 84u, 78u, 109u, 85u, 100u}, 10u, 0u, 0u, 13u, 14u, 9u, 9u, 4u, {30u, 20u, 31u, 7u}},
    /* Charizard-Mega-Y -- data/pokedex.ts:138-152 */
    {6u, 1005u, {6u, 7u}, {78u, 104u, 78u, 159u, 115u, 100u}, 15u, 0u, 1u, 13u, 255u, 9u, 9u, 0u, {0u, 0u, 0u, 0u}},
    /* Grimmsnarl -- data/pokedex.ts:16636-16650 */
    {861u, 610u, {1u, 4u}, {95u, 120u, 65u, 95u, 75u, 60u}, 11u, 1u, 0u, 15u, 255u, 255u, 10u, 4u, {32u, 33u, 34u, 35u}},
    /* Sneasler -- data/pokedex.ts:17573-17587 */
    {903u, 430u, {5u, 13u}, {80u, 130u, 60u, 40u, 80u, 120u}, 16u, 0u, 0u, 16u, 255u, 255u, 11u, 4u, {5u, 37u, 7u, 2u}},
    /* Incineroar -- data/pokedex.ts:13756-13769 */
    {727u, 830u, {6u, 1u}, {95u, 115u, 90u, 80u, 90u, 60u}, 1u, 0u, 0u, 17u, 255u, 255u, 2u, 4u, {2u, 38u, 35u, 39u}},
    /* Salamence -- data/pokedex.ts:6920-6934 */
    {373u, 1026u, {2u, 7u}, {95u, 135u, 80u, 110u, 80u, 100u}, 1u, 0u, 0u, 18u, 19u, 12u, 12u, 4u, {7u, 40u, 41u, 6u}},
    /* Salamence-Mega -- data/pokedex.ts:6935-6948 */
    {373u, 1126u, {2u, 7u}, {95u, 145u, 130u, 120u, 90u, 120u}, 20u, 0u, 1u, 18u, 255u, 12u, 12u, 0u, {0u, 0u, 0u, 0u}},
    /* Indeedee-F -- data/pokedex.ts:16969-16982 */
    {876u, 280u, {14u, 12u}, {70u, 55u, 65u, 95u, 105u, 85u}, 17u, 2u, 0u, 20u, 255u, 255u, 13u, 4u, {42u, 29u, 43u, 27u}},
    /* Kingambit -- data/pokedex.ts:18845-18858 */
    {983u, 1200u, {1u, 16u}, {100u, 135u, 120u, 60u, 85u, 50u}, 18u, 0u, 0u, 21u, 255u, 255u, 14u, 4u, {44u, 45u, 22u, 7u}},
    /* Basculegion -- data/pokedex.ts:17538-17555 */
    {902u, 1100u, {17u, 8u}, {120u, 112u, 65u, 80u, 75u, 78u}, 19u, 1u, 0u, 22u, 255u, 255u, 15u, 4u, {47u, 46u, 49u, 48u}},
    /* Pelipper -- data/pokedex.ts:5458-5470 */
    {279u, 280u, {17u, 7u}, {60u, 50u, 100u, 95u, 70u, 65u}, 6u, 0u, 0u, 23u, 255u, 255u, 2u, 4u, {20u, 31u, 6u, 57u}},
    /* Arcanine-Hisui -- data/pokedex.ts:1515-1531 */
    {59u, 1680u, {6u, 15u}, {95u, 115u, 80u, 95u, 80u, 90u}, 26u, 0u, 0u, 24u, 255u, 255u, 49u, 4u, {38u, 60u, 59u, 7u}},
    /* Annihilape -- data/pokedex.ts:18771-18784 */
    {979u, 560u, {5u, 8u}, {110u, 115u, 80u, 50u, 90u, 90u}, 18u, 0u, 0u, 25u, 255u, 255u, 15u, 4u, {5u, 64u, 65u, 50u}},
    /* Floette-Eternal -- data/pokedex.ts:12573-12586 */
    {670u, 9u, {4u, 255u}, {74u, 65u, 67u, 125u, 128u, 92u}, 27u, 2u, 0u, 26u, 27u, 51u, 51u, 2u, {71u, 7u, 0u, 0u}},
    /* Floette-Mega -- data/pokedex.ts:12587-12603 */
    {670u, 1008u, {4u, 255u}, {74u, 85u, 87u, 155u, 148u, 102u}, 28u, 2u, 1u, 26u, 255u, 51u, 51u, 0u, {0u, 0u, 0u, 0u}},
};

const dfi_move_data dfi_pool_moves[DFI_POOL_MOVE_COUNT] = {
    /* Wood Hammer -- data/moves.ts:21018-21031 */
    {9u, 0u, 120u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Grassy Glide -- data/moves.ts:7655-7672 */
    {9u, 0u, 55u, 100u, 20u, 20u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 4u},
    /* Fake Out -- data/moves.ts:5087-5109, data/mods/champions/moves.ts:354-361 */
    {12u, 0u, 40u, 100u, 10u, 12u, 11u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 100u, 3u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 6u},
    /* High Horsepower -- data/moves.ts:8885-8897 */
    {10u, 0u, 95u, 95u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Brave Bird -- data/moves.ts:1775-1788 */
    {7u, 0u, 120u, 100u, 15u, 16u, 8u, 2u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Close Combat -- data/moves.ts:2571-2589 */
    {5u, 0u, 120u, 100u, 5u, 8u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 3u, {6u, 5u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Tailwind -- data/moves.ts:18875-18914 */
    {7u, 2u, 0u, 0u, 15u, 16u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 1u, 0u, 0u},
    /* Protect -- data/moves.ts:13961-14005, data/mods/champions/moves.ts:765-768 */
    {12u, 2u, 0u, 0u, 5u, 8u, 12u, 6u, 1u, 8u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 8u},
    /* Muddy Water -- data/moves.ts:12398-12416 */
    {17u, 1u, 90u, 85u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 30u, 1u, 0u, 2u, {6u, 6u, 6u, 6u, 6u, 5u, 6u}, 0u, 0u, 0u, 0u},
    /* Coil -- data/moves.ts:2606-2624 */
    {13u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {7u, 7u, 6u, 6u, 6u, 7u, 6u}, 0u, 0u, 0u, 0u},
    /* Ice Beam -- data/moves.ts:9302-9318 */
    {11u, 1u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 2u, 2u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Hypnosis -- data/moves.ts:9220-9234 */
    {14u, 2u, 0u, 60u, 20u, 20u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 4u, 0u, 0u, 0u},
    /* Bitter Blade -- data/moves.ts:1368-1380 */
    {6u, 0u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {1u, 2u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Shadow Sneak -- data/moves.ts:16115-16127 */
    {8u, 0u, 40u, 100u, 30u, 20u, 9u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Swords Dance -- data/moves.ts:18691-18707 */
    {12u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {8u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Zap Cannon -- data/moves.ts:21163-21179 */
    {3u, 1u, 120u, 50u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 100u, 2u, 3u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Focus Blast -- data/moves.ts:5952-5970 */
    {5u, 1u, 120u, 70u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Make It Rain -- data/moves.ts:10934-10951, data/mods/champions/moves.ts:609-617 */
    {16u, 1u, 120u, 95u, 5u, 8u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 3u, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Shadow Ball -- data/moves.ts:16020-16038 */
    {8u, 1u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 20u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Nasty Plot -- data/moves.ts:12548-12564 */
    {1u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {6u, 6u, 8u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Weather Ball -- data/moves.ts:20692-20745 */
    {12u, 1u, 50u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 2u},
    /* Leech Life -- data/moves.ts:10188-10201 */
    {0u, 0u, 80u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {1u, 2u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Iron Head -- data/moves.ts:9722-9738, data/mods/champions/moves.ts:545-551 */
    {16u, 0u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 20u, 3u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Drill Run -- data/moves.ts:4280-4293 */
    {10u, 0u, 80u, 95u, 10u, 12u, 8u, 1u, 2u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Dragon Pulse -- data/moves.ts:4163-4175 */
    {2u, 1u, 85u, 100u, 10u, 12u, 8u, 2u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Electro Shot -- data/moves.ts:4630-4659 */
    {3u, 1u, 130u, 100u, 10u, 12u, 8u, 1u, 1u, 6u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 5u},
    /* Snarl -- data/moves.ts:17085-17103 */
    {1u, 1u, 55u, 95u, 15u, 16u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 100u, 1u, 0u, 2u, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Psychic -- data/moves.ts:14041-14059 */
    {14u, 1u, 90u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Grass Knot -- data/moves.ts:7537-7577 */
    {9u, 1u, 0u, 100u, 20u, 20u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 1u},
    /* Trick Room -- data/moves.ts:19940-19980 */
    {14u, 2u, 0u, 0u, 5u, 8u, 1u, 9u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 1u, 0u},
    /* Heat Wave -- data/moves.ts:8516-8532 */
    {6u, 1u, 95u, 90u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 2u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Hurricane -- data/moves.ts:9026-9054 */
    {7u, 1u, 110u, 70u, 10u, 12u, 8u, 2u, 1u, 2u, {0u, 0u}, {0u, 0u}, 30u, 3u, 2u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 3u},
    /* Spirit Break -- data/moves.ts:17602-17619 */
    {4u, 0u, 75u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 100u, 1u, 0u, 2u, {6u, 6u, 5u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Reflect -- data/moves.ts:14842-14882 */
    {14u, 2u, 0u, 0u, 20u, 20u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 2u, 0u, 0u},
    /* Light Screen -- data/moves.ts:10315-10355 */
    {14u, 2u, 0u, 0u, 30u, 20u, 8u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 3u, 0u, 0u},
    /* Parting Shot -- data/moves.ts:13165-13185 */
    {1u, 2u, 0u, 100u, 20u, 20u, 8u, 1u, 1u, 18u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 7u},
    /* Struggle -- data/moves.ts:18211-18232 */
    {12u, 0u, 50u, 0u, 1u, 1u, 8u, 10u, 1u, 99u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 9u},
    /* Dire Claw -- data/moves.ts:3629-3647, data/mods/champions/moves.ts:217-227 */
    {13u, 0u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 30u, 4u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Flare Blitz -- data/moves.ts:5642-5659 */
    {6u, 0u, 120u, 100u, 15u, 16u, 8u, 1u, 1u, 131u, {33u, 100u}, {0u, 0u}, 10u, 2u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Darkest Lariat -- data/moves.ts:3323-3337 */
    {1u, 0u, 85u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 10u},
    /* Hyper Voice -- data/moves.ts:9207-9219 */
    {12u, 1u, 90u, 100u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Draco Meteor -- data/moves.ts:4002-4019 */
    {2u, 1u, 130u, 90u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 3u, {6u, 6u, 4u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Follow Me -- data/moves.ts:6039-6074 */
    {12u, 2u, 0u, 0u, 20u, 20u, 10u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 14u},
    /* Helping Hand -- data/moves.ts:8573-8606 */
    {12u, 2u, 0u, 0u, 20u, 20u, 13u, 3u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 13u},
    /* Kowtow Cleave -- data/moves.ts:9985-9996 */
    {1u, 0u, 85u, 0u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Sucker Punch -- data/moves.ts:18396-18415 */
    {1u, 0u, 70u, 100u, 5u, 8u, 9u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 12u},
    /* Last Respects -- data/moves.ts:10091-10105 */
    {8u, 0u, 50u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 11u},
    /* Wave Crash -- data/moves.ts:20679-20691 */
    {17u, 0u, 120u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Aqua Jet -- data/moves.ts:453-465 */
    {17u, 0u, 40u, 100u, 20u, 20u, 9u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Flip Turn -- data/moves.ts:5787-5799 */
    {17u, 0u, 60u, 100u, 20u, 20u, 8u, 1u, 1u, 19u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* U-turn -- data/moves.ts:20268-20281 */
    {0u, 0u, 70u, 100u, 20u, 20u, 8u, 1u, 1u, 19u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Rock Slide -- data/moves.ts:15239-15255 */
    {15u, 0u, 75u, 90u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 30u, 3u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Throat Chop -- data/moves.ts:19389-19437 */
    {1u, 0u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 15u},
    /* Encore -- data/moves.ts:4724-4783, data/mods/champions/moves.ts:309-345 */
    {12u, 2u, 0u, 100u, 5u, 8u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 16u},
    /* Double-Edge -- data/moves.ts:3879-3892 */
    {12u, 0u, 120u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {33u, 100u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Thunderbolt -- data/moves.ts:19467-19483 */
    {3u, 1u, 90u, 100u, 15u, 16u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 2u, 3u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Scald -- data/moves.ts:15761-15778 */
    {17u, 1u, 80u, 100u, 15u, 16u, 8u, 1u, 1u, 130u, {0u, 0u}, {0u, 0u}, 30u, 2u, 1u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 17u},
    /* Wide Guard -- data/moves.ts:20808-20851 */
    {15u, 2u, 0u, 0u, 10u, 12u, 11u, 8u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 18u},
    /* Flash Cannon -- data/moves.ts:5678-5696 */
    {16u, 1u, 80u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 10u, 1u, 0u, 2u, {6u, 6u, 6u, 5u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Extreme Speed -- data/moves.ts:5019-5031 */
    {12u, 0u, 80u, 100u, 5u, 8u, 10u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Head Smash -- data/moves.ts:8226-8239 */
    {15u, 0u, 150u, 80u, 5u, 8u, 8u, 1u, 1u, 3u, {1u, 2u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* First Impression -- data/moves.ts:5473-5491, data/mods/champions/moves.ts:386-394 */
    {0u, 0u, 100u, 100u, 10u, 12u, 10u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 19u},
    /* Bulk Up -- data/moves.ts:1954-1971 */
    {5u, 2u, 0u, 0u, 20u, 20u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 1u, {7u, 7u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Liquidation -- data/moves.ts:10375-10393 */
    {17u, 0u, 85u, 100u, 10u, 12u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 20u, 1u, 0u, 2u, {6u, 5u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Ice Punch -- data/moves.ts:9387-9403 */
    {11u, 0u, 75u, 100u, 15u, 16u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 10u, 2u, 2u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Shadow Claw -- data/moves.ts:16059-16072, data/mods/champions/moves.ts:871-874 */
    {8u, 0u, 70u, 100u, 15u, 16u, 8u, 1u, 2u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Recover -- data/moves.ts:14806-14820 */
    {12u, 2u, 0u, 0u, 5u, 8u, 8u, 6u, 1u, 0u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 20u},
    /* Soak -- data/moves.ts:17186-17208 */
    {17u, 2u, 0u, 100u, 20u, 20u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 21u},
    /* Psychic Noise -- data/moves.ts:14079-14094 */
    {14u, 1u, 75u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 22u},
    /* Drum Beating -- data/moves.ts:4294-4311 */
    {9u, 0u, 80u, 100u, 10u, 12u, 8u, 1u, 1u, 2u, {0u, 0u}, {0u, 0u}, 100u, 1u, 0u, 2u, {6u, 6u, 6u, 6u, 5u, 6u, 6u}, 0u, 0u, 0u, 0u},
    /* Low Kick -- data/moves.ts:10442-10481 */
    {5u, 0u, 0u, 100u, 20u, 20u, 8u, 1u, 1u, 3u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 23u},
    /* Dazzling Gleam -- data/moves.ts:3378-3390 */
    {4u, 1u, 80u, 100u, 10u, 12u, 8u, 7u, 1u, 2u, {0u, 0u}, {0u, 0u}, 0u, 0u, 0u, 0u, {6u, 6u, 6u, 6u, 6u, 6u, 6u}, 0u, 0u, 0u, 0u},
};

const dfi_item_data dfi_pool_items[DFI_POOL_ITEM_COUNT] = {
    /* Miracle Seed -- data/items.ts:4135-4149 */
    {255u, 255u},
    /* Staraptite -- data/items.ts:5977-5988, data/mods/champions/items.ts:898-901 */
    {1u, 2u},
    /* Sitrus Berry -- data/items.ts:5744-5765 */
    {255u, 255u},
    /* Grassy Seed -- data/items.ts:2595-2617 */
    {255u, 255u},
    /* Raichunite Y -- data/items.ts:5047-5058, data/mods/champions/items.ts:766-769 */
    {5u, 6u},
    /* Life Orb -- data/items.ts:3404-3420 */
    {255u, 255u},
    /* Mystic Water -- data/items.ts:4254-4268 */
    {255u, 255u},
    /* Golisopite -- data/items.ts:2529-2540, data/mods/champions/items.ts:402-405 */
    {9u, 10u},
    /* Leftovers -- data/items.ts:3338-3351 */
    {255u, 255u},
    /* Charizardite Y -- data/items.ts:800-811, data/mods/champions/items.ts:142-145 */
    {13u, 14u},
    /* Light Clay -- data/items.ts:3444-3453 */
    {255u, 255u},
    /* White Herb -- data/items.ts:7658-7712 */
    {255u, 255u},
    /* Salamencite -- data/items.ts:5506-5517, data/mods/champions/items.ts:830-833 */
    {18u, 19u},
    /* Rocky Helmet -- data/items.ts:5295-5309 */
    {255u, 255u},
    /* Chople Berry -- data/items.ts:1030-1053 */
    {255u, 255u},
    /* Choice Scarf -- data/items.ts:983-1005 */
    {255u, 255u},
    /* Black Belt -- data/items.ts:508-522 */
    {255u, 255u},
    /* Black Glasses -- data/items.ts:523-537 */
    {255u, 255u},
    /* Charcoal -- data/items.ts:773-787 */
    {255u, 255u},
    /* Dragon Fang -- data/items.ts:1482-1496 */
    {255u, 255u},
    /* Fairy Feather -- data/items.ts:1927-1941 */
    {255u, 255u},
    /* Hard Stone -- data/items.ts:2774-2788 */
    {255u, 255u},
    /* Magnet -- data/items.ts:3689-3703 */
    {255u, 255u},
    /* Metal Coat -- data/items.ts:3961-3975 */
    {255u, 255u},
    /* Never-Melt Ice -- data/items.ts:4296-4310 */
    {255u, 255u},
    /* Poison Barb -- data/items.ts:4646-4661 */
    {255u, 255u},
    /* Sharp Beak -- data/items.ts:5606-5620 */
    {255u, 255u},
    /* Silk Scarf -- data/items.ts:5714-5728 */
    {255u, 255u},
    /* Silver Powder -- data/items.ts:5729-5743 */
    {255u, 255u},
    /* Soft Sand -- data/items.ts:5857-5871 */
    {255u, 255u},
    /* Spell Tag -- data/items.ts:5902-5916, data/mods/champions/items.ts:882-885 */
    {255u, 255u},
    /* Twisted Spoon -- data/items.ts:7377-7391 */
    {255u, 255u},
    /* Babiri Berry -- data/items.ts:355-378 */
    {255u, 255u},
    /* Charti Berry -- data/items.ts:812-835 */
    {255u, 255u},
    /* Chilan Berry -- data/items.ts:898-921 */
    {255u, 255u},
    /* Coba Berry -- data/items.ts:1109-1132 */
    {255u, 255u},
    /* Colbur Berry -- data/items.ts:1133-1156 */
    {255u, 255u},
    /* Haban Berry -- data/items.ts:2750-2773 */
    {255u, 255u},
    /* Kasib Berry -- data/items.ts:3129-3152 */
    {255u, 255u},
    /* Kebia Berry -- data/items.ts:3153-3176 */
    {255u, 255u},
    /* Occa Berry -- data/items.ts:4347-4370 */
    {255u, 255u},
    /* Passho Berry -- data/items.ts:4449-4472 */
    {255u, 255u},
    /* Payapa Berry -- data/items.ts:4473-4496 */
    {255u, 255u},
    /* Rindo Berry -- data/items.ts:5203-5226 */
    {255u, 255u},
    /* Roseli Berry -- data/items.ts:5360-5383 */
    {255u, 255u},
    /* Shuca Berry -- data/items.ts:5690-5713 */
    {255u, 255u},
    /* Tanga Berry -- data/items.ts:6222-6245 */
    {255u, 255u},
    /* Wacan Berry -- data/items.ts:7493-7515 */
    {255u, 255u},
    /* Yache Berry -- data/items.ts:7769-7792 */
    {255u, 255u},
    /* Focus Sash -- data/items.ts:2269-2285 */
    {255u, 255u},
    /* Expert Belt -- data/items.ts:1901-1914 */
    {255u, 255u},
    /* Floettite -- data/items.ts:2189-2201, data/mods/champions/items.ts:342-345 */
    {26u, 27u},
};

/* Abilities carry no table data but their family column. Provenance of the pool abilities:
 *   pixilate -- data/abilities.ts:3296-3316
 *   refrigerate -- data/abilities.ts:3812-3832
 *   overgrow -- data/abilities.ts:3124-3143
 *   torrent -- data/abilities.ts:5046-5065
 *   swarm -- data/abilities.ts:4766-4785
 *   rockhead -- data/abilities.ts:3906-3917
 *   flowerveil -- data/abilities.ts:1419-1457
 *   fairyaura -- data/abilities.ts:1266-1282
 */

/* data/typechart.ts: the closure bits plus psn (Poison, Steel). */
const uint8_t dfi_pool_type_immunity[DFI_TYPE_COUNT] = {0u, 8u, 0u, 4u, 0u, 0u, 1u, 0u, 0u, 0u, 0u, 2u, 0u, 16u, 0u, 0u, 16u, 0u};

/* Family columns, one row per id (decision 0015 section 2). */
const dfi_item_family dfi_pool_item_family[DFI_POOL_ITEM_COUNT] = {
    [DFI_ITEM_MIRACLESEED] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_GRASS},
    [DFI_ITEM_STARAPTITE] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_SITRUSBERRY] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_GRASSYSEED] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_RAICHUNITEY] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_LIFEORB] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_MYSTICWATER] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_WATER},
    [DFI_ITEM_GOLISOPITE] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_LEFTOVERS] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_CHARIZARDITEY] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_LIGHTCLAY] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_WHITEHERB] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_SALAMENCITE] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_ROCKYHELMET] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_CHOPLEBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_FIGHTING},
    [DFI_ITEM_CHOICESCARF] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_BLACKBELT] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_FIGHTING},
    [DFI_ITEM_BLACKGLASSES] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_DARK},
    [DFI_ITEM_CHARCOAL] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_FIRE},
    [DFI_ITEM_DRAGONFANG] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_DRAGON},
    [DFI_ITEM_FAIRYFEATHER] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_FAIRY},
    [DFI_ITEM_HARDSTONE] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_ROCK},
    [DFI_ITEM_MAGNET] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_ELECTRIC},
    [DFI_ITEM_METALCOAT] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_STEEL},
    [DFI_ITEM_NEVERMELTICE] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_ICE},
    [DFI_ITEM_POISONBARB] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_POISON},
    [DFI_ITEM_SHARPBEAK] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_FLYING},
    [DFI_ITEM_SILKSCARF] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_NORMAL},
    [DFI_ITEM_SILVERPOWDER] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_BUG},
    [DFI_ITEM_SOFTSAND] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_GROUND},
    [DFI_ITEM_SPELLTAG] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_GHOST},
    [DFI_ITEM_TWISTEDSPOON] = {DFI_ITEM_FAMILY_TYPE_BOOSTER, DFI_TYPE_PSYCHIC},
    [DFI_ITEM_BABIRIBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_STEEL},
    [DFI_ITEM_CHARTIBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_ROCK},
    [DFI_ITEM_CHILANBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_NORMAL},
    [DFI_ITEM_COBABERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_FLYING},
    [DFI_ITEM_COLBURBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_DARK},
    [DFI_ITEM_HABANBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_DRAGON},
    [DFI_ITEM_KASIBBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_GHOST},
    [DFI_ITEM_KEBIABERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_POISON},
    [DFI_ITEM_OCCABERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_FIRE},
    [DFI_ITEM_PASSHOBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_WATER},
    [DFI_ITEM_PAYAPABERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_PSYCHIC},
    [DFI_ITEM_RINDOBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_GRASS},
    [DFI_ITEM_ROSELIBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_FAIRY},
    [DFI_ITEM_SHUCABERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_GROUND},
    [DFI_ITEM_TANGABERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_BUG},
    [DFI_ITEM_WACANBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_ELECTRIC},
    [DFI_ITEM_YACHEBERRY] = {DFI_ITEM_FAMILY_RESIST_BERRY, DFI_TYPE_ICE},
    [DFI_ITEM_FOCUSSASH] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_EXPERTBELT] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ITEM_FLOETTITE] = {DFI_ITEM_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
};

const dfi_ability_family dfi_pool_ability_family[DFI_POOL_ABILITY_COUNT] = {
    [DFI_ABILITY_GRASSYSURGE] = {DFI_ABILITY_FAMILY_TERRAIN_SETTER, DFI_FAMILY_TERRAIN_GRASSY},
    [DFI_ABILITY_INTIMIDATE] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_COMPETITIVE] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_FLASHFIRE] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_LIGHTNINGROD] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_GOODASGOLD] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_DRIZZLE] = {DFI_ABILITY_FAMILY_WEATHER_SETTER, DFI_FAMILY_WEATHER_RAIN},
    [DFI_ABILITY_EMERGENCYEXIT] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_STAMINA] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_ARMORTAIL] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_BLAZE] = {DFI_ABILITY_FAMILY_PINCH, DFI_TYPE_FIRE},
    [DFI_ABILITY_PRANKSTER] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_CONTRARY] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_NOGUARD] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_TOUGHCLAWS] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_DROUGHT] = {DFI_ABILITY_FAMILY_WEATHER_SETTER, DFI_FAMILY_WEATHER_SUN},
    [DFI_ABILITY_UNBURDEN] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_PSYCHICSURGE] = {DFI_ABILITY_FAMILY_TERRAIN_SETTER, DFI_FAMILY_TERRAIN_PSYCHIC},
    [DFI_ABILITY_DEFIANT] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_ADAPTABILITY] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_AERILATE] = {DFI_ABILITY_FAMILY_ATE, DFI_TYPE_FLYING},
    [DFI_ABILITY_PIXILATE] = {DFI_ABILITY_FAMILY_ATE, DFI_TYPE_FAIRY},
    [DFI_ABILITY_REFRIGERATE] = {DFI_ABILITY_FAMILY_ATE, DFI_TYPE_ICE},
    [DFI_ABILITY_OVERGROW] = {DFI_ABILITY_FAMILY_PINCH, DFI_TYPE_GRASS},
    [DFI_ABILITY_TORRENT] = {DFI_ABILITY_FAMILY_PINCH, DFI_TYPE_WATER},
    [DFI_ABILITY_SWARM] = {DFI_ABILITY_FAMILY_PINCH, DFI_TYPE_BUG},
    [DFI_ABILITY_ROCKHEAD] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_FLOWERVEIL] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
    [DFI_ABILITY_FAIRYAURA] = {DFI_ABILITY_FAMILY_NONE, DFI_FAMILY_PARAM_NONE},
};

/* The moves and abilities each forme may have (decision 0015 section 2). */
const dfi_forme_legal dfi_pool_forme_legal[DFI_POOL_FORME_COUNT] = {
    /* Rillaboom -- abilities: overgrow, grassysurge */
    /*    learns: Wood Hammer, Grassy Glide, Fake Out, High Horsepower, Protect, Swords Dance, Focus Blast, */
    /*    Snarl, Grass Knot, Hyper Voice, U-turn, Double-Edge, Bulk Up, Drum Beating, Low Kick */
    [DFI_FORME_RILLABOOM] = {{0x8fu, 0x40u, 0x01u, 0x14u, 0x00u, 0x01u, 0x44u, 0x40u, 0x60u}, 2u, {DFI_ABILITY_OVERGROW, DFI_ABILITY_GRASSYSURGE, DFI_CLOSURE_NONE}},
    /* Staraptor -- abilities: intimidate */
    /*    learns: Brave Bird, Close Combat, Tailwind, Protect, Focus Blast, Heat Wave, Hurricane, */
    /*    Helping Hand, U-turn, Double-Edge, Bulk Up */
    [DFI_FORME_STARAPTOR] = {{0xf0u, 0x00u, 0x01u, 0xc0u, 0x00u, 0x08u, 0x44u, 0x40u, 0x00u}, 1u, {DFI_ABILITY_INTIMIDATE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Staraptor-Mega -- abilities: contrary */
    /*    learns: nothing */
    [DFI_FORME_STARAPTORMEGA] = {{0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u}, 1u, {DFI_ABILITY_CONTRARY, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Milotic -- abilities: competitive */
    /*    learns: Protect, Muddy Water, Coil, Ice Beam, Hypnosis, Weather Ball, Iron Head, Dragon Pulse, */
    /*    Light Screen, Helping Hand, Flip Turn, Double-Edge, Scald, Recover */
    [DFI_FORME_MILOTIC] = {{0x80u, 0x0fu, 0x50u, 0x01u, 0x04u, 0x08u, 0x42u, 0x01u, 0x04u}, 1u, {DFI_ABILITY_COMPETITIVE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Ceruledge -- abilities: flashfire */
    /*    learns: Close Combat, Protect, Bitter Blade, Shadow Sneak, Swords Dance, Shadow Ball, Iron Head, */
    /*    Heat Wave, Reflect, Light Screen, Flare Blitz, Helping Hand, Throat Chop, Bulk Up, Shadow Claw */
    [DFI_FORME_CERULEDGE] = {{0xa0u, 0x70u, 0x44u, 0x40u, 0x46u, 0x08u, 0x10u, 0x40u, 0x02u}, 1u, {DFI_ABILITY_FLASHFIRE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Raichu -- abilities: lightningrod */
    /*    learns: Fake Out, Protect, Zap Cannon, Focus Blast, Nasty Plot, Grass Knot, Reflect, */
    /*    Light Screen, Helping Hand, Encore, Thunderbolt, Dazzling Gleam */
    [DFI_FORME_RAICHU] = {{0x84u, 0x80u, 0x09u, 0x10u, 0x06u, 0x08u, 0xa0u, 0x00u, 0x80u}, 1u, {DFI_ABILITY_LIGHTNINGROD, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Raichu-Mega-Y -- abilities: noguard */
    /*    learns: nothing */
    [DFI_FORME_RAICHUMEGAY] = {{0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u}, 1u, {DFI_ABILITY_NOGUARD, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Gholdengo -- abilities: goodasgold */
    /*    learns: Protect, Focus Blast, Make It Rain, Shadow Ball, Nasty Plot, Iron Head, Psychic, Reflect, */
    /*    Light Screen, Thunderbolt, Flash Cannon, Recover, Low Kick, Dazzling Gleam */
    [DFI_FORME_GHOLDENGO] = {{0x80u, 0x00u, 0x4fu, 0x08u, 0x06u, 0x00u, 0x80u, 0x04u, 0xc4u}, 1u, {DFI_ABILITY_GOODASGOLD, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Politoed -- abilities: drizzle */
    /*    learns: Protect, Muddy Water, Ice Beam, Hypnosis, Focus Blast, Weather Ball, Psychic, */
    /*    Hyper Voice, Helping Hand, Encore, Double-Edge, Liquidation, Ice Punch, Low Kick */
    [DFI_FORME_POLITOED] = {{0x80u, 0x0du, 0x11u, 0x08u, 0x00u, 0x09u, 0x60u, 0x80u, 0x41u}, 1u, {DFI_ABILITY_DRIZZLE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Golisopod -- abilities: emergencyexit */
    /*    learns: Close Combat, Protect, Muddy Water, Ice Beam, Swords Dance, Focus Blast, Leech Life, */
    /*    Iron Head, Drill Run, Snarl, Sucker Punch, Aqua Jet, U-turn, Rock Slide, Throat Chop, Scald, */
    /*    Wide Guard, First Impression, Bulk Up, Liquidation, Shadow Claw */
    [DFI_FORME_GOLISOPOD] = {{0xa0u, 0x45u, 0xe1u, 0x04u, 0x00u, 0x20u, 0x1du, 0xe3u, 0x02u}, 1u, {DFI_ABILITY_EMERGENCYEXIT, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Golisopod-Mega -- abilities: toughclaws */
    /*    learns: nothing */
    [DFI_FORME_GOLISOPODMEGA] = {{0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u}, 1u, {DFI_ABILITY_TOUGHCLAWS, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Archaludon -- abilities: stamina */
    /*    learns: Protect, Swords Dance, Iron Head, Dragon Pulse, Electro Shot, Snarl, Reflect, */
    /*    Light Screen, Draco Meteor, Rock Slide, Double-Edge, Thunderbolt, Flash Cannon */
    [DFI_FORME_ARCHALUDON] = {{0x80u, 0x40u, 0x40u, 0x07u, 0x06u, 0x02u, 0xc8u, 0x04u, 0x00u}, 1u, {DFI_ABILITY_STAMINA, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Farigiraf -- abilities: armortail */
    /*    learns: High Horsepower, Protect, Shadow Ball, Nasty Plot, Iron Head, Psychic, Grass Knot, */
    /*    Trick Room, Reflect, Light Screen, Hyper Voice, Helping Hand, Double-Edge, Thunderbolt, */
    /*    Psychic Noise, Low Kick, Dazzling Gleam */
    [DFI_FORME_FARIGIRAF] = {{0x88u, 0x00u, 0x4cu, 0x38u, 0x06u, 0x09u, 0xc0u, 0x00u, 0xd0u}, 1u, {DFI_ABILITY_ARMORTAIL, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Charizard -- abilities: blaze */
    /*    learns: Protect, Swords Dance, Focus Blast, Weather Ball, Dragon Pulse, Heat Wave, Hurricane, */
    /*    Flare Blitz, Helping Hand, Rock Slide, Double-Edge, Shadow Claw */
    [DFI_FORME_CHARIZARD] = {{0x80u, 0x40u, 0x11u, 0xc1u, 0x40u, 0x08u, 0x48u, 0x00u, 0x02u}, 1u, {DFI_ABILITY_BLAZE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Charizard-Mega-Y -- abilities: drought */
    /*    learns: nothing */
    [DFI_FORME_CHARIZARDMEGAY] = {{0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u}, 1u, {DFI_ABILITY_DROUGHT, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Grimmsnarl -- abilities: prankster */
    /*    learns: Fake Out, Protect, Focus Blast, Nasty Plot, Leech Life, Spirit Break, Reflect, */
    /*    Light Screen, Parting Shot, Sucker Punch, Throat Chop, Bulk Up, Ice Punch, Shadow Claw, Low Kick, */
    /*    Dazzling Gleam */
    [DFI_FORME_GRIMMSNARL] = {{0x84u, 0x00u, 0x29u, 0x00u, 0x0fu, 0x20u, 0x10u, 0x40u, 0xc3u}, 1u, {DFI_ABILITY_PRANKSTER, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Sneasler -- abilities: unburden */
    /*    learns: Fake Out, Close Combat, Protect, Swords Dance, Focus Blast, Shadow Ball, Nasty Plot, */
    /*    Grass Knot, Dire Claw, U-turn, Rock Slide, Throat Chop, Bulk Up, Shadow Claw, Low Kick */
    [DFI_FORME_SNEASLER] = {{0xa4u, 0x40u, 0x0du, 0x10u, 0x20u, 0x00u, 0x1cu, 0x40u, 0x42u}, 1u, {DFI_ABILITY_UNBURDEN, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Incineroar -- abilities: blaze, intimidate */
    /*    learns: Fake Out, Close Combat, Protect, Swords Dance, Focus Blast, Nasty Plot, Leech Life, */
    /*    Iron Head, Snarl, Heat Wave, Parting Shot, Flare Blitz, Darkest Lariat, Helping Hand, */
    /*    Throat Chop, Double-Edge, Bulk Up, Shadow Claw, Low Kick */
    [DFI_FORME_INCINEROAR] = {{0xa4u, 0x40u, 0x69u, 0x44u, 0xc8u, 0x08u, 0x50u, 0x40u, 0x42u}, 2u, {DFI_ABILITY_BLAZE, DFI_ABILITY_INTIMIDATE, DFI_CLOSURE_NONE}},
    /* Salamence -- abilities: intimidate */
    /*    learns: Tailwind, Protect, Iron Head, Dragon Pulse, Heat Wave, Hurricane, Hyper Voice, */
    /*    Draco Meteor, Helping Hand, Rock Slide, Double-Edge, Shadow Claw */
    [DFI_FORME_SALAMENCE] = {{0xc0u, 0x00u, 0x40u, 0xc1u, 0x00u, 0x0bu, 0x48u, 0x00u, 0x02u}, 1u, {DFI_ABILITY_INTIMIDATE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Salamence-Mega -- abilities: aerilate */
    /*    learns: nothing */
    [DFI_FORME_SALAMENCEMEGA] = {{0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u}, 1u, {DFI_ABILITY_AERILATE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Indeedee-F -- abilities: psychicsurge */
    /*    learns: Fake Out, Protect, Shadow Ball, Psychic, Trick Room, Reflect, Light Screen, Hyper Voice, */
    /*    Follow Me, Helping Hand, Dazzling Gleam */
    [DFI_FORME_INDEEDEEF] = {{0x84u, 0x00u, 0x04u, 0x28u, 0x06u, 0x0du, 0x00u, 0x00u, 0x80u}, 1u, {DFI_ABILITY_PSYCHICSURGE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Kingambit -- abilities: defiant */
    /*    learns: Protect, Swords Dance, Focus Blast, Iron Head, Snarl, Grass Knot, Kowtow Cleave, */
    /*    Sucker Punch, Throat Chop, Flash Cannon, Shadow Claw, Low Kick */
    [DFI_FORME_KINGAMBIT] = {{0x80u, 0x40u, 0x41u, 0x14u, 0x00u, 0x30u, 0x10u, 0x04u, 0x42u}, 1u, {DFI_ABILITY_DEFIANT, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Basculegion -- abilities: adaptability */
    /*    learns: Protect, Muddy Water, Ice Beam, Shadow Ball, Last Respects, Wave Crash, Aqua Jet, */
    /*    Flip Turn, Double-Edge, Head Smash, Liquidation, Soak */
    [DFI_FORME_BASCULEGION] = {{0x80u, 0x05u, 0x04u, 0x00u, 0x00u, 0xc0u, 0x43u, 0x90u, 0x08u}, 1u, {DFI_ABILITY_ADAPTABILITY, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Pelipper -- abilities: drizzle */
    /*    learns: Brave Bird, Tailwind, Protect, Muddy Water, Ice Beam, Weather Ball, Hurricane, */
    /*    Helping Hand, U-turn, Wide Guard, Liquidation, Soak */
    [DFI_FORME_PELIPPER] = {{0xd0u, 0x05u, 0x10u, 0x80u, 0x00u, 0x08u, 0x04u, 0x82u, 0x08u}, 1u, {DFI_ABILITY_DRIZZLE, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Arcanine-Hisui -- abilities: intimidate, flashfire, rockhead */
    /*    learns: Close Combat, Protect, Iron Head, Dragon Pulse, Snarl, Heat Wave, Flare Blitz, */
    /*    Hyper Voice, Helping Hand, Rock Slide, Double-Edge, Extreme Speed, Head Smash */
    [DFI_FORME_ARCANINEHISUI] = {{0xa0u, 0x00u, 0x40u, 0x45u, 0x40u, 0x09u, 0x48u, 0x18u, 0x00u}, 3u, {DFI_ABILITY_INTIMIDATE, DFI_ABILITY_FLASHFIRE, DFI_ABILITY_ROCKHEAD}},
    /* Annihilape -- abilities: defiant */
    /*    learns: Close Combat, Protect, Focus Blast, Shadow Ball, Helping Hand, U-turn, Rock Slide, */
    /*    Throat Chop, Encore, Double-Edge, Thunderbolt, Bulk Up, Ice Punch, Shadow Claw, Low Kick */
    [DFI_FORME_ANNIHILAPE] = {{0xa0u, 0x00u, 0x05u, 0x00u, 0x00u, 0x08u, 0xfcu, 0x40u, 0x43u}, 1u, {DFI_ABILITY_DEFIANT, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Floette-Eternal -- abilities: flowerveil */
    /*    learns: Protect, Psychic, Grass Knot, Light Screen, Helping Hand, Dazzling Gleam */
    [DFI_FORME_FLOETTEETERNAL] = {{0x80u, 0x00u, 0x00u, 0x18u, 0x04u, 0x08u, 0x00u, 0x00u, 0x80u}, 1u, {DFI_ABILITY_FLOWERVEIL, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
    /* Floette-Mega -- abilities: fairyaura */
    /*    learns: nothing */
    [DFI_FORME_FLOETTEMEGA] = {{0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u}, 1u, {DFI_ABILITY_FAIRYAURA, DFI_CLOSURE_NONE, DFI_CLOSURE_NONE}},
};

const uint8_t dfi_pool_table_hash[32] = {
    0x1du, 0x40u, 0x27u, 0x45u, 0xebu, 0xa5u, 0xe5u, 0xe0u,
    0xb4u, 0x87u, 0x8fu, 0xeeu, 0x1eu, 0x8du, 0x0au, 0xa1u,
    0x0du, 0xb8u, 0x87u, 0x5au, 0x0eu, 0xf1u, 0x07u, 0x7au,
    0x62u, 0x53u, 0x58u, 0xdbu, 0x79u, 0x1cu, 0xeau, 0x68u,
};

static size_t dfi_pool_put_u16(uint8_t *out, size_t n, uint32_t v)
{
    out[n] = (uint8_t)(v & 0xFFu);             /* wide-operands-reviewed */
    out[n + 1u] = (uint8_t)((v >> 8u) & 0xFFu); /* wide-operands-reviewed */
    return n + 2u;
}

size_t dfi_pool_canonical_bytes_of(uint8_t *out, size_t capacity, uint32_t formes, uint32_t moves, uint32_t items,
                                   uint32_t abilities, uint32_t immunity_mask)
{
    if (formes > DFI_POOL_FORME_COUNT || moves > DFI_POOL_MOVE_COUNT || items > DFI_POOL_ITEM_COUNT ||
        abilities > DFI_POOL_ABILITY_COUNT) {
        return 0u;
    }
    /* counts, 24 bytes per forme, 29 per move, 2 per item, chart, immunity, natures */
    const size_t size = 12u + (size_t)formes * 24u + (size_t)moves * 29u + (size_t)items * 2u +
                        DFI_TYPE_COUNT * DFI_TYPE_COUNT + DFI_TYPE_COUNT + DFI_NATURE_COUNT * 2u;
    if (capacity < size) {
        return 0u;
    }
    size_t n = 0u;
    n = dfi_pool_put_u16(out, n, formes);
    n = dfi_pool_put_u16(out, n, moves);
    n = dfi_pool_put_u16(out, n, items);
    n = dfi_pool_put_u16(out, n, abilities);
    n = dfi_pool_put_u16(out, n, DFI_TYPE_COUNT);
    n = dfi_pool_put_u16(out, n, DFI_NATURE_COUNT);
    for (uint32_t i = 0u; i < formes; ++i) {
        const dfi_forme_data *f = &dfi_pool_formes[i];
        n = dfi_pool_put_u16(out, n, f->dex_num);
        out[n++] = f->types[0];
        out[n++] = f->types[1];
        for (uint32_t k = 0u; k < DFI_STAT_COUNT; ++k) {
            out[n++] = f->base[k];
        }
        n = dfi_pool_put_u16(out, n, f->weight_hg);
        out[n++] = f->ability;
        out[n++] = f->gender_rule;
        out[n++] = f->is_mega;
        out[n++] = f->base_forme;
        out[n++] = f->mega_forme;
        out[n++] = f->mega_item;
        out[n++] = f->set_item;
        out[n++] = f->set_move_count;
        for (uint32_t k = 0u; k < 4u; ++k) {
            out[n++] = f->set_moves[k];
        }
    }
    for (uint32_t i = 0u; i < moves; ++i) {
        const dfi_move_data *m = &dfi_pool_moves[i];
        out[n++] = m->type;
        out[n++] = m->category;
        out[n++] = m->base_power;
        out[n++] = m->accuracy;
        out[n++] = m->pp_base;
        out[n++] = m->pp_max;
        out[n++] = m->priority;
        out[n++] = m->target_class;
        out[n++] = m->crit_ratio;
        out[n++] = m->flags;
        out[n++] = m->recoil[0];
        out[n++] = m->recoil[1];
        out[n++] = m->drain[0];
        out[n++] = m->drain[1];
        out[n++] = m->sec_chance;
        out[n++] = m->sec_kind;
        out[n++] = m->sec_param;
        out[n++] = m->boost_role;
        for (uint32_t k = 0u; k < DFI_STAGE_COUNT; ++k) {
            out[n++] = m->boosts[k];
        }
        out[n++] = m->primary_status;
        out[n++] = m->side_condition;
        out[n++] = m->pseudo_weather;
        out[n++] = m->special;
    }
    for (uint32_t i = 0u; i < items; ++i) {
        out[n++] = dfi_pool_items[i].mega_base;
        out[n++] = dfi_pool_items[i].mega_forme;
    }
    for (uint32_t d = 0u; d < DFI_TYPE_COUNT; ++d) {
        for (uint32_t a = 0u; a < DFI_TYPE_COUNT; ++a) {
            out[n++] = dfi_closure_type_chart[d][a];
        }
    }
    for (uint32_t i = 0u; i < DFI_TYPE_COUNT; ++i) {
        out[n++] = (uint8_t)(dfi_pool_type_immunity[i] & immunity_mask); /* wide-operands-reviewed: < 256 */
    }
    for (uint32_t i = 0u; i < DFI_NATURE_COUNT; ++i) {
        out[n++] = dfi_closure_natures[i].plus;
        out[n++] = dfi_closure_natures[i].minus;
    }
    return n;
}

size_t dfi_pool_canonical_bytes(uint8_t *out, size_t capacity)
{
    if (capacity < DFI_POOL_CANONICAL_SIZE) {
        return 0u;
    }
    size_t n = dfi_pool_canonical_bytes_of(out, capacity, DFI_POOL_FORME_COUNT, DFI_POOL_MOVE_COUNT,
                                           DFI_POOL_ITEM_COUNT, DFI_POOL_ABILITY_COUNT, 0xFFu);
    for (uint32_t i = 0u; i < DFI_POOL_ITEM_COUNT; ++i) {
        out[n++] = dfi_pool_item_family[i].family;
        out[n++] = dfi_pool_item_family[i].type;
    }
    for (uint32_t i = 0u; i < DFI_POOL_ABILITY_COUNT; ++i) {
        out[n++] = dfi_pool_ability_family[i].family;
        out[n++] = dfi_pool_ability_family[i].param;
    }
    for (uint32_t i = 0u; i < DFI_POOL_FORME_COUNT; ++i) {
        const dfi_forme_legal *l = &dfi_pool_forme_legal[i];
        for (uint32_t k = 0u; k < DFI_POOL_LEARN_BYTES; ++k) {
            out[n++] = l->learnable[k];
        }
        out[n++] = l->ability_count;
        for (uint32_t k = 0u; k < DFI_POOL_FORME_ABILITIES_MAX; ++k) {
            out[n++] = l->abilities[k];
        }
    }
    return n;
}
